### ISSUE TITLE
Add support for lxd image generation

### ISSUE THREAD

**Issue by palica** [OSInside/kiwi#1033]
## Problem description
Kiwi seems to support a lot of images and formats, but doesn't seem to support LXD/LXC image generation

## Expected behaviour
It would be nice to have native support for lxd image

Basic information about the format of the image that LXD is expecting and should be able to import can be found here:
https://lxd.readthedocs.io/en/latest/image-handling/#image-format

There are also some unofficial images being already generated for opensuse.
Those can be found here:

> https://us.images.linuxcontainers.org/
> https://github.com/lxc/lxc-ci/tree/master/images
> https://github.com/lxc/lxc-ci/blob/master/images/opensuse.yaml
> https://jenkins.linuxcontainers.org/job/image-opensuse/

Thank you for considering!

**Comment by dcermak** [comment]
I didn't have the time to look at this in full detail yet, but LXD looks relatively simple to implement: the "image" is actually just a tarball of the root filesystem plus a `metadata.yaml` file. That file has only three mandatory components: creation date, architecture and the name of the container.

What could be tricky is the following: LXD supports templates that can be used to customize the creation of e.g. `/etc/hosts`. I've been told that these are generally not necessary, but we should at least keep their existence in mind. Also, these templates are not part of the root tarball itself, so putting them into the overlay `root.tar.gz` is not really an option.

I guess we could handle the templates by extending the RNG schema and add something like this:
``` XML
<lxd_templates>
  <lxd_template
    filename="template_file.tpl" 
    when="create,rename" 
    create_only="true/false"
    destination="/etc/hostname" />
</lxd_templates>
```
and put the `template_file.tpl` into the image description directory.

Other ideas are of course welcome!

**Comment by Conan-Kudo** [comment]
I'd actually be okay with only supporting a subset of functionality initially. I imagine that there are much better methods for deploying customizations, and you start getting into really weird territory with this stuff, as distributions tend to differ quite a bit here.

Also, it should be pointed out that the legacy KIWI supported LXC image creation, and the current KIWI dropped it due to lack of interest or demand. With LXD not officially available in Fedora or openSUSE (the two platforms that kiwi is officially validated on as an execution host) as a system package, it would be hard to justify supporting this.

**Comment by palica** [comment]
There is some recent work being done on OBS. https://build.opensuse.org/package/show/Virtualization:containers/lxd 

Christian Brauner (chbrauner) is one of the core developers of LXD. I think it would be nice to add support for this. Once LXD gets maybe accepted to Factory.

**Comment by dcermak** [comment]
@schaefi @davidcassany What's your opinion on this? Include rudimentary LXD support or not before LXD is supported by Fedora and/or openSUSE or not at all?

**Comment by schaefi** [comment]
To be honest, I haven't looked into this one deep enough to share a good comment. I have no objections adding support for adding another image type. However as of this time the coding resources can only come from the community because David and myself recently agreed on the P1/P2 list to work on for the next month. Unless there is a high demand or business case (from the suse side) we are currently set with our tasks. In my case there is also public cloud work that has to get done and maybe David is involved in some work on the Kubic side as well.

I don't consider this one as low hanging fruits, so a new image type needs a well design and integration which I currently have no time for.

@dcermak as you opened the issue you said:

> It would be nice to have native support for lxd image

Is this what it says; nice to have ? or is there more happening behind the scenes which we don't know ?
Shifting prios can always be done if there are good reasons.

Thanks

**Comment by dcermak** [comment]
From my point of view it's currently just "nice to have". @palica Told me about LXD on IRC and it sounds very promising (a bit like vagrant, but with containers), so I took a look at it, but nothing more.

However, since rudimentary support appears to be really simple to implement, I thought I'd ask you, in case I get bored in my free time ;-)

**Comment by palica** [comment]
Well LXD is a like a big brother of LXC adding management to lxc images, supporting server clustering and networking, proxying, live migration and other goodies. It makes e.g. testing of packages easy as spin a new ephemeral container from base image, do your testing (deps, compiling ...) and if successful poweroff the container, which will get auto-destroyed.

I understand that there is no pressure from opensuse or SLE to implement this, but still I think it is one of the container solutions that can be more appealing than docker.

**Comment by Conan-Kudo** [comment]
@palica It'd be more interesting for me if it was natively packaged in Fedora too. As the maintainer of the kiwi package in Fedora and also a user of various container things, LXD is interesting to me. Unfortunately, even with me doing the work to make LXD "friendly" for the Fedora SELinux policy, no one seemed to want to do it. 😢

**Comment by palica** [comment]
@Conan-Kudo I briefly searched on the net and this is what I've found:

https://copr.fedorainfracloud.org/coprs/ganto/lxd/packages/
https://copr.fedorainfracloud.org/coprs/iavael/lxd-epel/packages/

I don't know if you could together with those two users get it into working state.

**Comment by palica** [comment]
@Conan-Kudo also note that since some time the lxd.tarball contains all the needed source and deps.

  /lxd-3.11/dist/src/

**Comment by schaefi** [comment]
During our sprint planning we discussed this one again and we think there is currently no big business case or customer demand. We'll keep this open but without a priority. Your thoughts are very much appreciated. If we come to an agreement that we don't need it in kiwi this one can also be closed.

Thanks

**Comment by schaefi** [comment]
seems there is no further interest, going to close this for now
