### ISSUE TITLE
groups attribute of user could be more intuitive/convenient to use

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1059]
## Problem description

We allow the customization of the primary and supplementary groups of a user account created by KIWI via the `groups` attribute:
``` XML
  <users>
    <user
      password="this_is_soo_insecure"  pwdformat="plain"
      home="/home/me" name="me"
      groups="users;video;libvirt;wheel"
    />
  </users>
```

The first entry in the `groups` attribute becomes the primary group and the remaining ones become the supplementary groups.

I find this inconvenient, as it is a) impossible to only set supplementary groups  and b) it is not entirely obvious for someone not acquainted with the schemal what is happening.

I propose to follow Ansible's example and provide an attribute `group` (for the primary group) and `groups` (for the supplementary groups). The above example would then become:
``` XML
  <users>
    <user
      password="this_is_soo_insecure" pwdformat="plain"
      home="/home/me" name="me"
      group="users" groups="video;libvirt;wheel"
    />
  </users>
```

**Comment by davidcassany** [comment]
I like this suggestion. I find it handy to be capable to only define supplementary groups and let the primary group be the default. :+1:

**Comment by davidcassany** [comment]
After some more discussions I believe that such a change in the schema just for that might not be worth. This is not a new feature neither solving a bug, thus it does not deserve a schema change and version bump.

In order to improve I believe we could add and INFO message stating the primary group of the user. This should make it easier for anyone debugging a user creation what is going on. Also the current documentation for kiwi.rnc and sphinx docs could be reviewed.
