### ISSUE TITLE
Generate and ship Python stub files

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1080]
## Problem description

KIWI still supports Python 2 and thus cannot yet use typing hints as introduced by [PEP484](https://www.python.org/dev/peps/pep-0484/), however we could create so-called stub files. These are files with the `.pyi` extension that co-exist next to the Python sources but contain no implementation, only declarations with type hints (comparable to C/C++ header files), e.g.:
``` Python
class Result(object):
    __doc__: str
    class_version: int
    result_files: Dict[Any, `namedtuple-result_file_type-filename-use_for_bundle-compress-shasum`]
    xml_state: Any
    def __init__(self, xml_state) -> None: ...
    def add(self, key, filename, use_for_bundle = ..., compress = ..., shasum = ...) -> None: ...
    def dump(self, filename) -> None: ...
    def get_results(self) -> Dict[Any, `namedtuple-result_file_type-filename-use_for_bundle-compress-shasum`]: ...
    @classmethod
    def load(cls, filename) -> Any: ...
    def print_results(self) -> None: ...
    def verify_image_size(self, size_limit, filename) -> None: ...
```

These files can be autogenerated by [pytype](https://github.com/google/pytype) and then re-used by [mypy](http://mypy.readthedocs.io/) to perform type checking and static analysis.

Eventually, once we drop Python 2 support, we can use pytype to merge stub files into the actual code base.

Opinions concerning that?

**Comment by schaefi** [comment]
It sounds like a nice side or hackweek project

From a project perspective I think the way kiwi operates doesn't need to put on strict type checking. I personally don't see much value at this point because 80% of the processing kiwi invokes external tools. The data that makes it into the implementation runs through a schema that is strong typed, validated and  syntactically checked. This gives a bit of freedom handling that data inside of the implementation.

I know people that are used to writing strong typed languages like C, C++ have a big problem if they don't know what type the data is and to what it can be casted to safely. I myself were into Qt based projects for a long time and know both worlds. From my experience the choice for strong typed language or "scripting" depends on the problem that should be solved. With kiwi we knew from the beginning on that we will be forced to execute a lot of stuff that we just have to trust. A strong interpretation of the data types wouldn't had much benefit as 90% of it would be string and patterns.

For what it makes sense imho is on the public interface and for people that use the kiwi module in their own applications. Thus I had planned to use type hints on the public methods of the interfaces we have in kiwi. However I thought we use the py3 native type hint implemenation: https://docs.python.org/3/library/typing.html after we have dropped py2 support

Putting any effort in py2 which is on the way to leave this planet doesn't sound useful to me

Just my2cents

@davidcassany what's your view on that ?

**Comment by dcermak** [comment]
> For what it makes sense imho is on the public interface and for people that use the kiwi module in their own applications. Thus I had planned to use type hints on the public methods of the interfaces we have in kiwi. However I thought we use the py3 native type hint implemenation: https://docs.python.org/3/library/typing.html after we have dropped py2 support

Python stub files use Python3 native typing, I am not even sure if Python2 cares about them. The advantage of them is: we can add them now and don't need to add those ugly Python2 compat type hints.

> It sounds like a nice side or hackweek project

It's mostly boring grind. You can auto-generate the stubs with pytype, but they have to be cleaned up as it cannot infer most of the types.

**Comment by schaefi** [comment]
Doing that for the public interfaces sounds like a great extension. It offers more protection for people that use kiwi as module in their own projects

**Comment by schaefi** [comment]
@dcermak After conversation with David we currently won't give this a priority as there is other work to be done first. Therefore my question: Are you willing to take on the work in this regard since py2 was dropped ?

**Comment by dcermak** [comment]
Now that we have dropped python2 support, we might as well just add type hints to kiwi itself and don't bother with maintaining stub files alongside.

I'll see if/when I have time to work on this.

**Comment by schaefi** [comment]
yep we had the discussion on riot and we will go with the type hints as supported by py3. 
the work has already been started: https://github.com/OSInside/kiwi/pull/1176
