### ISSUE TITLE
Add support for Arch Linux images / Pacman package manager

### ISSUE THREAD

**Issue by Pernat1y** [OSInside/kiwi#1098]
## Problem description
Currently, kiwi supports neither Arch Linux nor Pacman package manager.
It will be nice to have such support :)

## OS and Software information
+ KIWI version: 9.17.39
+ Operating system: openSUSE Leap 15.1
+ OBS version: -

**Comment by schaefi** [comment]
@davidcassany has done some great work during hackweek on this. As it currently has no prio there is not ETA for a PR, but there will be one as soon as David see fit

**Comment by davidcassany** [comment]
@Pernat1y yes I did some work regarding that and managed to build some ISO, VMX and OEM images based on bios firmware (for efi I am missing the linuxefi grub2 module in Arch) without big issues.

I am currently coding some unit tests, api docs and some other details. As @schaefi said this is a low prio work, thus I am not entirely sure when I'll manage to get all that done.

Would you be willing to test the implementation and provide feedback? I could commit the code in a separate branch meanwhile.

**Comment by Pernat1y** [comment]
> Would you be willing to test the implementation and provide feedback?
Sure

**Comment by Pernat1y** [comment]
> Would you be willing to test the implementation and provide feedback? I could commit the code in a separate branch meanwhile.

Sure

**Comment by schaefi** [comment]
David is currently on vacation. He will be back next week. Just to let you know there is a delay in response time. Thanks for the offer to test :+1:

**Comment by davidcassany** [comment]
@Pernat1y I have just pushed a `poc_pacman_for_arch` branch that can be used to create Arch images from an Arch host (this is the only I have tested so far). I do not have prepared yet an pacman package for KIWI but it is on my TODO list. In order to use kiwi from Arch I just checked out code and set a development environment. Some hints on how to create it are documented [here](https://osinside.github.io/kiwi/development.html), they were not written for Arch, but I do not remember struggling much to sort out how to do it for Arch.

**Comment by Pernat1y** [comment]
Thanks. Will look into it.

**Comment by davidcassany** [comment]
Note that the travis validation is failing since I have not yet finished the development. Unit tests aren't complete and few adaptations of the current ones are required, however it should be possible to build basic Arch images.

I have posted a PoC Arch image [here](https://github.com/OSInside/kiwi-descriptions/tree/poc_arch_images/arch/x86_64/arch). Please note that I had to add the kiwi dracut modules inside the root tree since they are not yet packaged for Arch. Also, as a consequence of missing dracut modules packages, in order to build OEM and ISO images for Arch you should disable the dracut runtime checks by adding in `/etc/kiwi.yml` of your host the following content:

```yml
runtime_checks:
  - disable:
    - check_dracut_module_for_oem_install_in_package_list
    - check_dracut_module_for_live_iso_in_package_list
    - check_dracut_module_for_disk_overlay_in_package_list
    - check_dracut_module_for_disk_oem_in_package_list
```

This image was working fine from an Arch host about a month ago.
