### ISSUE TITLE
k.user.password.attribute not optional

### ISSUE THREAD

**Issue by M0ses** [OSInside/kiwi#1161]
## Problem description

If I try to build a kiwi image with a ```<user>``` element which contains no attribute ```password``` I get the following error message:

```
error: element "user" missing required attribute "password"
```

## Expected behaviour

According to the schema documentation, password should be optional (which IMHO makes sense, esp. for containers)
SEE:
https://osinside.github.io/kiwi/development/schema.html#

But it looks like its not defined as optional attribute in the kiwi.rng

https://github.com/OSInside/kiwi/blob/master/kiwi/schema/kiwi.rng#L2790

## Steps to reproduce the behaviour

Try to build an image with an user element without attribute password

## OS and Software information
+ KIWI version: 9.17.42
+ Operating system: opensuse leap 15.1
+ OBS version: 2.11.alpha
+ KIWI schema version: 7.1

**Comment by davidcassany** [comment]
Passwors is mandatory since 9.17.39 see #1061. I checked the documentation and I could not see were it is stated to be optional see https://osinside.github.io/kiwi/development/schema.html#id584.

For leap 15.1 we have KIWI 9.17.15 thus in Leap 15.1 password is still optional and according to #1061 leads to a `usermod` error.

For the specific case you mention about containers I believe that you might require users like `wwwrun` which are usually provided by an specific package or created within the installation of some application.

**Comment by M0ses** [comment]
Ok, I got confused by https://osinside.github.io/kiwi/development/schema.html#id317 where the password attribute is documented as optional.
