### ISSUE TITLE
oem recovery - tar failure

### ISSUE THREAD

**Issue by kanthans** [OSInside/kiwi#1166]
Hi
## Problem description
We are trying to setup oem recovery option. 
However this fails and terminates with following errors
```
KiwiCommandError: tar: stderr: tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow them.  Please, rearrange them properly.
tar: --exclude ‘./dev’ has no effect
tar: --exclude ‘./proc’ has no effect
tar: --exclude ‘./sys’ has no effect
tar: Exiting with failure status due to previous errors
```
We noticed the reason for the error is exclude parameters are after the path to be included in the tar archive. 

we assume the positional arguments have come only in tar version 1.30 and above. tar 1.29 seems to be working for similar exclusions, though we have not tested ourselves. We are refering to similar problem reported for few other tools. 

## OS and Software information
+ KIWI version: 9.18.9
+ Operating system: SLED 15
+ OBS version: 
+ tar version 1.30

**Comment by schaefi** [comment]
Thanks much, this is valuable information. A word on the recovery feature; I have implemented this as part of a hackweek project and we added it to the oemboot deployment as an experimental feature. Since that time nobody really jumped on it. So what I'm saying is, this feature is rather untested. If you plan to make use of recovery in a production environment this should be tested carefully beforehand and probably more patches are needed since it's behind some distribution releases.

Also please note the recovery implementation is part of the custom kiwi initrd oemboot. We recommend people to switch to dracut as initrd system and we haven't ported the recovery system as a dracut module since there was not much interest in it so far.

All this just as a background information for you.

Thanks

**Comment by schaefi** [comment]
Tracker information. The code to be fixed is here:

* https://github.com/OSInside/kiwi-descriptions/blob/master/custom_boot/arch/x86_64/oemboot/dump
* https://github.com/OSInside/kiwi-descriptions/blob/master/custom_boot/arch/x86_64/oemboot/repart

Potential fix must be done for all archs

**Comment by kanthans** [comment]
Thank for the info. Let me give it a try over this weekend.

**Comment by kanthans** [comment]
Is the tar command implemented vide the bash script only. The system is not calling the bash-script mentioned above. the scripts are there in the default path /usr/share/kiwi/custom_boot/oemboot/dump & repart file. Do we need to copy the file or the oemboot directory to the one containing our build xml file (config.xml or sled.kiwi).

Mean while I located tar.py file under  /usr/lib/python3.6/site-packages/kiwi/archive directory.  I tried editing this file, but with some success. I could make the recovery file getting build by using this, but the process completes after recovery image is built into the raw file. The install.iso file is not getting created after the process. 

Am i making some mistake.

**Comment by schaefi** [comment]
First part of the fix available here. I'll come up with further information on your questions next

* https://github.com/OSInside/kiwi-descriptions/pull/53

**Comment by schaefi** [comment]
The same fix applied to the legacy kiwi version

* https://github.com/OSInside/kiwi-legacy/pull/680

**Comment by schaefi** [comment]
The fixes mentioned here are fixing the order problem of tar in the related code parts.

Now back to your question. The recovery system was considered experimental and implemented in the legacy (perl based) kiwi version which you can find here:

* https://build.opensuse.org/package/show/Virtualization:Appliances/kiwi

As you can see this version is being build and supported up to SLES12-SP3 beginning with SLES12-SP4 the next generation kiwi version was introduced. Starting with SLES15 only the next generation kiwi is available.

As your target is sle15 this will be a problem. As I already wrote we didn't ported the feature to the next generation kiwi builder, you won't be able to build the recovery metadata even if the fix here becomes merged. Actually you need to use the old kiwi to make use of recovery.

If you are still interested I can offer to enable the sle15 target to build the old kiwi on the Virt:App project for sle15. But as I said there is no warranty that this will work and we can only spent a limited amount of time on it as it currently has no priority. SUSE put on the REAR project for recovery and the ideas we had doing this on an imaging level were not taken serious as of today.

Let me know what you think

Thanks

**Comment by kanthans** [comment]
Thank you for effort in getting this fixed in kiwi-legacy

Can you please provide us SLE15 support on kiwi-legacy. We will work with that and check.

Thank you once again.

**Comment by schaefi** [comment]
ok here we go. The package can be found here:

* https://download.opensuse.org/repositories/Virtualization:/Appliances/SLE_15/x86_64/

The respective documentation for this version of kiwi is here:

* https://doc.opensuse.org/projects/kiwi/doc/

search for "recovery" and you will find the available oem-recovery attributes supported in the XML setup.

I just wanted to make this clear: This kiwi version is not officially available in the sle15 code base and also hasn't been tested for it. In theory you should be able to build an oem image with it but it could also happen that you run into other (not recovery related) problems.

So you are on an experimental path.

Thanks

**Comment by schaefi** [comment]
I would start with the following type definition

```xml
<type image="oem" filesystem="ext3" boot="oemboot/suse-SLES12" bootloader="grub2" kernelcmdline="splash">
            <oemconfig>
                <oem-recovery>true</oem-recovery>
                <oem-swap>false</oem-swap>
            </oemconfig>
        </type>
```

Also note there are no sle15 oemboot descriptions (not supported as I said). So you have to build the sle15 initrd from a sle12 description: ```oemboot/suse-SLES12``` ... Let's see what happens

**Comment by schaefi** [comment]
Going to close this one since the reported defect has been addressed. I would still be interested if the oem recovery in the form as it exists in the legacy kiwi is in any case useful to you. If it turns out it could be useful we might start a discussion on the mailing list about a recovery feature to be implemented in this (next generation) kiwi code stream.

Since we had the feature experimental in the legacy kiwi I remember most people that tried it were interested in the factory reset but not so much in the recovery tar which tried to reset OS data but keep user data. The process of a factory reset I would implement pretty differently compared to the ideas we had before.

Maybe you can share more of your use case and/or start the discussion on the kiwi mailing list

Thanks
