### ISSUE TITLE
embed entrypoint sources

### ISSUE THREAD

**Issue by dirkmueller** [OSInside/kiwi#1172]
## Problem description

When using kiwi for container building, a common problem is the need to embed the "entrypoint script" into the build process. This can be done currently fairly convoluted fashion by having <archive> pointing to a build service generated tarball that contains just one file. 

We could make that easier by having something that behaves similarly to how the rpm "Sources:" work. it can be a full url (so an obs source service can fetch and cache the file in the package container in obs) but kiwi handles it as an additional source file to install inside the container. potentially we could have the config.sh be able to install it manually to a location, or an attribute on the <source target>.

```
<source target="/usr/local/bin/entrypoint.sh">http://github.com/foo/bar/tree/master/entrypoint.sh</source>
```

could be an example of that, but I'm not tied to any particular implementation idea. Main goal is to get a way around the "<archive>foobar.tar</archive>" step of having to generate a tarball that only contains one file.

**Comment by davidcassany** [comment]
In order to add files in an image KIWI includes already some mechanisms. One can include some extra files by having them in the root-tree overlay (file structure applied on image `/` after installing all the packages but before running config script `config.sh`), this can be provided as tarball or as plain `root/*` directory structure in the KIWI project folder.

Additionally one can add tarball archives inside `<packages>` section with something like `<archive name="foobar.tar"/>`. I assume you are in this use case.

Having the entrypoint sources not visible in OBS I can see how annoying it can be, specially if sources are not hosted anywhere else. We also faced such an issue in the containers team and within the KIWI integration tests. For that we opted to keep all sources in github without making a tarball of the root-tree overlay (see [this doker](https://github.com/OSInside/kiwi/tree/master/build-tests/x86/test-image-docker) image as an example). Then we just perform all image sources changes at github and sources can be fetched to OBS by an obs-service, the following would do the trick in this case:

```xml
<services>
    <service name="obs_scm">
        <param name="url">https://github.com/SUSE/kiwi.git</param>
        <param name="scm">git</param>
        <param name="subdir">build-tests/x86/test-image-docker</param>
        <param name="extract">appliance.kiwi</param>
        <param name="extract">config.sh</param>
        <param name="exclude">root</param>
        <param name="revision">master</param>
    </service>
    <service name="obs_scm">
        <param name="url">https://github.com/SUSE/kiwi.git</param>
        <param name="scm">git</param>
        <param name="subdir">build-tests/x86/test-image-docker/root</param>
        <param name="filename">root</param>
        <param name="version">_none_</param>
        <param name="revision">master</param>
    </service>
</services>
```
See it in this [project](https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86/test-image-docker).

I believe this setup is not that different from what you suggest for its usage within OBS.

Including files in images build in OBS might be a bit tiring since you can't include folders containing files as sources, it has to be a cpio or tarball, which you can't browse them in the UI or checkout with  `osc` as unpacked files.

So that I am not a fan of adding new strategies to include files within the image in KIWI to work around those OBS <-> KIWI integration limitations. I think KIWI is already fine to that regard, this is not an issue for the command line users and for OBS use case I can't see a solution that does not involve extra obs-services setup, if we assume the usage of obs-service we already have an strategy to fetch those files from a remote repository.

@dirkmueller does it all make sense? If so I'd just close the issue.

**Comment by dirkmueller** [comment]
@davidcassany Thanks for the very detailed reply, much appreciated. lets assume you have an extra file to "extract", e.g. the entrypoint.sh example above. you can extract it using the OBS source service into the package container but afaik there is no way to "reference" it in the kiwi xml build description. How would yo do that?

**Comment by davidcassany** [comment]
> @davidcassany Thanks for the very detailed reply, much appreciated. lets assume you have an extra file to "extract", e.g. the entrypoint.sh example above. you can extract it using the OBS source service into the package container but afaik there is no way to "reference" it in the kiwi xml build description. How would you do that?

Sorry for the late replay, I would do it by using the `<archive name="tarball_file_name">`. The tarball could be created using the source service of OBS. I agree that this forces you to use a tarball even if this is for single file (I don't see a problem with it) and that you still miss a way to configure the target destination. The OBS source service it is not possible to restructure the generated tarball and kiwi assumes the tarball is including the target destination, thus it just untars the tarball in /.  In case it lands to an undesired location you could still move it inside `config.sh` to a proper location. So this is all possible to be done.

I agree that this approach might be a bit convoluted, but note that KIWI itself it is pretty simple. The complexity comes once you aim to run KIWI within OBS and generate the source files by using OBS services, each of these three has its own limitations or constraints. IMHO in those cases the solution it getting the files as KIWI expects by adapting your sources (thus having the image description in some repo) or either by adapting the tooling you use to generate those OBS files from some source repository or similar (generator scripts/obs services, etc.).

For instance, for some container image repository we ended up not using OBS source serivce but including a Makefile in the repository that by running `make suse-package` it just creates all the files that need to be appended in the OBS package. This could be done manually or by some automation tool.

**Comment by schaefi** [comment]
I agree to what David suggested. There are imho enough alternatives to get files into the build

> So that I am not a fan of adding new strategies to include files within the image in KIWI 

Fully agree. Unless there is a high demand and the suggested alternatives are for a good reason not applicable I'm not open to add yet another method to add files.

@dirkmueller Please re-open if this somehow collides with your project requirements or we misunderstood the concern.

Thanks
