### ISSUE TITLE
Refactor BootLoaderConfigGrub2 to use grub2-mkconfig

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1194]
When building a .qcow2 image, the grub2.cfg provided by the OS is just fine and kiwi does not have to create its own based on a hardcoded template.

This means that settings are taken from /etc/default/grub, sysconfig and elsewhere as they should be and all packages and features (tuned, health-checker, etc.) work fine.

**Comment by schaefi** [comment]
You have several opportunities to use the distro provided grub.cfg:

1. write a simple script that copies the file over the one kiwi wrote. Use the ```<type ... editbootconfig="script"``` attribute in your XML description to make your script active

2. write a systemd oneshot unit that is called on firstboot and runs grub2-mkconfig to apply the hostonly setup on first boot. In this case you would boot first with the kiwi created grub setup. If this is not wanted use 1. or both in combination

We are not changing the grub template approach because I don't trust the distro provided config file. Too often they were just broken and every distro handles it differently.

**Comment by Vogtinator** [comment]
> You have several opportunities to use the distro provided grub.cfg:
>
> write a simple script that copies the file over the one kiwi wrote. Use the <type ... editbootconfig="script" attribute in your XML description to make your script active

That's definitely not simple. During `editbootconfig` and `editbootinstall` the target system is neither in a chrootable state nor are all OS files copied over yet. This means that running `grub2-mkconfig` is impossible without doing the rsync itself inside the script.

> write a systemd oneshot unit that is called on firstboot and runs grub2-mkconfig to apply the hostonly setup on first boot. In this case you would boot first with the kiwi created grub setup. If this is not wanted use 1. or both in combination

This would indeed not work for us.

> We are not changing the grub template approach because I don't trust the distro provided config file. Too often they were just broken and every distro handles it differently.

Right, and I don't trust the kiwi generated config file as it's often just broken and not every image is the same.

**Comment by Vogtinator** [comment]
What might work to support a hack is moving one of the editboot* hooks after rsync, or calling `fstab.script` chrooted after rsyncing and writing the config, so that it can call grub2-mkconfig itself.

Both would be hacks though.

**Comment by schaefi** [comment]
grub2-mkconfig creates a host specific grub config file. Calling it on the host that will not be the target system will not necessarily produce correct results. afaik it looks up the root mountpoint and checks filesystem capabilities which would be all targeted to the host but not to the image. Running it from the image chroot doesn't help much here. This was the reason for manually writing the file as part of the image builder. Unless grub2 has changed this and one could pass on all the information that it usually takes from the host, calling grub2-mkconfig seems wrong to me. Other than output file, version and help, there is not much we can give it

**Comment by Vogtinator** [comment]
AFAIK, YaST calls `grub2-mkconfig` in one way or another during installation as well and it appears to work fine for them in all possible scenarios.

I'll continue playing around with `editbootinstall`, it seems like contrary to what I wrote it's run after rsync \o/

**Comment by schaefi** [comment]
of course it does, yast runs on the target. In this case calling grub2-mkconfig is no problem :)

In the image world it's different. The image is build on some host which is not necessarily the later target machine. Calling tools that runs based on the assumption the system they see is the "real" system are hard to be used for imaging. This applies to grub2-install, dracut and some others. Fortunately most of them you can call with parameters to switch off their built in "intelligence". I couldn't come along a way to get this done with grub2-mkconfig. This is the reason why we did not use it so far in the process of building an image.

If you through your research find a way how we can use it that would be great. I was thinking on something like

```
grub2-mkconfig --root-id ... --kernel ... --initrd ... --options
```

Next there is the problem how to bring in the config options configured through the XML description. So far we support:

* kernelcmdline
* setup of graphics mode
* setup of boot timeout
* setup of boot theme
* setup of boot title
* setup of terminal mode

I think all those might be refactored using grub templates in ```/etc/grub.d/...```
After that there would still be the problem that some boot related settings are requested by users to apply only once, e.g the initial boot timeout.

When I decided for the custom grub template way I had done this research before. It is already some time ago so maybe the grub tooling has been improved.

I like the idea to use grub native tools whenever possible but in this case the tools where not capable to be used the way we needed it.

On special root setup like it is present on the live images grub2-mkconfig also fails because it cannot resolve the canonical path to the rootfs. If we take any action here and decide the template used in kiwi is not nice and it should be done by grub2-mkconfig then it should be possible to use it generally and I think that requires to disable some tool magic

If you look at e.g ```/etc/grub.d/30_os-prober``` I see code that evaluates variables like
GRUB_DISABLE_OS_PROBER. If we can come up with an environment that allows to provide the data kiwi knows and disable the magic it would be a good refactoring opportunity.

In any case it would be a big refactoring which I'm not afraid of but it must be worth doing it and provide a value for the majority of our users

> I'll continue playing around with editbootinstall

you can do that but it will not solve the problem that grub2-mkconfig probes values from a host that is not the target system

Just my2cents

**Comment by Vogtinator** [comment]
> of course it does, yast runs on the target. In this case calling grub2-mkconfig is no problem :)

Yes, but still chrooted and the UUID etc. is detected correctly.

> In the image world it's different. The image is build on some host which is not necessarily the later target machine. Calling tools that runs based on the assumption the system they see is the "real" system are hard to be used for imaging. This applies to grub2-install, dracut and some others. Fortunately most of them you can call with parameters to switch off their built in "intelligence". I couldn't come along a way to get this done with grub2-mkconfig. This is the reason why we did not use it so far in the process of building an image.
> 
> If you through your research find a way how we can use it that would be great. I was thinking on something like
> 
> ```
> grub2-mkconfig --root-id ... --kernel ... --initrd ... --options
> ```

All of those have to work anyway as regenerating the configuration from inside the running image has to work fine and be as close to a no-op as possible.

> Next there is the problem how to bring in the config options configured through the XML description. So far we support:
> 
> * kernelcmdline
> * setup of graphics mode
> * setup of boot timeout
> * setup of boot theme
> * setup of boot title
> * setup of terminal mode
> 
> I think all those might be refactored using grub templates in `/etc/grub.d/...`

Yes, or just set in `/etc/default/grub`. If none of those are set, the settings in there should not be overwritten and the distro defaults used. That's what users would expect.

> After that there would still be the problem that some boot related settings are requested by users to apply only once, e.g the initial boot timeout.
> 
> When I decided for the custom grub template way I had done this research before. It is already some time ago so maybe the grub tooling has been improved.
> 
> I like the idea to use grub native tools whenever possible but in this case the tools where not capable to be used the way we needed it.
> 
> On special root setup like it is present on the live images grub2-mkconfig also fails because it cannot resolve the canonical path to the rootfs. If we take any action here and decide the template used in kiwi is not nice and it should be done by grub2-mkconfig then it should be possible to use it generally and I think that requires to disable some tool magic

Yup, the live image setup is a bit more complex, but could be mostly worked around by adding some more options to `/etc/default/grub`

> If you look at e.g `/etc/grub.d/30_os-prober` I see code that evaluates variables like
> GRUB_DISABLE_OS_PROBER. If we can come up with an environment that allows to provide the data kiwi knows and disable the magic it would be a good refactoring opportunity.

That's also an option from `/etc/default/grub`.

> In any case it would be a big refactoring which I'm not afraid of but it must be worth doing it and provide a value for the majority of our users
> 
> > I'll continue playing around with editbootinstall
> 
> you can do that but it will not solve the problem that grub2-mkconfig probes values from a host that is not the target system

Turns out that works just fine:

```
#!/bin/bash
set -euxo pipefail

echo "Recreating the bootloader config"

# This is fragile, but better fail hard than silently
root="$(echo /tmp/kiwi_mount_manager.*/usr)"
root=${root%/usr}

mount -osubvol=@/.snapshots /dev/mapper/loop0p3 "${root}/.snapshots"

chroot "${root}" grub2-mkconfig -o /boot/grub2/grub.cfg

umount "${root}/.snapshots"
```

Results in a fully working image. There are two parameters for `root=` though, one wrong and one correct.

**Comment by Vogtinator** [comment]
And I just fixed the wrong first `root=` parameter:

```
# Make sure the link exists
ln -s /dev/mapper/loop0p3 "/dev/disk/by-uuid/$(chroot "${root}" grub2-probe / --target=fs_uuid)"
```

**Comment by schaefi** [comment]
Inspired by your testing I hacked a bit in the kiwi code on a POC to use grub2-mkconfig. A short smoke test looks not too bad. The branch is named: ```poc_refactor_grub2_config_setup```

I won't have much time to work on this one but David and me will take it into account for one of the next sprints. It seems you have a workaround solution at hand so we are not under time pressure afaik

**Comment by Vogtinator** [comment]
> Inspired by your testing I hacked a bit in the kiwi code on a POC to use grub2-mkconfig. A short smoke test looks not too bad. The branch is named: poc_refactor_grub2_config_setup

Yay!

> I won't have much time to work on this one but David and me will take it into account for one of the next sprints.

Sounds great, thanks!

> It seems you have a workaround solution at hand so we are not under time pressure afaik

Yup, that should suffice for a couple of weeks.
