### ISSUE TITLE
Add support for alpine linux / apk package manager

### ISSUE THREAD

**Issue by Finkregh** [OSInside/kiwi#1206]
## Problem description
Support for alpine linux would be great

**Comment by davidcassany** [comment]
I am curious about your use case or motivation for that. Are you willing to build alpine containers with KIWI? Or are you targeting some other OS or system?

Currently, adding further package managers support is not in our priorities. I am also working for Pacman support in my spare time and it is hard to find the spot to work it, so there is no ETA.

I have no apk experience at all. From a package manager we basically require:

* Set custom configuration without interfering the host (custom location for config, repos definition, etc.)
* Bootstrap a system to a specific location

I guess apk is capable of doing so, but I have no experience.

We are also opened to contributions, in case you consider getting your hands on code, this would be welcome. I don't see the time frame for us to work on that at mid term.

**Comment by davidcassany** [comment]
We are closing it for now, as Alpine support is quite a huge effort in many areas and up to now there is no specific use case or pressing need for it. Also, there is no Alpine within the Open Build Service (the tool we rely to operate and distribute binary packages from sources), which would make it hard for us to maintain that part.

Apline is different to most major distros in many aspects, since KIWI aims to be cross distro adding a support for Alpine is likely to require quite some additional code and probably several refactors. Just to mention an example, Alpine does not use systemd, because of that, stuff like creating the initrd is quite a completely different story, as KIWI embraces systemd and dracut for that purpose.

Said that contributions are welcome, so you are invited to investigate regarding Alpine and eventually contribute, it's not an easy task though.
