### ISSUE TITLE
Excessive memory usage in a config.xml

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1213]
## Problem description

I've tried unifying a SLED and SLES vagrant box description by "abusing" profiles a bit and managed to make kiwi allocate memory uncontrollably.

## Expected behavior

Kiwi should not OOM my system.

## Steps to reproduce the behavior

Grab [this](https://susepaste.org/33041232) kiwi description. Put it into a SLE 12 SP3 image build project, e.g. https://build.suse.de/project/show/home:dancermak:SLE-12-SP3 (SUSE internal unfortunately). You can create a `_multibuild` with the following contents:
``` xml
<multibuild>
    <flavor>libvirt_sles</flavor>
    <flavor>libvirt_sled</flavor>
    <flavor>libvirt_aarch64_sles</flavor>
    <flavor>virtualbox_sles</flavor>
    <flavor>virtualbox_sled</flavor>
</multibuild>
```
and do a `touch config.sh && touch aarch64_vagrantfile`.

Now run `osc build -M libvirt_sles`. **Caution, this will OOM your machine! Run this inside a osc KVM!**

The build will start and kiwi will endlessly loop with:
``` ShellSession
[  104s] runtime error: file /usr/share/kiwi/xsl/convert57to58.xsl line 24 element copy-of
[  104s] error : out of memory error
```

## OS and Software information
+ KIWI version: 9.18.16
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.suse.de

**Comment by schaefi** [comment]
Oh this looks like a xslt recursion problem. But I don't see why. The reported line basically the recursion exit criteria which just passes along the xml context.

I'm not sure if this can be fixed in kiwi. Can you try to limit your test to the xslt processing. You can write a simple python code like this (see kiwi/xml_description.py)

```
xslt_transform = etree.XSLT(
    etree.parse(Defaults.get_xsl_stylesheet_file())
)
```

This should be a reproducer to the endless use of memory. If we have an example we can go an open a bug on the xslt side. If we can fix this in kiwi I'm happy to do it.

So far I have no solution though

**Comment by schaefi** [comment]
You can also test if running ```xsltproc``` on the commandline have the same effect

**Comment by dcermak** [comment]
After committing the changes on obs, it now no longer OOMs, also the things @schaefi posted all worked flawlessly.
