### ISSUE TITLE
kiwi-ng command not available after pip install kiwi

### ISSUE THREAD

**Issue by probonopd** [OSInside/kiwi#1226]
## Problem description

The `kiwi-ng` command is not available after `pip install kiwi`.

As per the instructions, I got the impression that it should work:

![kiwi](https://user-images.githubusercontent.com/2480569/66253230-6a684c00-e754-11e9-8c8d-c915c587caee.png)

## Expected behaviour

The `kiwi-ng` command is available after `pip install kiwi`.

## Steps to reproduce the behaviour

```
root@0e4606e7890b:~# pip install kiwi
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: kiwi in /usr/local/lib/python2.7/dist-packages (9.18.18)
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from kiwi) (4.2.6)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from kiwi) (2.21.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (from kiwi) (3.13)
Requirement already satisfied: pyxattr in /usr/local/lib/python2.7/dist-packages (from kiwi) (0.6.1)
Requirement already satisfied: docopt>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from kiwi) (0.6.2)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->kiwi) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->kiwi) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->kiwi) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->kiwi) (2.8)

root@0e4606e7890b:~# which kiwi-ng
root@0e4606e7890b:~# 

root@0e4606e7890b:~# find /usr/local/ | grep kiwi-ng$
root@0e4606e7890b:~# 
```

## OS and Software information
+ KIWI version:  9.18.18
+ Operating system: Ubuntu 18.04.3 LTS
+ OBS version: n/a

**Comment by davidcassany** [comment]
A couple of comments regarding that:

1. Note that since kiwi v9.18.0 there is no support for python2. So you should not install any kiwi >= 9.18.0 under a python2 environment. You mostly sure gonna face runtime issues due to python2 and python3 differences or incompatibilities. Gonna check if there is something to be done form our side to prevent pip to install kiwi in python2 environments.

2. Usually kiwi-ng is installed using the RPM, mostly because the `kiwi` and `kiwi-ng` are managed throught the update-alternatives that points to the `kiwi-ng-3` or `kiwi-ng-2` depending on the underlying python version or also depending on if the very old former kiwi written in Perl is installed on the system. At the time of writing KIWI-NG having dual python environments (py2 and py3) was a requirement, and it was also a requirement to allow both kiwi versions to coexist former kiwi coded in Perl and next generation coded in Python. All that to explain that what pip does is to provide the `kiwi-ng-2` or `kiwi-ng-3` depending on the python version, as the other tools names we expected them be managed by update-alternatives when kiwi is installed using a package manager.

Since we already removed python2 support upstream since last June I'd say that building only the `kiwi-ng` instead of `kiwi-ng-3` is something that we could consider. @schaefi do you have any thoughts regarding that?
