### ISSUE TITLE
[Rescue LiveCD] No memtest option on boot items list

### ISSUE THREAD

**Issue by MikhailKasimov** [OSInside/kiwi#1286]
Hello! Resounding openSUSE's bug-report: https://bugzilla.suse.com/show_bug.cgi?id=112371 due to this comment: https://bugzilla.suse.com/show_bug.cgi?id=1123713#c2 :

```
The rescue CD does not behave like an installed system, especially not the available boot options. Those are managed by KIWI, so please file a feature request on https://github.com/OSInside/kiwi/issues
```

https://bugzilla.suse.com/show_bug.cgi?id=112371 info:

```
Hello!

Despite on memtest86+ is installed by default (see memtest_is_installed.jpg), but there is no Memorycheck option in boot items list (see no_memtest_option.jpg).

Rescue LiveCD was downloaded from [0] https://download.opensuse.org/distribution/leap/15.0/live/openSUSE-Leap-15.0-Rescue-CD-x86_64-Current.iso

At the same time locally installed Leap 15.0 has Memtest86+ option when memtest86+ is installed.

Please, re-check it.

Thanks!
```

**Comment by davidcassany** [comment]
IIRC we decided to remove (or do not include) memtest support in KIWI-NG mostly because memtest is kind of a dead project. See that now the memtest project is mostly living in a proprietary solution and the opensource code is just left there without maintenance updates since 2013 and with very little movement prior to that. See https://www.memtest.org/. Also this is only available for x86 archs.

Moreover there is no memtest in SLE12 nor SLE15.

**Comment by schaefi** [comment]
Thanks David for your observations in this area. I agree we don't want to put on a proprietary solution

**Comment by ktry** [comment]
Memtest86+ is still under development and version 6.01 supports UEFI. I've had good results deploying via iPXE.

https://www.memtest.org/
https://github.com/memtest86plus/memtest86plus

I'm building a UEFI rescue ISO with ZFS support and I'd like to add memtest86+ 6.01 to it. I've used kiwi 7.04 for years and I'm just started to investigate kiwi-ng to do this. I'm hoping to figure out how to wire in memtest to the iso hybrid live image. Thanks for keeping this project going. It's an awesome tool!
