### ISSUE TITLE
Add --ignore-obs-repos option

### ISSUE THREAD

**Issue by nadvornik** [OSInside/kiwi#1307]
## Problem description

Kiwi images built in OBS use 
```
<repository type="rpm-md" >
        <source path='obsrepositories:/'/>
</repository>
```
This makes the image hard to rebuild outside of OBS without modifying sources.
With --ignore-repos or --ignore-repos-used-for-build  it can be rebuild, but it would be useful to have more specific option just for OBS repos that preserve other repo types.

See also https://github.com/SUSE/spacewalk/issues/10360

**Comment by davidcassany** [comment]
I don't think I understand the motivation of this request or its use case. More specific I don't see how you'd like to define the repositories in a way that works in OBS and works without OBS.

Are you imagining something like?

```xml
<repository type="rpm-md" >
        <source path='obsrepositories:/'/>
</repository>
<repository type="rpm-md" alias="MyRepository">
        <source path="https://myrepository_url"/>
</repository>
```

So in OBS builds only `obsrepositories` has effect but outside OBS only `MyRepository` is being used depending on the flag `--ignore-obs-repos`? Honeslty, I find it quite confusing and I am not sure how the OBS parser would react to something like that.

If the problem is not having to edit the source files you can always make use the `--ignore-repos` options, as you already noted, and then provide the desired repositories on the command line at runtime. In fact this is what OBS is actually doing when `obsrepositories:/` is in use.

**Comment by schaefi** [comment]
If you want to distinguish different repo setup you can use profiled sections:

```
<profiles>
    <profile name="OBS" description="Build in obs" />
    <profile name="Standalone" description="Build standalone"/>
</profiles>

<repository type="rpm-md"  profiles="OBS>
    <source path='obsrepositories:/'/>
</repository>
<repository type="rpm-md"  profiles="Standalone>
    <source path=.../>
</repository>
```

In obs you need a _multibuild file that selects the OBS profile to build

We are not adding an ignore option for obsrepositories because that doesn't help. You need at least one repository section and that can be setup in various ways. You can also use the commandline with ```--ignore-repos --add-repo ...``` or ```--set-repo ...``` The later will overwrite the first repo defintion in the XML

So there are plenty of opportunities to get what you need.

Let us know if none of those will work for your use case.

Thanks

**Comment by nadvornik** [comment]
Now SUSEManager calls Kiwi with ``--ignore-repos --add-repo ...`` as you suggested above. This works fine for the typical case, where all the repos are provided by SUSEManager.

In https://github.com/SUSE/spacewalk/issues/10360 there was pointed out a scenario that does not work:

1. user installs ``kiwi-templates-SLES15-JeOS`` from ``SLE-Module-DevTools15-SP1``
2. user modifies the config.xml and replaces ``obsrepositories`` with some custom repo (not controlled by SUSEManager) and use packages from it
3. building with SUSEManager which uses  ``--ignore-repos`` ignores the custom repo and fails

I can see these options to fix it:

1. let user configure if SUSEManager should use ``--ignore-repos`` or not
2. let SUSEManager detect if ``--ignore-repos`` is needed or not - this means parsing config.xml
3. implement ``--ignore-obs-repos`` in Kiwi and use it unconditionally in SUSEManager

3 is IMHO the most clean fix.
