### ISSUE TITLE
Vagrant boxes request the microphone with the Virtualbox provider

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1322]
## Problem description

I was made aware in [boo#1157615](https://bugzilla.opensuse.org/show_bug.cgi?id=1157615) that the virtualbox vagrant boxes request the microphone which confuses users.

This does not occur with other vagrant boxes (that are usually built by packer), for instance the [Ubuntu 18.04 Bento box](https://app.vagrantup.com/bento/boxes/ubuntu-18.04). You can find the extracted Virtualbox ovf description [here](https://trello-attachments.s3.amazonaws.com/5d51288d62546874d4dbb916/5dce944cc886898f943f1b39/29bd4d0d9a7012c808197c79fe29791a/bento_box.ovf). According to the information that I've found online, turning of the microphone is tuned by this line:
``` xml
<AudioAdapter driver="ALSA" enabled="true" enabledIn="false" enabledOut="false"/>
```

This line is part of the `<vbox:Machine>` element, which we have completely omitted from the template in [kiwi/storage/subformat/template/virtualbox_ovf.py](https://github.com/osinside/kiwi/blob/master/kiwi/storage/subformat/template/virtualbox_ovf.py). However that element contains a lot of machine specific settings like the RAM size, CPU count, etc. so I am not sure if we should set these. On the other hand: basically every packer built box has such a section and for these it **is** possible to retroactively change the CPU count and so on.

Anyone has any experience with this? Opinions how we should fix this?

## OS and Software information
+ KIWI version: latest release
+ Operating system: any
+ OBS version: build.opensuse.org

**Comment by schaefi** [comment]
@dcermak Hi, we have discussed this issue in the sprint planning meeting and had more questions than answers :) So our scope from a kiwi + vagrant perspective is to provide generic box files that usually will be used for automation. Thus we assume customers use vagrant boxes built with kiwi to get a shell and/or ssh access but no desktop related features like audio, graphics, etc...

From this perspective we are open to change the template in a way that it does not expose this virtual hardware, e.g a ```<vbox:Machine>``` section that disables audio completely.

But we don't know if this would be the expected behavior and I also don't know how this needs
to be specified in kiwi/storage/subformat/template/virtualbox_ovf.py. So this needs clarification.

Other than that if we specify a ```<vbox:Machine>``` section where we have none right now, will this require a set of mandatory settings or not ?

The one thing we don't want is a customization option in the kiwi XML to configure the VM. I had this before for the VMware settings file and I consider this as broken by design because any change will not be known and you will never be complete and cover only a portion of it. Also this is not the scope of the builder imho

Feedback welcome.

Thanks

**Comment by dcermak** [comment]
> @dcermak Hi, we have discussed this issue in the sprint planning meeting and had more questions than answers :) So our scope from a kiwi + vagrant perspective is to provide generic box files that usually will be used for automation. Thus we assume customers use vagrant boxes built with kiwi to get a shell and/or ssh access but no desktop related features like audio, graphics, etc...
> 

Agreed, that is the general use case.

> From this perspective we are open to change the template in a way that it does not expose this virtual hardware, e.g a `<vbox:Machine>` section that disables audio completely.
> 
> But we don't know if this would be the expected behavior and I also don't know how this needs
> to be specified in kiwi/storage/subformat/template/virtualbox_ovf.py. So this needs clarification.

It needs to be added into that template.

> 
> Other than that if we specify a `<vbox:Machine>` section where we have none right now, will this require a set of mandatory settings or not ?

It requires some predefined defaults, but actually these shouldn't be really important, as one of the big features of vagrant is that it adjusts the VM to your needs in an abstract way without you having to do that. So in theory most of the settings shouldn't matter, as vagrant will overwrite them anyway.

> 
> The one thing we don't want is a customization option in the kiwi XML to configure the VM. I had this before for the VMware settings file and I consider this as broken by design because any change will not be known and you will never be complete and cover only a portion of it. Also this is not the scope of the builder imho

Yes, let's not go down that path.

**Comment by schaefi** [comment]
Ok we try to add a line that disables audio completely
