### ISSUE TITLE
docker build resets /etc/fstab

### ISSUE THREAD

**Issue by lnussel** [OSInside/kiwi#1329]
## Problem description

For WSL images we currently need to use docker as image type in kiwi short of a better way. Unfortunately the docker build resets /etc/fstab to zero. That means we can't provide any defaults.

## Expected behaviour

either leave /etc/fstab alone if it exists or implement the documented way of fstab.append etc.

## OS and Software information
+ KIWI version: python3-kiwi-9.19.10-1.1
+ Operating system: TW
+ OBS version: build.opensuse.org

**Comment by davidcassany** [comment]
First, whatever we change for docker builds has to be an improvement for docker images/builds, unrelated to WSL. We are about to code a new WSL builder for KIWI, thus all WSL specifics belong there.

Docker containers are meant to be single process, meaning that anything else than the entry-point is executed. The entry point is a user provided value which can be defined as a default, but also provided at run-time. So that I see no point on addressing any sort of fstab manipulation on docker images as part of KIWI. In fact I am surprised we have this code to wipe fstab content, I am pretty sure this is some sort of legacy from old times, before supporting OCI and probably to support LXC (which is an attempt of a containerized full system).

I did a quick check and fedora images do not have any `fstab` file and alpine images include a none sense `fstab` file with entries for `/dev/usbdisk` and `/dev/cdrom` :man_shrugging: Probably it is just there as a leftover of their build procedure.

So I am not entirely sure how should we proceed here.

I'd be in favor of removing any sort of `fstab` handling for OCI images, which I guess would result with no `/etc/fstab` at all and would also allow to the user to append the file as part of the root overlay. Gonna do some smoke test about it.

I believe this might have only impact to containers running some sort of `/sbin/init` process, like trying to run systemd on a container. Would systemd fail without an `/etc/fstab`? In any case I would consider that a really corner case that the user has to solve by providing it's own `fstab`.

Any thoughts?

**Comment by lnussel** [comment]
Both the use of docker and the need for fstab are short term hacks for WSL. Neverthless the only way at this point in time.
Whether or not fstab is present doesn't break anything.
I also don't see why kiwi would care so long as the kiwi profile doesn't define anything related to fstab. So the least surprising behavior is to just not touch fstab.

**Comment by davidcassany** [comment]
> I also don't see why kiwi would care so long as the kiwi profile doesn't define anything related to fstab. So the least surprising behavior is to just not touch fstab.

Correct, totally agree, going to review this container logic and make sure we are not performing unneeded and unexpected stuff.
