### ISSUE TITLE
Update code base in SLE12 and SLE15

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1360]
## Problem description

In order to make the changes effective on SLES an update of the code base is required

## Expected behaviour

* Latest kiwi available in SLE12-SP5
* Latest kiwi available in SLE15-SP2

**Comment by davidcassany** [comment]
The bugfix driving this could be bsc#1165578

**Comment by schaefi** [comment]
@davidcassany I'm starting the code base update for SLE12-SP5, would be great if you can do SLE15

**Comment by schaefi** [comment]
We target 9.20.5 and follow your suggestion that any individual commit does not change the version information to make @aplanas happy

**Comment by schaefi** [comment]
QA:Maintenance:Test:12-SP5:python-kiwi/python-kiwi

has been updated with the latest code changes. I'll check if all integration test builds prior submission to the SUSE namespace

**Comment by schaefi** [comment]
Watching:

* https://build.suse.de/project/show/QA:Maintenance:Images:12-SP5:kiwi-ng-testing

**Comment by davidcassany** [comment]
I have updated SLE15 packages here:

* https://build.suse.de/project/show/QA:Maintenance:Test:15:python-kiwi
* https://build.suse.de/project/show/QA:Maintenance:Test:15-SP1:python-kiwi

So far all tests are green:
* https://build.suse.de/project/show/QA:Maintenance:Images:15:kiwi-ng-testing
* https://build.suse.de/project/show/QA:Maintenance:Images:15-SP1:kiwi-ng-testing

**Comment by davidcassany** [comment]
@schaefi I also noted we should manually add a reference to the this ticket [bsc#1165578](https://bugzilla.opensuse.org/show_bug.cgi?id=1165578). There are no traces of it in changelog because it was fixed upstream way before being reported on SLE15.

Sorry I just realized now about that while reviewing the bugfixes introduced on the release.

**Comment by schaefi** [comment]
I have updated SLE12-SP5

* created request id 215067
  maintenance_incident: home:sax2:branches:SUSE:SLE-12-SP5:Update/python-kiwi@f50895b7dbb86cabe539d302d645289c -> SUSE:Maintenance (release in SUSE:SLE-12-SP5:Update)

**Comment by schaefi** [comment]
@aosthof I put you onto this card just in case there will be problems with our submissions. Thanks

**Comment by davidcassany** [comment]
Maintenance requests to update SLE15 are out:

* [MR#215080](https://build.suse.de/request/show/215080) for SLE15-SP1
* [MR#215079](https://build.suse.de/request/show/215079) for SLE15

**Comment by aosthof** [comment]
@schaefi @davidcassany 

- https://smelt.suse.de/request/215067/ (SLES 12 SP5, to be reviewed/accepted) 
- https://smelt.suse.de/request/215079/ (SLES 15, accepted) -> https://smelt.suse.de/incident/14596/ (stopped, Reason: 2020-03-31:deneb_alpha:Not enough for LTSS)
- https://smelt.suse.de/request/215080/ (SLES 15, accepted) -> https://smelt.suse.de/incident/14595/ (active)

Note that the update for SLES 15 GA is currently stopped because SLES 15 GA is meanwhile in LTSS. Before I start a discussion to proceed with the update for 15 GA I like to understand if this is really needed/intended, especially as the description of this issue here says:

Expected behaviour:

- Latest kiwi available in SLE12-SP5
- Latest kiwi available in SLE15-SP2

**Comment by schaefi** [comment]
> Before I start a discussion to proceed with the update for 15 GA I like to understand if this is really needed/intended

Actually I'm fine if this lands in SLE15-SP1 and SP2. If a GA update causes too many problems I'm happy to not update it there.

**Comment by davidcassany** [comment]
@aosthof Thanks for having a look at submissions. 

I am also fine to not upgrade KIWI on SLE-15.

The main reason to do it is to avoid glitches for cross SPx builds (e.g. building SLE-15-SP2 image from a SLE-15 host). So the less KIWI versions available the less chances to be hit by unexpected incompatibilities caused by crossing SPs, that's why I wanted to update both to the same version as they currently were. The gap between them is not that huge, thus I am not much concerned about having this divergence. I was not aware that SLE15 is under LTSS, then it makes sense to me to leave it untouched.

**Comment by aosthof** [comment]
@schaefi @davidcassany OK, sounds good to me. Then I'll coordinate that with Maintenance:

- https://smelt.suse.de/request/215067/ stays for SLES 12 SP5, needs to be reviewed/accepted
- https://smelt.suse.de/incident/14596/ for SLES 15 GA can be revoked/deleted
- https://smelt.suse.de/incident/14595/ for SLES 15 SP1 stays active and will eventually be inherited by SLES 15 SP2 when the maintenance update is available.

**Comment by schaefi** [comment]
This is done now, thanks to everybody
