### ISSUE TITLE
Exception while setting du_call in system/size.py

### ISSUE THREAD

**Issue by dwmccheyne** [OSInside/kiwi#1363]
## Problem description
Permission Denied messages in output while setting du_call in size.py error the build

```
[ INFO    ]: 02:29:59 | Precalculating required disk size
[ INFO    ]: 02:30:01 | Cleaning up BootImageDracut instance
[ ERROR   ]: 02:30:01 | KiwiCommandError: du: stderr: du: cannot access '/builds/user/project-kiwi/kiwi/img/build/image-root/proc/8606/task/8606/fd/4': No such file or directory
du: cannot access '/builds/user/project-kiwi/kiwi/img/build/image-root/proc/8606/task/8606/fdinfo/4': No such file or directory
du: cannot access '/builds/user/project-kiwi/kiwi/img/build/image-root/proc/8606/fd/3': No such file or directory
du: cannot access '/builds/user/project-kiwi/kiwi/img/build/image-root/proc/8606/fdinfo/3': No such file or directory
, stdout: 140740459628253	/builds/user/project-kiwi/kiwi/img/build/image-root

[ INFO    ]: 02:30:01 | Cleaning up BootImageDracut instance
section_end:1583375403:build_script
```

## Expected behaviour
du command runs, returns processed du -s type output and continues

## Steps to reproduce the behaviour
Run the attached repr description with like: `sudo kiwi-ng --type vmx system build --description ../project --target-dir ./img`
I am building kiwi  using gitlab ci in this instance, log including build and install of kiwi from source included in zip. Attached a reproducing description which is largely based on the kiwi-descriptions' xenial description.
## OS and Software information
+ KIWI version: v9.20.2-4 (logs from .2, same result with .4)
+ Operating system: Fedora 31
+ du version: du (GNU coreutils) 8.31
+ OBS version: N/A

[kiwi-ng_output.txt](https://github.com/OSInside/kiwi/files/4290662/kiwi-ng_output.txt)
[repr.zip](https://github.com/OSInside/kiwi/files/4290637/repr.zip)

**Comment by schaefi** [comment]
I tried to reproduce this but failed. To be honest it looks more like a problem of the host building the image. Could you provide some more details what process:

    /proc/8606/task/8606/fdinfo/4

relates to ? We have seen issues like that if the host:

- is btrfs based
- is xfs based (but only occasionally) usually xfs works just fine as build host
- there is a LVM volume manager active
- some process e.g apache holds cgroups on certain files

So I'm fishing in dark water so far, sorry

**Comment by DattoDaveOps** [comment]
I'll see about getting some detail about the files du can't read. They change between runs, but are always in proc. 
I suspect you're fishing in the right hole at least and appreciate the notes, the original description runs in an open environment where the constructed 'du' command doesn't output any of the file errors in the log there so I'll recheck my reproducer too.
My initial thought was that this was one of those cases where a file is removed by something else between when du reads the list of names from an encountered directory, and when it gets to processing the Nth item in that list. 
It looks like the code does some filtering, and accepts an exclude[] to this function. But, I'm not sure how that could be populated or what other issues that might propogate?

**Comment by DattoDaveOps** [comment]
Here's what I found:
It's always some /proc file. But they don't exist there, they've already been reported as missing earlier in the log.
>[ WARNING ]: 23:38:25 | Image root directory /builds/project-kiwi/kiwi/img/build/image-root not cleanly umounted: umount: stderr: umount: /builds/project-kiwi/kiwi/img/build/image-root/proc: umount failed: No such file or directory.

Following a lot of threads around the internet with explanations about du like this, 

> proc is a pseudo filesystem; it's a part of your RAM and contains information for every existing process. So, if a process does not exist anymore when du tries to count it, or if a process has closed a file descriptor (subdirectory fd or fdinfo) in the meantime, you get this message. You must keep in mind, that du will at first build a list of files and directories to count and later will count their sizes. Meanwhile there will be a lot of changes on your system - processes are finished, file descriptors are closed and so on.  
You should use the -x option of the du command to prevent it from searching mounted filesystems while examining the root partition.

I built and ran with that replacement in kiwi/system/size.py:accumulate_mbyte_file_sizes and it was able to successfully calculate a disk size to use and build the disk

> [ INFO    ]: 00:04:47 | Creating .profile environment
3316 [ INFO    ]: 00:04:48 | Precalculating required disk size
3317 [ INFO    ]: 00:04:52 | --> system data with filesystem overhead needs 3375 MB
3318 [ INFO    ]: 00:04:52 | --> legacy bios boot partition adding 2 MB
3319 [ INFO    ]: 00:04:52 | --> EFI partition adding 20 MB
3320 [ INFO    ]: 00:04:52 | Using calculated disk size: 3397 MB
3321 [ INFO    ]: 00:04:52 | Creating raw disk image /builds/project-kiwi/kiwi/img/LimeJeOS-Ubuntu-Xenial.x86_64-16.0.4.raw

I'm not sure what other fallout this might have, but it seems safe to me since it wouldn't be missing counting anything that's actually there as far I can tell.

**Comment by davidcassany** [comment]
This is interesting information, thanks much for digging into this. I am not sure if using `-x` might have impact on specific circumstances, this change is quite sensitive. In any case this is interesting information.

Also I am curious about the umount warning you have prior calling `du`, it looks like some procedure umount `/proc`. Would it be possible for you to share the complete build logs that include the failure?


I am also wondering if you might have some umount leftovers somewhere, after the failure the command:

`grep -r /builds/project-kiwi/kiwi/img/build/image-root /proc/*/mounts` 

should not return anything, otherwise the chroot env was not properly unmounted, I such cases I have seen strange failures.

**Comment by DattoDaveOps** [comment]
[with-x-buildlog.log](https://github.com/OSInside/kiwi/files/4330945/with-x-buildlog.log)
Attached a slightly anonymized build log.
There is a failure later in the process, but the du calculates the disk size. Happy to get any other related info that's useful here. Thanks!

**Comment by Conan-Kudo** [comment]
With some further digging, I think the actual problem is that we don't set up exclusions for `/proc`, `/sys`, and `/dev` for size calculations. We should not be attempting to compute things there regardless, and it causes weird issues inside of containers when trying to build images.

**Comment by schaefi** [comment]
Thanks for all the feedback. I came up with a first suggestion for a fix. However I'm relatively convinced the patch is just dealing with a situation that should not exist.

When kiwi runs the size calculation all external mount processes into the new rootfs should have been umounted by kiwi itself. My guess is that some of those umount operations failed and in the end that makes du working on e.g /proc with the reported effects. As I was not able to reproduce this it would still be valuable to find the reason for this behavior. Maybe you can check on custom scripts or container events triggered by mount actions from kiwi that causes some kind of external busy state not caused by kiwi code... just guessing though.

In any case I agree with @Conan-Kudo that we should not work on filesystems that has no phsyical block device associated. My patch goes into that direction

I believe the suggested "-x" option to be passed to du is something we should not do because that checks if a filesystem boundary was passed and this is the case when you build images through loop devices as well as into other filesystems compared to the building host. Therefore I agree to @davidcassany that this might have a bad impact on the size calculation to be still accurate

Your help on the testing front is much appreciated. Let me know if the open PR works for you

Thanks much

**Comment by Conan-Kudo** [comment]
We also definitely don't want to use `-x` because it will have weird effects when building Btrfs based images with multiple subvolumes.

**Comment by DattoDaveOps** [comment]
[546fe7c3db009c3ef486a587e4991a8120226d0c_build.log](https://github.com/OSInside/kiwi/files/4333309/546fe7c3db009c3ef486a587e4991a8120226d0c_build.log)
The rebuild eliminated the initial set of warnings where du tries to reference removed files.
There are still the warnings about the umounts where those items aren't present.
The calculated size for system data is about 300mb larger than running with the -x option in the same description, so that would seem to validate that -x isn't a great option. :) 
It does still fail shortly after with `KiwiCommandError: kpartx: stderr: /proc/devices: fopen failed: No such file or directory`

**Comment by schaefi** [comment]
Do you have a more complete log file for me ? Thanks

**Comment by davidcassany** [comment]
> Thanks for all the feedback. I came up with a first suggestion for a fix. However I'm relatively convinced the patch is just dealing with a situation that should not exist.

I fully agree, that's why I'd like also to understand what is going here regardless we decide to remove some kernel specific paths for `du` calls and size calculation. @schaefi just for reference, but the issue reported on this bug (bsc#1158000) might be related. This was reported for kiwi v7, thus a workaround was provided without investing too much time on why some umounts were silently not working as expected and leaving leftovers behind. Also mounting and umounting kiwi logs for v7 are not easy to follow. The reproducer was hard to achieve for that one. In that one **BaseCleanMount** method did the trick (even the same paths were umounted on later stages right after `config.sh`).
