### ISSUE TITLE
add support for discoverable partitions

### ISSUE THREAD

**Issue by lnussel** [OSInside/kiwi#1385]
Systemd has put up a number of standard UUIDs for GPT partitions:
https://systemd.io/DISCOVERABLE_PARTITIONS/

Quoting the link:

*   OS installers can automatically discover and make sense of partitions of existing Linux installations.
*    The OS can discover and mount the necessary file systems with a non-existing or incomplete /etc/fstab file and without the root= kernel command line option.
*   Container managers (such as nspawn and libvirt-lxc) can decode and set up file systems contained in GPT disk images automatically and mount them to the right places, thus allowing booting the same, identical images on bare-metal and in Linux containers. This enables true, natural portability of disk images between physical machines and Linux containers.
 *  As a help to administrators and users partition manager tools can show more descriptive information about partitions tables.

Would make sense to support that from kiwi I guess.

**Comment by davidcassany** [comment]
This is interesting stuff, if the implementation is simple and in the scope of adding just some sort of new labeling criteria that can be cleanly implemented I'd say it makes sense supporting it (I imagine a new choice for `devicepersistency` attribute, e.g. `devicepercistency="discoverable"`).

Otherwise, if relevant changes are required on KIWI side, I'd say we need some little more time to see how those features settle down, I'm just afraid of keep doing changes on KIWI because of containers technologies hype and its very fast evolution. Even this is not strictly tight containers but somehow promoted by it.

**Comment by schaefi** [comment]
We have been discussing this on the planning meeting and there are some concerns.

1. kiwi uses PARTUUID for its own purpose to detect the image original partition and a modified(resized). This would only allow us to set the uuid specification at resize of an oem image but not as part of the image

2. the systemd specification is done for GPT only but PARTUUID also exists on e.g msdos table. The restriction of the specification to GPT impacts also other archs like s390

3. the systemd specification is implemented in systemd 211 and newer and requires the Boot Loader spec to be respected/implemented by the OS.

4. the feature of auto discovery doesn't play a big role for images in my eyes. As the OS is produced by an image builder all partitions are known and labeled. Thus kiwi already has a specification of partitions which would allow mounting by label

5. I find it weird that the systemd specification uses different id for root and other partitions depending on the architecture.

Overall we see some potential for issues and are currently not implementing the spec in the builder. We can discuss to extend the Disk interface in kiwi to allow specifying a uuid such that this information can be optionally passed in the XML description. Is that something you would agree to ?

Here are my thoughts on the listed advantages:

>OS installers can automatically discover and make sense of partitions of existing Linux Installations.

In the area of an image builder, why should this be needed ? As I said the image builder knows everything about partitions and their classification

>The OS can discover and mount the necessary file systems with a non-existing or incomplete /etc/fstab file and without the root= kernel command line option.

In the area of an image builder there is no doubt about root. The concept to classify the rootfs by a label of the partition is also questionable because the PARTUUID label is not the filesystem label. A mount by label is more of a classification. Also a system with an incomplete fstab is considered broken unless the idea is to delete fstab from Linux at all

> Container managers (such as nspawn and libvirt-lxc) can decode and set up file systems contained in GPT disk images automatically and mount them to the right places, thus allowing chooting the same, identical images on bare-metal and in Linux containers. This enables true, natural portability of disk images between physical machines and Linux containers.

A container is typically an archive file not containing any partition table. I didn't get that part

> As a help to administrators and users partition manager tools can show more descriptive information about partitions tables.

In the area of an image builder and with respect to kiwi an admin knows about the partition classification by either the LABEL or the name tag in GPT. See the flag_map displayed by tools like gdisk. 

```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048            6143   2.0 MiB     EF02  p.legacy
   2            6144           47103   20.0 MiB    EF00  p.UEFI
   3           47104         2633694   1.2 GiB     8300  p.lxroot
```

So with kiwi we already have this type of classification

Thanks

**Comment by davidcassany** [comment]
After having had a closer look to it and in addition to what @schaefi already said I add few other concerns I see on trying to support such a feature.

The table of the predefined UUID is extensive and as far as I understand not provided by any tool. Meaning that either we code it in KIWI or we let user specify the UUIDs somehow. Adding the predefined UUIDSs hardcoded in KIWI is bad idea as we would have no way to validate or anticipate changes on it that could happen upstream, thus I would definitely discard that option. On the other side, letting users configure it turns to be quite hard in terms of UI as there are many different simultaneous UUIDS to set (root, home, swap, etc.), so adding them into the XML might not be that obvious, however setting root partition only should be sufficient in most cases (probably this is a reasonable option).

> kiwi uses PARTUUID for its own purpose to detect the image original partition and a modified(resized). This would only allow us to set the uuid specification at resize of an oem image but not as part of the image

This is a relevant limitation, as @schaefi mentioned we use UUID to identify changes on partitions, thus for expandable images the UUID changes during firstboot. It is not clear to me if the predefined UUID should be the first one or the second one? I believe both would make sense under certain circumstances.

For the benefits suggested with this predefined UUIDs approach I also believe that from KIWI's POV only the containers use case makes sense or implies a new feature and I have the feeling this is a very specific nspawn or lxc related feature. Is there any actual demand for that? To me this seems a fun feature using disk images as containers, but is there any real demand on that?

**Comment by lnussel** [comment]
Chicken and egg problem. As soon as we start using this in practice I'm sure other components will pick it up. I ran into this due to broken hacks required in ARM images to detect he root volume UUID in dracut for u-boot.

The UUIDs are not expected to change, that would defeat the whole purpose. They may add more though. If really wanted I guess we could add tool that dumps the current options based on https://github.com/systemd/systemd/blob/master/src/shared/gpt.h

Anyways, feel free to discuss the gaps you see with upstream. I am just relaying the information here, I was not involved in the design. To me it makes total sense to support that on the platforms where it's specified.

Specifying the UUID in the kiwi file would be tricky as it's different on each arch and we want to reuse the kiwi file. So transparently using those UUIDs makes more sense IMO.

**Comment by lnussel** [comment]
>     5. I find it weird that the systemd specification uses different id for root and other partitions depending on the architecture.

That is explained in the linked document.

>  Also a system with an incomplete fstab is considered broken unless the idea is to delete fstab from Linux at all

Exactly. There is no need for fstab by default at all. You only need it if you want to mount extra volumes for data somewhere. The OS itself doesn't need it for itself.

> > Container managers (such as nspawn and libvirt-lxc) can decode and set up file systems contained in GPT disk images automatically and mount them to the right places, thus allowing chooting the same, identical images on bare-metal and in Linux containers. This enables true, natural portability of disk images between physical machines and Linux containers.
> 
> A container is typically an archive file not containing any partition table. I didn't get that part

In the context of docker maybe. Could be full disk image as well though that works on bare metal, VMs and as container.

**Comment by lnussel** [comment]
what format are you proposing for the uuid information?

**Comment by lnussel** [comment]
given a systemd version installed that actually supports it, how about just using this:

```
# systemd-id128 show
NAME                  ID                              
root-x86              44479540f29741b29af7d131d5f0458a
root-x86-verity       d13c5d3bb5d1422ab29f9454fdc89d76
root-x86-64           4f68bce3e8cd4db196e7fbcaf984b709
root-x86-64-verity    2c7357edebd246d9aec123d437ec2bf5
root-arm              69dad7102ce44e3cb16c21a1d49abed3
root-arm-verity       7386cdf2203c47a9a498f2ecce45a2d6
root-arm64            b921b0451df041c3af444c6f280d3fae
root-arm64-verity     df3300ced69f4c92978c9bfb0f38d820
root-ia64             993d8d3df80e4225855a9daf8ed7ea97
root-ia64-verity      86ed10d5b60745bb8957d350f23d0571
root                  4f68bce3e8cd4db196e7fbcaf984b709
root-verity           2c7357edebd246d9aec123d437ec2bf5
root-secondary        44479540f29741b29af7d131d5f0458a
root-secondary-verity d13c5d3bb5d1422ab29f9454fdc89d76
esp                   c12a7328f81f11d2ba4b00a0c93ec93b
xbootldr              bc13c2ff59e64262a352b275fd6f7172
swap                  0657fd6da4ab43c484e50933c84b4f4f
home                  933ac7e12eb44f13b8440e14e2aef915
srv                   3b8f842520e04f3b907f1a25a76f98e8
var                   4d21b016b53445c2a9fb5c16e091fd2d
tmp                   7ec6f5573bc54acab29316ef5df639d1
linux-generic         0fc63daf848347728e793d69d8477de4
# systemd-id128 show root-x86
NAME     ID                              
root-x86 44479540f29741b29af7d131d5f0458a
```

**Comment by davidcassany** [comment]
Yes, something like that is what I was having in mind, a way to get the UUID's from systemd itself, so we are certain we use a UUID that the installed systemd will recognize. The `systemd-id128 show root-x86` command is nice, so we just get what we need.

@lnussel I think you said you found this feature while looking for something related for ARM, am I right? I am just trying to figure out some specific the use case for this feature that we could benefit from (beyond the generic use cases exposed by systemd docs). Would it be helpful somehow to clear some of the hacks that are needed for images making use of u-boot?

**Comment by lnussel** [comment]
Exactly. Right now the appliances have to figure out the root partition uuid and put it into the u-boot config. If the UUID is a standardized one by default that step isn't needed anymore. Also paves the way for using systemd-boot.

**Comment by schaefi** [comment]
@lnussel systemd-boot support is now available in kiwi. See #1935 Regarding this issue we still need to actively set the UUID. All kiwi methods to create filesystems now also have an argument to set the UUID (for those filesystems that supports it).
Thus it should be relatively straight forward to ask systemd for its id and set the one we get.

However, we would use the systemd from the host to get this information and that is not necessarily the same than the one that runs on target. So I would start an implementation only if the IDs has stabilized across systemd versions

Thoughts ?

**Comment by lnussel** [comment]
As said earlier the uuids are stable. You don't have to ask systemd really. You can keep a copy of https://uapi-group.org/specifications/specs/discoverable_partitions_specification/ if you want.

**Comment by Conan-Kudo** [comment]
This is also going to be needed for supporting [UKIs in Fedora Cloud](https://fedoraproject.org/wiki/Changes/Unified_Kernel_Support_Phase_2) as well. I'm not a fan of the limitations of this specification, but we're going to need to support it for this use-case.

cc: @davdunc @kraxel

**Comment by Conan-Kudo** [comment]
cc: @davide125 @DaanDeMeyer

**Comment by Conan-Kudo** [comment]
My main concern at this point is I don't know how we use this with Btrfs subvolumes. [Fedora Cloud images have used Btrfs since Fedora Linux 35](https://fedoraproject.org/wiki/Changes/FedoraCloudBtrfsByDefault) and it seems the UAPI group didn't come up with something for discovering Btrfs subvolumes. The systemd issue on this (https://github.com/systemd/systemd/issues/23500) has no meaningful progress since it was filed.

**Comment by kraxel** [comment]
> My main concern at this point is I don't know how we use this with Btrfs subvolumes. [Fedora Cloud images have used Btrfs since Fedora Linux 35](https://fedoraproject.org/wiki/Changes/FedoraCloudBtrfsByDefault) and it seems the UAPI group didn't come up with something for discovering Btrfs subvolumes. The systemd issue on this ([systemd/systemd#23500](https://github.com/systemd/systemd/issues/23500)) has no meaningful progress since it was filed.

Finding the root subvolume works by making it the default.
`filesystem="btrfs" btrfs_root_is_subvolume="true" btrfs_set_default_volume="true"`
All other subvolumes can be mounted via /etc/fstab.

**Comment by DaanDeMeyer** [comment]
@Conan-Kudo About using this with btrfs subvolumes, I think for the moment you can still use this in combination with btrfs subvolumes by using fstab. Generally, you'd leave the partition stuff to systemd-gpt-auto-generator. You'd use `rootflags=` to set the btrfs root subvolume which will be picked up by systemd-gpt-auto-generator and for all the other btrfs subvolumes you use `/etc/fstab`. Sure this isn't as nice as discoverable btrfs subvolumes but this should work fine today.

**Comment by schaefi** [comment]
I think we should work on this one. I'll assign it to me
