### ISSUE TITLE
/var/lib/zypp/AnonymousUniqueId not deleted if packages are uninstalled

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1396]
If there are packages in the `uninstall` section, `/var/lib/zypp/AnonymousUniqueId` is recreated after it is deleted in `config.sh` as part of `suseCleanup` or a plain call to `rm -rf`.

Not sure what could be done about this, but it might need to be documented.

**Comment by schaefi** [comment]
An interesting finding, I don't know that this id file existed.

**Comment by davidcassany** [comment]
To me looks like this logic could be part of the zypper package manager class. Probably we should make sure the file is removed as the package_manager instance is gone and just trim this logic from `suseCleanup`. We should not deal with stuff in `config.sh` IMHO.

IIRC this file is used to collect zypper usage statistics on server side. I guess we should remove it as a single image could potentially be deployed n times all them should have a unique different ID to collect meaningful statistics.

Since this is a zypper specific logic I am convinced it belongs to the zypper specific package manger class. Probably cleaning this file as part of the `__del__` method of the class is enough (not sure if the class instance is still around by the time we rsync, but I doubt it as one is in prepare step and the other in create step).
