### ISSUE TITLE
when can wsl-appx.justforwsltest be deleted

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1424]
## Problem description

For support of wsl we added a temporary package named Virtualization:Appliances:Images:Testing_x86:suse/wsl-appx.justforwsltest
This package provides appx metadata which is expected to be provided by the
distribution.

This issue exists to check base on TW if the distro provides the metadata package
and to not forget about deleting it from the kiwi integration testing space

## Expected behaviour

wsl integration test builds without extra wsl-appx.justforwsltest package

**Comment by davidcassany** [comment]
Up to my undestanding the package can't be removed from the integration tests area as the integration tests are not building under the openSUSE:Factory project, hence using an incompatible signing key. `wsl-appx` includes some metadata, including the signature that is required for the image builds, this signature is the one used to sign the package, thus the one set for the OBS project.

In order to workaround this limitation the wsp-appx package and the wsl image need to happen under the same project hierarchy in OBS. According to that I just created a link of `openSUSE:Factory/wsl-appx` package in `Virtualization:Appliances:Images:Testing_x86:suse`.

**Comment by schaefi** [comment]
Thanks for looking into this. Now with the package linked to TW the test image build fails with:

```
[  203s] [ ERROR   ]: 12:28:19 | KiwiContainerSetupError: Appx Manifest not found at: 
/usr/share/wsl-appx/AppxManifest.xml
```

```
osc buildinfo images x86_64 | grep wsl-appx
  <bdep name="wsl-appx" noinstall="1" version="1" release="5.1" arch="x86_64" project="Virtualization:Appliances:Images:Testing_x86:suse" repository="openSUSE_Tumbleweed_WSL"/>
```

So looks like the package from factory does not provide the information as the test package before did ?

we use the following meta data path and expect the package to provide the data there

```xml
<type image="appx" metadata_path="/usr/share/wsl-appx">
```

I think this is not the case for the package on factory... haven't looked deeper into it though

**Comment by davidcassany** [comment]
@vogtinator @lnussel  it looks like the wsl-appx package changed since we coded the wsl support in KIWI. We have our wsl-appx package build from a Factory link [here](https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:suse/wsl-appx), however the resulting binary seams it does not include the `AppxManifest.xml` file anymore as it used to. Should we install some other additional package? Is the package providing the XML in some way but in a different location (our current expectation was `/usr/share/wsl-appx`)? 

Any hint would be appreciated, thanks

**Comment by Vogtinator** [comment]
I don't think the `wsl-appx` package in Factory ever included `AppxManifest.xml` like that, it is still using the "old" method of building an .appx file without kiwi support for that. I just rebased my branch of `wsl-appx` which can be used for kiwi appx building.

I don't know what the plan is on switching TW's WSL build over to the kiwi mechanism. @lnussel might know.

**Comment by davidcassany** [comment]
@Vogtinator thanks for the details, gonna reuse your branch again meanwhile. 

In any case this is something that needs to be clarified as we'd like to have an integration test for WSL in OBS and for that we need a package providing the expected metadata.

**Comment by lnussel** [comment]
WSL development is in Scott's team atm. Not sure what the current time line is.

**Comment by schaefi** [comment]
@lnussel ok we continue to use Fabian's branch project to build our integration test. Once you know the timeline I think it's also clear how the wsl-appx package needs to be adapted. For us we consider this now done
