### ISSUE TITLE
CentOS 7 UEFI images are not booting on UEFI

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1453]
## Problem description

The OEM integration test image for CentOS does not boot on uefi. It faces the same issue we had in SLE about grub not being capable to determine wheather to use linuxefi or not at runtime.

Looks like the workaround introduced in a46c56a54632db3628a671247cece44f52bef5de doesn't do the job for CentOS 7. Would be interesting to test the same thing on CentOS 8, I haven't done it yet.

## Expected behaviour

The resulting image boots at least on UEFI regardless of the host configuration.

## Steps to reproduce the behaviour

Use the OEM integration test image for CentOS and boot it as:

```
qmeu-kvm -m 2048 -hda ~/test.img -bios /usr/share/qemu/ovmf-x86_64-ms.bin
```

## OS and Software information
+ KIWI version: v9.20.16 (current master)
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
in kiwi we run this linuxefi modification only if the GRUB_USE_LINUXEFI setting exists. I guess this is where the centos grub2-mkconfig differs. But needs investigations first

**Comment by schaefi** [comment]
I booted a centos7 system and can confirm GRUB_USE_LINUXEFI does not exist in the grub2-mkconfig tool. This is the reason why our patching code was not applied

**Comment by schaefi** [comment]
However I can find the typical use of linuxefi in ```/etc/grub.d/10_linux```. This brings me to the following problem. It seems the customization of the linuxefi via GRUB_USE_LINUXEFI setting is a suse specific patch that does not exist elsewhere. It seems that for those version of grub that still uses linuxefi the right place to look for it is ```/etc/grub.d/10_linux```.

Thus I suggest to generally change the lookup code to reference 10_linux instead of grub2-mkconfig.

It all sucks and I really hate that distros maintain custom patches to core tools instead of working upstream. It only makes our live harder with messy code like the grub2 tools.

I don't see another way though

Thoughts ?

**Comment by schaefi** [comment]
I did further checking on the contents of /etc/grub.d and found that they are different across all distributions. This is a nightmare. For the patching of linuxefi I suggest to do it based on the grub
version. So for "grub < 2.04" always apply our linuxefi patching.

Thoughts ?

**Comment by schaefi** [comment]
I'll come up with the suggestion in code for further thoughts
