### ISSUE TITLE
Kiwi writes to `/etc/sysconfig/language` instead of `locale.conf` for languages settings

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1471]
## Problem description
Kiwi writes to `/etc/sysconfig/language` instead of `locale.conf` for languages settings on OEM image.

## Expected behaviour
Kiwi should write to `locale.conf` for languages settings.

## Steps to reproduce the behaviour
Build an image with `<locale>en_US</locale>`.

## OS and Software information
+ KIWI version: 9.20.9
+ Operating system: openSUSE Tumbleweed aarch64
+ OBS version: build.opensuse.org

**Comment by ggardet** [comment]
Code performing this update is at https://github.com/OSInside/kiwi/blob/master/kiwi/system/setup.py#L318

**Comment by Vogtinator** [comment]
The "instead of" is wrong, kiwi uses `systemd-firstboot` correctly.

However, this check here is wrong: https://github.com/OSInside/kiwi/blob/e107abbc62dbe7ab95b12db05656610ab8620b2b/kiwi/system/setup.py#L318

The file exists for backwards compat, but it must not be written to if localed is used as it takes precedence. See also https://build.opensuse.org/package/view_file/system:install:head/live-langset-data/langset.sh?expand=1 line 68.

**Comment by davidcassany** [comment]
If I understand it correctly the issue is that on SLE > 12 if we set the `/etc/sysconfig/language` it takes precedence over whatever is in `/etc/locale.conf`. However in KIWI we set both with equivalent data, thus the resulting image is fine for SLE <= 12 and SLE > 12...

@ggardet, which is the issue you actually experimented? Is that running `systemd-firstboot --locale` is not functional because there is something else written in `/etc/sysconfig/language`?

I understand that having `/etc/sysconfig/language` with RC_LANG configured on TW or SLE15 is a bad practice, however I can't see a way  to distinguish when to apply it or not. Adding a SLE <= 12 condition in KIWI code is not a solution I am happy with, is there any other criteria that can be used?

We could use an `if else` approach to use `systemd-firstboot --locale` and if not available just write `/etc/sysconfig/language` but this will make the configuration not effective for SLE12 and we are keeping `/etc/sysconfig/language` around just for SLE12 in fact. I'd like to completely get rid of `/etc/sysconfig/language` but SLE12 is still there and it will still be for a while :thinking:

**Comment by Vogtinator** [comment]
> I understand that having /etc/sysconfig/language with RC_LANG configured on TW or SLE15 is a bad practice, however I can't see a way to distinguish when to apply it or not. Adding a SLE <= 12 condition in KIWI code is not a solution I am happy with, is there any other criteria that can be used?

I don't think so. Effectively, this change was implemented by YaST no longer writing them: https://github.com/yast/yast-country/commit/b1295adb2c58b5912291f8f41b9de7db13b14a92#diff-3b96e2c564f7d2e272c9457029f49ad5

**Comment by Vogtinator** [comment]
If I'm not mistaken, SLE 12 also honours `/etc/locale.conf`, but as YaST reads and writes only sysconfig, writing into `locale.conf` or using `localectl` just didn't do anything.

So unless YaST is used, dropping support for `/etc/sysconfig/language` is actually fine even on SLE 12.

**Comment by ggardet** [comment]
I guess SLE12 uses an older kiwi, so we should be fine to update the behavior, no?
