### ISSUE TITLE
Improper grub.cfg in /EFI/BOOT/grub.cfg

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1491]
## Problem description

kiwi copies the grub.cfg created by grub2-mkconfig also to EFI/BOOT/grub.cfg such that the grub efi binary can find it. However there is a report that this grub.cfg should only contain the code to load the proper (vendor specific) grub.cfg file from the linux boot space

kiwi does this for some years and it was not an issue. On ARM and the changes there it seems to be an issue now and this needs to be investigated

**Comment by schaefi** [comment]
Details and SUSE bug reference here:

https://bugzilla.suse.com/show_bug.cgi?id=1172908

**Comment by Vogtinator** [comment]
> kiwi does this for some years and it was not an issue. On ARM and the changes there it seems to be an issue now and this needs to be investigated

On x86_64 this copy does not happen because of `firmware="uefi"`, which is why it works fine there.

https://github.com/OSInside/kiwi/blob/0a381b4a914b4aaa837a5129f1860ce7f438d0db/kiwi/bootloader/config/grub2.py#L510

This issue was introduced by https://github.com/OSInside/kiwi/commit/60b207271fe797444dc4ea1b33b734b11aa10073 where I don't quite understand the reasoning. Does Fedora's `grub2-insitall` not install a config file?
