### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by isbm** [OSInside/kiwi#1503]
## Problem description

Among other dubious deps, `zypper install python3-kiwi` asks also these dependencies:

```
bea-stax
bea-stax-api
git-gui
gitk
java-11-openj9-headless
javapackages-filesystem
javapackages-tools
timezone-java
tk
```

My instance:
```
cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.2 Beta"
```

So seems like not "just Python", but also "git-gui" and "tk" with "java"... :-) Overall, about 200Mb installation. I'd say, it is a bit of too much, no?

**Comment by schaefi** [comment]
try with --no-recommends

There are the following recommended packages on suse

```
Recommends:     jing
Recommends:     gfxboot
Recommends:     dnf
Recommends:     gpg2
```

jing: better validation schema validation error information
gfxboot: for custom bootgraphics that needs compile time during build
dnf: for building fedora/rhel on a suse host
gpg2: for repository key signature verification

I'd say gfxboot can go away, custom boot graphics are not really used in kiwi. Most people build a package that compiles it and kiwi just uses the result of that

dnf can probably also go away because since we have the kiwi box plugin and self contained build support there will be not many people building fedora on a suse host but just use kiwi boxbuild

The other two recommends are still useful in my eyes and yes jing is pulling in a ton of stuff you don't need if you description validates. That's why all of it is just recommended

Thoughts ?

**Comment by schaefi** [comment]
The packaging is also something we want to work on together with @Conan-Kudo

**Comment by schaefi** [comment]
I think all of java, git, tk and friends are the result of the jing resolving

**Comment by Conan-Kudo** [comment]
The bulk of the dep storage bloat is from `jing`. Unfortunately, I'm not sure if there's a lighter XML validator we could use...

I do still think that keeping dnf and friends in Recommends makes sense, though.

**Comment by isbm** [comment]
I would suggest to drop `Recommends`. Maybe I am saying heresy here, but I would also drop other stuff, like DNF etc. These should be just modules. :) Once you say `<packagemanager>yum</packagemanager>`, it should say "please install foobar package".

> Unfortunately, I'm not sure if there's a lighter XML validator we could use...

@Conan-Kudo there are at least implemented in Python:
- https://lxml.de/validation.html
- https://github.com/sissaschool/xmlschema

**Comment by schaefi** [comment]
> Once you say <packagemanager>yum</packagemanager>, it should say "please install foobar package".

That exists in kiwi for several tooling. However it can hardly be mapped to packages. As package names/split/renames and friends are outside of kiwi's control we can only say "please install the XY tool ... whatever package it is on your distro".
The same applies to jing. If there is a validation error we currently print this message:

```
...error message from python...
For detailed schema validation report, please install: jing
```

In fact you could use any other validation error tool but jing is really nice. So in short kiwi acts like described for tools it needs
and can't find during build time. The recommends are there as a service to users and you can instruct the package
manager to make use of it or not. So what is the deep intention to get rid of it ? I guess it's again related to embedded, and no package managers wanted ?

**Comment by schaefi** [comment]
Further on this I'd like to have a discussion with @Conan-Kudo and @davidcassany to talk how we can restructure the packaging in a way that everybody can use this concept. Overall it would be good to have the packaging source here in the git repo instead of having it spread out to the distributors.

So next step is a conversation...

**Comment by Conan-Kudo** [comment]
For reference, here's the downstream Fedora packaging for kiwi: https://src.fedoraproject.org/rpms/kiwi/blob/master/f/kiwi.spec
