### ISSUE TITLE
Allow custom root LVM volume name

### ISSUE THREAD

**Issue by deacomm** [OSInside/kiwi#1530]
## Problem description
The root LVM volume name is currently hardcoded to "LVRoot".

## Expected behaviour
Instead of using "@root" in \<systemdisk>\<volume name="...">, allow putting in a real volume name in the name attribute, together with mountpoint="/" attribute to indicate root volume.

## OS and Software information
+ KIWI version: 9.21.3
+ Operating system: SLES15
+ OBS version: not using OBS

**Comment by schaefi** [comment]
We intentionally do not allow another name for the volumes root(LVRoot) and swap(LVSwap). The reasons are a) convention (we can trust this volume to exist) and b) because the entire volume section is an optional section. You can go without it and still create a function LVM based image. As there should be no reason to explicitly specify / as a volume we have the special '@root' volume to specify attributes of the (/) volume. Currently only the size is configurable but we could also add an attribute to set the name.

However as of this point I don't see a value for this change. Can you explain why that name matters ? Also you can change the volume name in the system on your own desire using ```lvrename```. So this setting is not set in stone.

Thoughts ?

**Comment by IT-Guy-1973** [comment]
Hello @schaefi ,

Changing the name of the root logical volume is important to me. The reason is - I want to have all the logical volumes follow the same naming convention. However, like you said we could do it later after the image is created but I would prefer doing it from KIWI itself. Because in cloud environments like Azure when you create an image using a running VM it will mention that in the image. SO if I create an image using KIWI and build a VM using that image and then change the root volume name and then create an image out of that VM, the new image will say - created from a VM rather than a build from scratch.

Also, @schaefi can you let me know how we define the swaplv? I did not see it on the documentation.

Regards,
Niranjan

**Comment by schaefi** [comment]
Sorry I'm late with my answer

Thanks for the details. We'll check base on that in the sprint meeting today

> an you let me know how we define the swaplv?

you can do this in the oemconfig section:

```xml
<oemconfig>
    <oem-swap>true</oem-swap>
    <oem-swapsize>MB-value</oem-swapsize>
</oemconfig>
```

**Comment by deacomm** [comment]
> However as of this point I don't see a value for this change. Can you explain why that name matters ? Also you can change the volume name in the system on your own desire using `lvrename`. So this setting is not set in stone.

The name matters for my use case, where we have some standardized filesystem layout and naming conventions across the organization, and the OEM image I'm building with kiwi needs to match that, in order to be useful as a "golden install image".

Sure, we could rename the volume in a post-boot script, or something like that, but then what's the point of building a custom image? We could just as well use the vanilla OS image and put ALL customizations (packages, filesystems, configuration in /etc, ...) in a script.

**Comment by schaefi** [comment]
got it, we are looking into it. Thanks for the details. I was not aware that the name of the root volume is a mandatory customization for a "golden image". Usually that information is also not exposed and stays a local setting. When the implementation was done, some root volume name must be set and we thought this part doesn't need to be customized. vgroup name, lv-names on top of the root but the root itself is like / mounted to some device whose name is determined by udev and not easy to customize (needs an extra rule).

Obviously my thinking was not correct and we will take a look how to configure the root volume name.

@deacomm just for interest, you said the root lv name follows a policy. Is there some step in your process where this policy is validated or some application that makes use of the policy. Just for my own understanding and only if you can share it.

Thanks

**Comment by deacomm** [comment]
> [...] the root itself is like / mounted to some device whose name is determined by udev and not easy to customize (needs an extra rule).
In the past, before bootloaders could handle a LVM logical volume as root filesystem, that might have been the case, but nowadays in LVM-based layouts, the lvol mounted at / is just another lvol. :)

> @deacomm just for interest, you said the root lv name follows a policy. Is there some step in your process where this policy is validated or some application that makes use of the policy. Just for my own understanding and only if you can share it.
The "policy" I menation is basically just a table with recommended filesystem layout (lvol names, mount points, sizes, mount options, etc.) within internal documentation, used as a "best practices" reference for people doing the installs (or creating golden images to automate installs where possible). We have hundreds, if not thousands of servers, managed mostly by shared support teams, so having servers as consistent as possible is important.

This particular bit (lvol naming) is not strictly enforced - perhaps because we never had to enforce it, as our people tend to follow these "best practices" recommendations on their own. Although we certainly do have a way to enforce it, should it become necessary. :)

**Comment by schaefi** [comment]
@deacomm Hi there. You probably saw it there is an open PR to address your issue. Review is welcome ;)

From an XML perspective you should be able to set:

```xml
<volume name="@root=root"/>
```

Let us know if this suits you.

Thanks
