### ISSUE TITLE
debian: bootstrap packages handled like other stages, falsely assuming that the chroot is ready yet

### ISSUE THREAD

**Issue by Josua-SR** [OSInside/kiwi#1587]
## Problem description

The general steps for building a Debian rootfs are:
- debootstrap a basic chroot
- configure basic system (repositories, dns, ...)
- invoke apt to install custom package selection

In kiwi, `debootstrap` is run for a packages block of type *bootstrap*. Next, all configured repositories are configured and apt is used to install all packages listed in the bootstrap block.
What's wrong here is the assumption that all repos and apt are already usable at this point.

There are corner cases where repositories of e.g. type https require additional packages in the chroot before they are usable;
or maybe additional signing keys need to be installed ...

## Expected behaviour

usability of all repos / apt is not assumed for the bootstrap stage, by either:
- use debootstrap cli option for additional packages
- only activate one marked repository for the bootstrap packages step

## Steps to reproduce the behaviour

Sample *config.xml* that uses a repo with https, and tries to bootstrap with the required packages for that:
```
<?xml version="1.0" encoding="utf-8"?>
<image name="sr-imx6">
...
	<repository type="apt-deb" distribution="buster" components="main non-free" repository_gpgcheck="false">
		<source path="http://deb.debian.org/debian"/>
	</repository>
	<repository type="apt-deb" repository_gpgcheck="false">
		<source path="https://repo.solid-build.xyz/debian/buster/bsp-any"/>
	</repository>
	<packages type="bootstrap">
		<package name="apt-transport-https"/>
		<package name="ca-certificates"/>
...
	</packages>
	<packages type="image">
...
	</packages>
</image>
```

Sample log:
```
[ INFO    ]: 14:48:05 | Using package manager backend: apt-get
[ INFO    ]: 14:48:05 | Installing bootstrap packages
[ INFO    ]: 14:48:05 | --> collection type: onlyRequired
[ INFO    ]: 14:48:05 | --> package: apt-get
[ INFO    ]: 14:48:05 | --> package: apt-transport-https
[ INFO    ]: 14:48:05 | --> package: ca-certificates
[ ERROR   ]: 14:54:49 | KiwiCommandError: chroot: stderr: W: https://repo.solid-build.xyz/debian/buster/bsp-any/./InRelease: No system certificates available. Try installing ca-certificates.
```

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.21.17
+ Operating system: openSUSE Leap 15.2
+ OBS version: -

**Comment by davidcassany** [comment]
I believe the best approach would be to include the boostrap packages in to the debootstrap call, this way we can customize the root-tree before any chroot operation. Basically that's the purpose of the `boostrap` section. 

I remember some time ago thinking why the debian boostrap was coded different than the others regarding this bootstap phase, however I ended thinking _why not?_ , so it finally looks like we got a good use case where it makes sense to include bootstrap packages in to the debootstrap call instead of chrooting after debootstrap call is ended.

**Comment by Josua-SR** [comment]
I would agree that passing the list on to debootstrap for processing is sane.
Otherwise one would need logic for e.g. using dpkg directly in that stage ...

**Comment by Josua-SR** [comment]
Here is a first attempt at implementing the first solution delegating to debootstrap:
https://github.com/Josua-SR/kiwi/commit/70f068c9a56390fed9aa559bedcf1e91a1ebd19f

I is only superficially tested, and I am particularly unhappy with having to return an object of type Command ... ... ...:

```
return Command.call(['echo']) 
```

**Comment by davidcassany** [comment]
> I is only superficially tested, and I am particularly unhappy with having to return an object of type Command ... ... ...:
> 
Yes in fact this is one of the reasons it is actually coded the way it is. The root cause is that KIWI and debootstrap overlap in its purpose. KIWI is designed to boostrap by using a package manager, thus KIWI prepares the initial root (kernel filesystem bind mount some other few details) and then calls the package manager from the host to install into that specific root. Since APT is no capable to install packages into certain specific root the debootstrap tool exists wrapping around dpkg. The problem is that debootstrap tool also takes care of preparing the new root environment by setting the kernel bind mounts, console, etc. Here is were KIWI process and debootstrap collide, as when KIWI installs the boostrap packages it already initialized the root with some bind mounts and some basic structure, while debootstrap expects to be called against to an empty folder (without mounts and other similar artifacts).

Yesterday evening I was playing around this ideas and found a couple of alternatives. One in line of what you did, and a second one with a little more ambicious refactor. Except  PR in the following days to test and discuss it.

**Comment by Josua-SR** [comment]
@davidcassanyAgain, thanks for solving - works for me(TM)!
