### ISSUE TITLE
profile attribute for package element?

### ISSUE THREAD

**Issue by lnussel** [OSInside/kiwi#1610]
openSUSE MicroOS has [quite some profiles](https://build.opensuse.org/package/view_file/openSUSE:Factory/openSUSE-MicroOS/openSUSE-MicroOS.kiwi?expand=1). The package list for that is rather confusing and has to repeat some packages to be able to have them in different arch/profile combinations eg (shortened).
```
    <packages type="image" profiles="Pine64">
        <package name="u-boot-pine64plus" arch="aarch64"/>
        <package name="dracut-kiwi-oem-repart"/>
    </packages>
    <packages type="image" profiles="RaspberryPi">
        <package name="raspberrypi-firmware" arch="aarch64"/>
        <package name="raspberrypi-firmware-config" arch="aarch64"/>
        <package name="raspberrypi-firmware-dt" arch="aarch64"/>
        <package name="u-boot-rpiarm64" arch="aarch64"/>
        <package name="dracut-kiwi-oem-repart"/>
    </packages>
    <packages type="image" profiles="RaspberryPi2">
        <package name="raspberrypi-firmware" arch="armv7l"/>
        <package name="raspberrypi-firmware-config" arch="armv7l"/>
        <package name="raspberrypi-firmware-dt" arch="armv7l"/>
        <package name="dracut-kiwi-oem-repart"/>
    </packages>
```

So I was wondering whether it would be possible to allow a `profiles` attribute on `package` and make `arch` a list. That would allow to rearrange the config like this:

```
     <packages type="image">
        <package name="u-boot-pine64plus"           profiles="Pine64"/>
        <package name="u-boot-rpiarm64"             profiles="RaspberryPi"/>
        <package name="dracut-kiwi-oem-repart"      arch="aarch64,armv7l"/>
        <package name="raspberrypi-firmware"        profiles="RaspberryPi,RaspberryPi2"/>
        <package name="raspberrypi-firmware-config" profiles="RaspberryPi,RaspberryPi2"/>
        <package name="raspberrypi-firmware-dt"     profiles="RaspberryPi,RaspberryPi2"/>
    </packages>
```

Ie much simpler and easier to grasp.

**Comment by schaefi** [comment]
We support profiles on all top level elements but not on children of those. This was done to allow grouping of top level elements but if this concept would be extended to children of the top level it allows for several unwanted side effects, e.g

```
<packages type="image" profiles="A">
    <package name="foo" profiles="B"/>
</packages>
```

This is unfortunate, hard to read and not something we want to allow.

I can understand where this comes from as the MicroOS image description is already very complex and you try to make
it a better read. However the complexity is not caused by the semantics of the description but rather by the decision to try to mangle everything into one description. I think the complexity of the MicroOS variations could be simplified with other structure elements obs provides.

As of now we won't change the way profiles are used in kiwi

Thanks

**Comment by lnussel** [comment]
what are the other structure elements?

**Comment by davidcassany** [comment]
I believe other OBS structure elements are as simple as splitting the package into several so instead of keeping a single package with single description with extensive use of multibuilds one could think of having few packages grouping use cases, architecture or any other criteria that makes sense. Anyways, what I mean is that there are alternatives to simplify the XML image description file. I understand you might prefer having a single package for all, but this comes at the cost of having complex image descriptions.
