### ISSUE TITLE
rsync failed in docker

### ISSUE THREAD

**Issue by snowliuping** [OSInside/kiwi#1653]
## Problem description
when i use kiwi in docker, i got the error as below:
KiwiCommandError: rsync; stderr: rsync: rename  -> ""/mnt/workspace/sys_custom-result_10367/kiwi_boot_root/.4bye834c/dev/console"" failed: Device or resource busy(16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
I found out that it is because /dev/console is mounted in docker, which is different from the normal system。
If i umount /dev/console and manually create a /dev/console file, it can execute successfully

## Expected behaviour
execute successfully in docker

## Steps to reproduce the behaviour
kiwi-ng --type pxe system build

## OS and Software information
+ KIWI version:  9.19.15
+ Operating system: 
+ OBS version:

**Comment by davidcassany** [comment]
Running KIWI inside a docker container is not supported scenario. KIWI makes use of many utilities that talk directly to the kernel API (device management, partitioning, mounts, etc.). Since containers are sharing the kernel with the host KIWI does not play well inside containers. Even running privileged containers there are limitations and issues tend to appear here and there. It could be possible to make use of KIWI in some specific cases, but do not expect it to be fully functional. We are definitely not supporting this use case.

On the other hand, if you are aiming for sandboxed builds we are providing the [OSInside/kiwi-boxed-plugin](https://github.com/OSInside/kiwi-boxed-plugin). This plugin runs kiwi inside a tiny lightweight KVM image and lets you build images as a regular user.

**Comment by schaefi** [comment]
> If i umount /dev/console and manually create a /dev/console file, it can execute successfully

yeah as David said you will run into a lot of issues when building images in a privileged container. Building an image requires to use low level device I/O, this has the consequence that the container must run privileged and this invalidates the use case of containers more or less. A container shares the kernel with the host. This means all device nodes and low level I/O such as loop devices, lvm, filesystems etc etc that hooks into the kernel are shared with the host. /dev/console is one example that creates a busy state, another is libdevmapper and a lot more. In kiwi we evaluated to run it inside of containers and found many issues which can't be solved in a clean and easy way. Some situations are even unsolvable like an incompatible libdevmapper between host and container.

Therefore if you want to build images in a self contained environment please use kiwi's boxbuild command. It utilizes kvm virtualization and is almost as fast as running in containers.

If you experience issues with boxbuild just let us know
