### ISSUE TITLE
Open Build Service errors outside our control

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1665]
## Problem description

This issue exists to get in contact with the obs team to clarify on errors which we can't solve and also only happens when building in OBS

- [x] LVM build fail (test-image-lvm)
  reason is pvcreate expects udev structures to be around which is not the case in an obs worker

- [x] aarch64 python3-kiwi package can't build
  TW arm distro seems broken for several weeks, why ?

- [x] fedora builds in blocked state for unknown reason
  image builds for fedora are in blocked state for weeks because of
  blocked: downloading 1 dod packages. That can't be

- [x] WSL packages are not part of Factory yet.

**Comment by dcermak** [comment]
> ## Problem description
> 
> This issue exists to get in contact with the obs team to clarify on errors which we can't solve and also only happens when building in OBS
> 
>     * LVM build fail (test-image-lvm)
>       reason is pvcreate expects udev structures to be around which is not the case in an obs worker
> 
>     * aarch64 python3-kiwi package can't build
>       TW arm distro seems broken for several weeks, why ?

Maybe @ggardet can help out here?

> 
>     * fedora builds in blocked state for unknown reason
>       image builds for fedora are in blocked state for weeks because of
>       blocked: downloading 1 dod packages. That can't be

My guess would be that this is related to obs' fetching the Fedora repos from a single mirror per arch (atm these are ftp-stud.hs-esslingen.de and http://ftp.fau.de/) instead of utilizing metalinks. And if the mirror is overloaded, then downloading will fail or be delayed, or it might just ratelimit OBS. Not sure if there's really anything that can be done here though, besides implementing metalink support in OBS (and I'm not sure if that would help either).

**Comment by ggardet** [comment]
> > * aarch64 python3-kiwi package can't build
> >   TW arm distro seems broken for several weeks, why ?
> > ```
> 
> Maybe @ggardet can help out here?

Where do you see it fails for weeks, job history looks fine: https://build.opensuse.org/packages/python-kiwi/job_history/openSUSE:Factory:ARM/standard/aarch64

**Comment by schaefi** [comment]
@rtamalin also mentioned that pvcreate might have options to circumvent the udev lookup... needs investigation

**Comment by schaefi** [comment]
> @ggardet Where do you see it fails for weeks

here: https://build.opensuse.org/package/show/Virtualization:Appliances:Builder/python-kiwi

Would be great if you can check why. It just stopped without us changing anything. It says strange things like "nothing provides gcc" and so on

**Comment by ggardet** [comment]
> > @ggardet Where do you see it fails for weeks
> 
> here: https://build.opensuse.org/package/show/Virtualization:Appliances:Builder/python-kiwi
> 
> Would be great if you can check why. It just stopped without us changing anything. It says strange things like "nothing provides gcc" and so on

This is a problem with your `openSUSE_Tumbleweed` repo config. You likely need to drop `<path project="openSUSE:Factory:PowerPC" repository="standard"/>` part.

**Comment by schaefi** [comment]
>This is a problem with your openSUSE_Tumbleweed repo config. You likely need to drop <path >project="openSUSE:Factory:PowerPC" repository="standard"/> part.

If I do that, the power build becomes unresolvable

**Comment by schaefi** [comment]
I've created a separate repo entry for power

**Comment by ggardet** [comment]
Just a note: `openSUSE_Tumbleweed_zSystems` and `openSUSE_Tumbleweed_PowerPC` are Factory, not Tumbleweed. (Tumbleweed is released to user, whereas Factory is the latest build on OBS).

**Comment by ggardet** [comment]
Fedora builds look ok. The DoD (Download on Demand) feature may hang sometimes. The best thing to do in this case is to ping people on IRC #opensuse-buildservice

**Comment by schaefi** [comment]
> Fedora builds look ok. The DoD (Download on Demand) feature may hang sometimes. The best thing to do in this case is to ping people on IRC #opensuse-buildservice

Saw it, great thanks much for the feedback and thanks to the people who fixed it

**Comment by schaefi** [comment]
@ggardet 

>Just a note: openSUSE_Tumbleweed_zSystems and openSUSE_Tumbleweed_PowerPC are Factory, not Tumbleweed.(Tumbleweed is released to user, whereas Factory is the latest build on OBS).

Yes I understand that part. On systemZ and Power I had issues in the past with the target "TW", it did not exist or had issues. For  building the integration tests in kiwi (and that's what we use it for) I think it's ok to reference the latest and greatest. Or do you suggest that we change this ? Thanks

**Comment by ggardet** [comment]
> @ggardet
> 
> > Just a note: openSUSE_Tumbleweed_zSystems and openSUSE_Tumbleweed_PowerPC are Factory, not Tumbleweed.(Tumbleweed is released to user, whereas Factory is the latest build on OBS).
> 
> Yes I understand that part. On systemZ and Power I had issues in the past with the target "TW", it did not exist or had issues. For building the integration tests in kiwi (and that's what we use it for) I think it's ok to reference the latest and greatest. Or do you suggest that we change this ? Thanks

Yes, it seems ok for your use case. I just wanted to make sure you are aware of this. :)

**Comment by schaefi** [comment]
Regarding the LVM issue I found the following information:

```
This is a known bug (https://bugzilla.redhat.com/show_bug.cgi?id=1676612), 

I rebuilt lvm2 with the linked patch

https://sourceware.org/git/?p=lvm2.git;a=commitdiff;h=3ebce8dbd2d9afc031e0737f8feed796ec7a8df9;hp=d19e3727951853093828b072e254e447f7d61c60
which fixed the problem
```

**Comment by schaefi** [comment]
@davidcassany the WSL issue is solved for the moment. A real solution that includes the required WSL packages to be in Factory is not done yet and a task of other people which we pinged but not feedback so far. David please add further information just in case I'm missing something. Thanks

**Comment by schaefi** [comment]
As the problem with LVM is a bug in the lvm tooling we can only wait until the proposed patch settles in the packages at suse.
Therefore I check off the LVM issue and hope it self heals in the future

**Comment by seife** [comment]
At least in SLES15-SP2, the lvm.conf got update to contain `devices/external_device_info_source=udev` (the reason is in https://bugzilla.opensuse.org/show_bug.cgi?id=1179691 which is closed to the public...).

A workaround *for SLES15-SP2 at least* is, to add `--config devices/external_device_info_source=none` to all LVM commands.
I did this in a local OBS installation and am doing some further tests.

**Comment by mwilck** [comment]
So ... I'm the one responsible for the `external_device_info_source=udev` change.

I apologize for the headaches this change has caused. Apparently the Kiwi builds aren't part of regular QA (at least not those that were affected by this setting), otherwise the issue should have been detected before releasing it.

I'm not trying to find excuses, but the engineers who work on things like storage and LVM2 aren't focused on Kiwi applications. Actually, we know little about Kiwi. We didn't anticipate this, as udev is available in all "normal" environments in which the LVM tools are run. IMO the only way to avoid breakage like this in the future is QA.

**Comment by Vogtinator** [comment]
Some time ago I suggested to just start udev in OBS as well, that would've also prevented this issue. Maybe it's time to revisit that?

**Comment by schaefi** [comment]
I can't agree more. udev should be running in obs. I had a long long conversation with Adrian about this and he suggested that we should create an internal package that starts udev in it %post script and add that package to the prjconf as "support: package"

We will not be doing that :)

**Comment by schaefi** [comment]
>I apologize for the headaches this change has caused. Apparently the Kiwi builds aren't part of regular QA (at least not those that were affected by this setting), otherwise the issue should have been detected before releasing it.

Hi, @mwilck. I think there is a misunderstanding. The problem with lvm builds broke kiwi because the lvm tools changed their config from external_device_info_source=none to external_device_info_source=udev and obs doesn't run udev. So it's not kiwi that should be in QA but rather obs workers should be native suse systems. Obviously any standard installation of a suse OS has udev running such that the change in the lvm config should not cause any problem except for systems that are outside the distro standard. obs workers are non-suse systems, they are something special and that is causing the problems.

For kiwi we have QA coverage:

QA:Maintenance:Test:12-SP3:python-kiwi
QA:Maintenance:Test:12-SP4:python-kiwi
QA:Maintenance:Test:12-SP5:python-kiwi
QA:Maintenance:Test:15:python-kiwi
QA:Maintenance:Test:15-SP1:python-kiwi
QA:Maintenance:Test:15-SP2:python-kiwi
QA:Maintenance:Test:12-SP3:kiwi
QA:Maintenance:Test:12-SP4:kiwi

QA:Maintenance:Images:12-SP3:kiwi-testing
QA:Maintenance:Images:12-SP4:kiwi-testing
QA:Maintenance:Images:12-SP3:kiwi-ng-testing
QA:Maintenance:Images:12-SP4:kiwi-ng-testing
QA:Maintenance:Images:12-SP5:kiwi-ng-testing
QA:Maintenance:Images:15:kiwi-ng-testing
QA:Maintenance:Images:15-SP1:kiwi-ng-testing
QA:Maintenance:Images:15-SP2:kiwi-ng-testing

We are missing an LVM build test in that space though. But I doubt the lvm2 package wouldn't have been submitted if one of those image build tests would have a failed result ;)

**Comment by Vogtinator** [comment]
> I can't agree more. udev should be running in obs. I had a long long conversation with Adrian about this and he suggested that we should create an internal package that starts udev in it %post script and add that package to the prjconf as "support: package"
> 
> We will not be doing that :)

Rightfully so. That really should be handled by https://github.com/openSUSE/obs-build/blob/master/build-recipe-kiwi.

**Comment by schaefi** [comment]
>I'm not trying to find excuses, but the engineers who work on things like storage and LVM2 aren't focused on Kiwi applications. Actually, we know little about Kiwi. We didn't anticipate this, as udev is available in all "normal" environments in which the LVM tools are run. IMO the only way to avoid breakage like this in the future is QA.

I agree and lvm engineers also don't have to know about kiwi. kiwi is just a user of lvm like anyone else. What bites us here is the environment. Please note this is not only a kiwi thing. If you start a simple docker container and run pvcreate in it you will run into the same problem... no udev in a container.

So yes QA can help to identify the problems but to be honest we have all the integration tests for kiwi that showed us the breakage at day one of the release of the lvm2 package. So we know about it but we always have hard times to fix it in obs
because it's workers are non-standard. From my perspective one good solution apart from QA is make obs workers standard suse OS systems

If you can help to convince the obs team to move into that direction it would be fantastic. I tried and got the mentioned package solution which I consider not a real solution, sorry :)

**Comment by seife** [comment]
Anyway.
LVM automatically detects nowadays is udev is running or not and behaves accordingly.
SUSE changes the default config from "automatic" to "udev always", and then we break if udev is not running.

And this all for obscure multipath setups which even in enterprise space are a fraction of the systems.
So while the "external_device_info_source=udev" might have been a quick fix to a non-public (still...) problem, I doubt it was the best solution. "Just" fixing up multipath might be more throrough.

If I ever get to know who our new DSE is, I'll try to generate some noise as a (big ;-)) customer about this regression to make sure that it does not happen again :-)

**Comment by mwilck** [comment]
> LVM automatically detects nowadays if udev is running or not and behaves accordingly, at least that's what I understand fromt he above linked redhat bug which is an issue where this automatic detection does not work.

This is not the whole truth. Unfortunately, LVM's logic is quite twisted and affected by various settings.

For general **path filtering**, if `multipath_component_detection` is active, LVM2 uses *either* udev *or* some "native" method to determine if a path belongs to a multipath device. Which method is used depends on `external_device_info_source`; there is no fallback. This logic is in [lib/filter/filter_mpath.c](https://sourceware.org/git/?p=lvm2.git;a=blob;f=lib/filters/filter-mpath.c;h=889a2dd96c8b51ea2595c65fdf0f75963d84f635;hb=HEAD).

The patch from the Red Hat bug above is in a different code path [lib/device/dev_type.c](https://sourceware.org/git/?p=lvm2.git;a=blob;f=lib/device/dev-type.c;h=896821de840c4b1c1d9cbd307ee562ab316fd531;hb=HEAD), which is separate from filtering. This code does not take `external_device_info_source` into account; rather, it looks at `obtain_device_list_from_udev`. The LVM documentation doesn't bother explaining how these two settings are supposed to interact. Apparently they actually don't; they just affect different parts of the LVM code. If I read the code history correctly, this code path originally comes from the now obsolete **lvmetad**, whereas the filtering code is from LVM2 core.

`obtain_device_list_from_udev` defaults to 1 both upstream and under SUSE.  It's obviously desirable that LVM probe devices consistently in all code paths. That alone is a strong reason for using `external_device_info_source=udev`; under any regular conditions, udev is available. Unfortunately, there is a fallback mechanism for `obtain_device_list_from_udev`, but not for `external_device_info_source`. The right solution would be to implement the same fallback mechanism for both options in LVM2 (actually, to unify these two options into one).

The patch @schaefi was talking about is part of LVM 2.03.03. We have 2.03.05 in SLE15-SP2 and Leap 15.2, so the patch should have been included. @schaefi, what lvm2 package did you have where the patch was not applied but the change to `external_device_info_source=udev` had been made? 

> SUSE changes the default config from "automatic" to "udev always", and then we break if udev is not running.

Not true, see above.

> So while the "external_device_info_source=udev" might have been a quick fix to a non-public (still...) problem, I doubt it was the best solution. "Just" fixing up multipath might be more throrough.

I explained the technical background to you. This was not just one bug. There are multiple cases where switching this setting helped. Moreover, it forces LVM to behave *consistently* on user systems, which is good in its own right.

This has absolutely nothing to do with multipath-tools or dm-multipath. It can't be fixed in multipath. lvm used to determine devices incorrectly and inconstently, and switching the default fixes that.

**Comment by mwilck** [comment]
FTR, I've posted a patch to the lvm-devel mailing list (subject "[PATCH] config: set external_device_info_source=none if udev isn't running) with a proposed patch that would allow using `external_device_info_source=udev` and still  support environments where udev is unavailable.

**Comment by schaefi** [comment]
> FTR, I've posted a patch to the lvm-devel mailing list (subject "[PATCH] config: set external_device_info_source=none if udev isn't running) with a proposed patch that would allow using `external_device_info_source=udev` and still support environments where udev is unavailable.

This is great. Thanks much for doing this. It allows us to go back and let the lvm tools select the appropriate device source itself. For the moment we keep the way kiwi does it right now as I think it will take some time for your patch to settle in all versions where the current external_device_info_source was set to udev. Would you agree to that ?

**Comment by mwilck** [comment]
Yes, sure.
