### ISSUE TITLE
rpmdb is broken in opensuse/tumbleweed-dnf

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#1669]
## Problem description
openSUSE images produced by KIWI using DNF lack a correctly populated rpmdb for some reason. This leads to package management being completely broken in these images.

## Expected behavior

1. `rpm -qa` returns a full list of packages
2. `dnf --version` returns both the version and info from rpmdb, like it does on the Fedora Rawhide container.

```
ngompa@localhost ~> podman run --pull=always --rm -it registry.fedoraproject.org/fedora:rawhide
Trying to pull registry.fedoraproject.org/fedora:rawhide...
Getting image source signatures
Copying blob ad16fb0e8007 done
Copying config 739bc13b58 done
Writing manifest to image destination
Storing signatures
[root@b445671f5a5c /]# dnf --version
4.5.2
  Installed: dnf-0:4.5.2-1.fc34.noarch at Mon Dec 21 09:56:38 2020
  Built    : Fedora Project at Thu Dec  3 16:19:10 2020

  Installed: rpm-0:4.16.1.2-1.fc34.x86_64 at Mon Dec 21 09:56:37 2020
  Built    : Fedora Project at Wed Dec 16 12:57:28 2020
```

## Steps to reproduce the behavior
```
ngompa@localhost ~> podman run --pull=always --rm -it registry.opensuse.org/opensuse/tumbleweed-dnf
Trying to pull registry.opensuse.org/opensuse/tumbleweed-dnf:latest...
Getting image source signatures
Copying blob 3acf88ce06c4 [--------------------------------------] 0.0b / 0.0b
Copying config 60322246ca done
Writing manifest to image destination
Storing signatures
944335ab1164:/ # rpm -qa
gpg-pubkey-307e3d54-5aaa90a5
gpg-pubkey-39db7c82-5f68629b
gpg-pubkey-3dbdc284-53674dd4
944335ab1164:/ # dnf --version
4.5.2
```

## OS and Software information
+ KIWI version: 9.22.1 (version in openSUSE Tumbleweed at this writing)
+ Operating system: openSUSE Tumbleweed (20201218)
+ OBS version: 2.11~alpha.20201218T151113.0e3def877c (openSUSE Build Service on build.opensuse.org)

**Comment by Conan-Kudo** [comment]
Here's a build log from [openSUSE:Factory/opensuse-tumbleweed-dnf-image](https://build.opensuse.org/package/show/openSUSE:Factory/opensuse-tumbleweed-dnf-image):

[opensuse-tumbleweed-dnf-image-docker-dnf-log.txt](https://github.com/OSInside/kiwi/files/5726864/opensuse-tumbleweed-dnf-image-docker-dnf-log.txt)

**Comment by schaefi** [comment]
hi, I gave the image from here a short test: 

https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:suse/test-image-suse-on-dnf

looks all good to me. ```dnf list``` works as expected, also other dnf commands works. I used

```
kvm kiwi-test-image-suse-on-dnf.x86_64-1.42.1-Build10.30.vmdk -serial stdio to start the image
```

**Comment by schaefi** [comment]
I'm not going to work on it as I'm on vacation :) but maybe there is a difference in the integration test and your image that explains it

**Comment by davidcassany** [comment]
I can confirm this issue. In fact the `Virtualization:Appliances:Images:Testing_x86:suse/test-image-suse-on-dnf` is also suffering it. In the integration tests it's just hidden (or not obvious to see) because it represents a full system, but for a container it can easily become a problem as @Conan-Kudo noted.

The error can be seen because the whole rpmdb is destroyed between bootstrap and in chroot installation. The consequence of that is that for the system packages installation the rpmdb is being created from scratch again and reinstalling all the needed dependencies even if they were already part of the bootstrap. You can easily check in the integration test how the packages installed during the bootstrap phase are later on reinstalled again in the system installation phase. Since the a full system image includes packages with dependencies to everything that was claimed at bootstrap phase the result is a consistent image. However for containers one can easily see the issue, since the packages listed by the resulting rpmdb are way less than what is actually being installed.

All this is happening because `zypper` and `dnf` behave different regarding the bootstrap phase. `zypper` when the `--root` flag is provided does not relay on the host rpm configuration and macros to initalize the rpmdb. In fact it creates the rpmdb at `/var/lib/rpm` (as the rpm default) regardless any alternate path configured in the host. However ,`dnf` when bootstrapping it initializes the rpmdb to the same path as the host. Basically, it honors the rpmdb path defined in the host and applies it to he bootstrapped root, so in that case it initializes the rpmdb at `/usr/lib/sysimage/rpm` on the new root.

At openSUSE the rpmdb at bootstrap is moved from `/var/lib/rpm` to `/usr/lib/sysimage/rpm` thanks to a hacky scriptlet on the rpm package, that assumes the rpmdb is located at `/var/lib/rpm` and moves the content from one place to the other and creates the compatibility symlink for `/var/lib/rpm`.  This scriptlet just behaves badly if the rpmdb was initated to `/usr/lib/sysimage/rpm` from the very beginning.

Gonna provide a possible solution from a KIWI PoV, however one could argue that rpm package scriptlets should be more robust.

**Comment by Conan-Kudo** [comment]
We should put a fix in place, but yes, I think this warrants a bug report to the rpm package.
