### ISSUE TITLE
flexible mechanism for custom bootable disk images independent from e.g dracut

### ISSUE THREAD

**Issue by Josua-SR** [OSInside/kiwi#1670]
## Problem description

KIWI user can choose between basically 2 options:
- create a root filesystem
- create a bootable disk image (oem) using dracut-based boot logic defined by kiwi.
   This option pulls in dracut as a hard dependency, and **expects** to manage core tasks such as ramdisk creation and root filesystem expansion.

## Expected behaviour

Have a generic mechanism for creating bootable disk images without any assumption on the users software stack:

Example Workflow:
1. bootstrap basic system
2. install "system" packages
3. execute images.sh for final touches before disk image is created
4. create partitions and filesystem per description
5. execute disk.sh after disk image, and root filesystem have been created, e.g. to do final touches like storing rootfs uuid in /etc/fstab

It is my personal opinion that image type "oem" almost fits perfectly, if it didn't try to take on also those helpful tasks which require integrating with the target system (expand rootfs e.g.).
A more generic version of "oem" image type would just allow users to use their init system of choice, their initramfs of choice and their boot-logic of choice - and therefore make space for experimentation and customisation.

## Motivation

I have been creating bootable disk images for 32-bit arm sbcs targeting Debian since 2015 the hard way. That is by sticking to the tooling integrated with the distro such as debootstrap, initramfs-tools and flash-kernel so that all future updates would be safe by design, since every customization follows the processes defined by Debian for their arm port.

In this particular case, by very simple debootstrap, package installation in chroot and explicit invocation of *flash-kernel* a bootable rootfs can be created that only lacks partitioning of a block device and configuration of filesystem uuid to the system.
Therefore image types "tbz" or "ext4" already go 95% of the way, making the added effort of switching to dracut for the sole satisfaction of kiwis dependency unreasonable.
To make matters worse there are situations when dracut is simply not an option:
- old releases of debian
- systems without u-boot support for efi applications
- systems that are not 100% mainlined, i.e. need their device-tree updated with kernel updates
The latter 2 cases pull in debians flash-kernel tool (which depends on initramfs-tools) to manage all boot logic, facilitating generation of boot-scripts on kernel updates or commandline changes, wrapping of binaries with u-boot headers and installation of device-tree in /boot.

## References

[description of a debian aarch64 image with flash-kernel and initramfs-tools](https://github.com/Josua-SR/imagebuilder/tree/kiwi/sr-imx8-debian-10)
[man flash-kernel](https://manpages.debian.org/testing/flash-kernel/flash-kernel.8.en.html)

**Comment by schaefi** [comment]
ok, I got your point and maybe there is an acceptable option for you that does not require changes in kiwi itself.

When building a disk image in kiwi we expect this image to be bootable. This means among others an initrd is required to drive the boot. I know Linux can also boot without an initrd but modern kernels and rootfs concepts usually requires the loading of modules that are not compiled into the kernel as well as more than just one simple rootfs mount to boot into the system is often needed. In kiwi this means some sort of initrd creation process is a mandatory part of the disk image builder. As you also know we put on ```dracut``` as the standard but kiwi also supports the creation of a complete custom initrd. This custom initrd concept could help in what you want to achieve as you could use it as kind of a dummy step in your process.

In order to get there you can specify the following in your image description:

```xml
<type image="oem" ... initrd_system="kiwi" boot="unspecified">
```

This eliminates the dependency to dracut and moves the system to the custom kiwi initrd concept. However as I said some sort of initrd creation process will be done there is not this ```boot="unspecified"``` which leads kiwi to look into ```/usr/share/kiwi/custom_boot/unspecified```. kiwi expects an initrd description at this place which you need to provide. This description however could be super simple and also incomplete as you don't plan to use this initrd. Therefore the ```unspecified``` kiwi initrd description could look like this:

1. Create ```/usr/share/kiwi/custom_boot/unspecified/config.xml``` with the following content
    ```xml
    <?xml version="1.0" encoding="utf-8"?>

    <image schemaversion="6.8" name="initrd-oemboot-unspecified">
        <description type="boot">
            <author>Me</author>
            <contact>me@example.com</contact>
            <specification>initrd image unspecified use</specification>
        </description>
        <profiles>
            <profile name="default" description="default"/>
            <profile name="std" description="standard"/>
        </profiles>
        <preferences>
            <type image="cpio"/>
            <version>2.15.1</version>
        </preferences>
        <packages type="bootstrap">
            <package name="kernel-default"/>
        </packages>
    </image>
    ```

2. Create an empty linuxrc
    ```bash
    $ mkdir /usr/share/kiwi/custom_boot/unspecified/root
    $ touch /usr/share/kiwi/custom_boot/unspecified/root/linuxrc
    ```

That's it. This fake initrd description will not be able to boot your disk image, but I think this is clear to everybody :)
I assume all steps to make it bootable will be done by you in the magic disk.sh script.

I hope this is an acceptable solution for you because everything else would require to add support for e.g ```initrd_system="none"``` and I'm currently not sure if this is worth the effort because my expectation is that any modern
linux will need an initrd and dracut as the standard tool to create it. There might be the embedded world which uses images without any initrd and for that purpose an option to skip the entire initrd creation step in the disk builder code would make sense but at the moment there is no demand in this area.

What do you think ?

Thanks

**Comment by schaefi** [comment]
@Josua-SR any thoughts about my last comment ?

Thanks

**Comment by schaefi** [comment]
@Josua-SR unfortunately no further feedback makes us closing this one for now

**Comment by ismail** [comment]
I have a very similar use case (an aarch64 board) which needs no initrd to boot, everything is hard-coded. It would be really nice to have initrd_system="none" and kiwi would just skip any initrd setting. In
