### ISSUE TITLE
SUSE product ISOs can't be simply used as iso repo due to module concept

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1678]
## Problem description
Hello,

I try to build an SLES 15 SP2 appliance based on kiwi description "kiwi-templates-JeOS-15.2-14.8.noarch.rpm".
But it fails.

[ ERROR   ]: 18:23:44 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: No provider of 'ca-certificates-mozilla' found.
No provider of 'filesystem' found.
No provider of 'glibc-locale-base' found.
No provider of 'sles-release' found.
No provider of 'udev' found.
No provider of 'zypper' found.

## Steps to reproduce the behaviour
Build with "SLE-15-SP2-Full-x86_64-GM-Media1.iso"

<packages type="bootstrap">
    <package name="udev"/>
    <package name="filesystem"/>
    <package name="glibc-locale-base"/>
    <package name="ca-certificates-mozilla"/>
    <package name="sles-release"/>
</packages>

<repository type="rpm-dir" alias="dvd-1">
	<source path="iso:///kiwi/iso/SLE-15-SP2-Full-x86_64-GM-Media1.iso"/>
</repository>

ERROR... see Problem description

Build with "SLE-15-SP2-Full-x86_64-OU1-Media1.iso"

<packages type="bootstrap">
    <package name="udev"/>
    <package name="filesystem"/>
    <package name="glibc-locale-base"/>
    <package name="ca-certificates-mozilla"/>
    <package name="sles-release"/>
</packages>

<repository type="rpm-dir" alias="dvd-1">
	<source path="iso:///kiwi/iso/SLE-15-SP2-Full-x86_64-OU1-Media1.iso"/>
</repository>

ERROR... see Problem description

Build with "SLE-15-SP2-Full-x86_64-GM-Media1.iso"

<packages type="bootstrap">
    <package name="udev"/>
    <package name="filesystem"/>
    <package name="glibc-locale-base"/>
    <package name="ca-certificates-mozilla"/>
    <package name="sles-release"/>
</packages>

<repository type="rpm-dir" alias="dvd-1">
	<source path="iso:///kiwi/iso/SLE-15-SP1-Packages-x86_64-GM-DVD1.iso"/>
</repository>

OKAY

SUSE has changed with SLES 15 SP2 the DVDs. Package DVDs are no more available. They are integrated into Full DVDs.
But kiwi-ng is not working this new Full DVDs. Please fix it.

Or is it possible to use OBS Repos for SLES 15 SP2 with a local kiwi? I found no URL.

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.22.1
+ Operating system: openSUSE Leap 15.2
+ OBS version: ---

**Comment by schaefi** [comment]
> They are integrated into Full DVDs. But kiwi-ng is not working this new Full DVDs. Please fix it.

Thanks for reaching out. SUSE has changed the layout of the DVD with respect to the module concept. The change has happened without talking to us. Thus it's not much of a surprise that an ISO image cannot be used as simple repo source.

SUSE DVDs are organized as multi repository source. Each module is a sub-directory on the DVD and each of that sub-dirs
represents a module with its own repodata/. If you want to use this in kiwi it currently only works as follows:

* Mount the DVD
* create a repository entry for each module of SLES you want to use
  ```
  <repository type="rpm-md" alias="module-name">
      <source path="dir://dvd-mount-point/module-name"/>
  </repository>
  ```

From a kiwi perspective we don't know which modules of the DVD should be used for building an image.
There is a discussion internally if we should support a new source type that includes all modules from a DVD.

```
...excerpt from a conversation we had internall

>    Maybe Kiwi needs to be updated to somehow recognize the product
>    subdirectories on the installation media?

This could be done with an extra url type e.g

   suseiso://...

That way upstream will also accept it as it would not conflict
with any other part of the builder.
```

As there is an opportunity for customers to make use of the repos on the DVD we currently haven't set this as a high prio. But it's on our radar

Let me know what you think about the suseiso:// idea

Thanks much

**Comment by t-ru** [comment]
Im confused. SUSE changed the layout. What they are done? The new FULL DVD contains all data from the old DVDs:

- Installer DVD
- Packages DVD

The new FULL DVD is a Package DVD + Installer. No more. The only difference is in /media.1/media. The repos are the same.

SLES 15 SP1 Packages DVD media info
SUSE - SLE-15-SP1-Packages-x86_64-Build228.2-Media1.iso
SLE-15-SP1-Packages-x86_64-Build228.2-Media1.iso
1

SLES 15 SP 2 FULL DVD  media info
SUSE - SLE-15-SP2-Full-x86_64-Build209.2-Media
SLE-15-SP2-Full-x86_64-Build209.2
1

But okay. For a workaround I will try to setup each "Module" and "Product" manually in config.xml

Question 1: Is it possible to access SLES Packages Repos from OBS with a local Installation?
Question 2: I found no sample kiwi-description on kiwi-descriptions for SLES. Wich packages are minimally required is section "bootstrap" for SLES?

**Comment by schaefi** [comment]
> Im confused. SUSE changed the layout. What they are done? 

You are not alone with the confusion. As I said we were not involved. If you call the following on the ISO, e.g

```
isoinfo -f -i SLE-15-SP2-Full-aarch64-GM-Media1.iso | grep MODULE
```

You see many module subdirectories which provides their own repodata/ directory. This means even if the name "Full" might indicate there is one big repodata/ that we could simple use, this is not true. There are many individual repositories which are inter-dependent. Module dependencies was one of the new features added and it turned out that YaST somehow knows it but the world is not only YaST. All others using just the data needs to make the repodata available and this requires to specify the path/paths from the iso. I don't like it either

> Is it possible to access SLES Packages Repos from OBS with a local Installation?

yes. If you have a registered SLES system which you use as an image build host you can use the token based repo urls also in the kiwi image description as repository. But this requires you to build on that registered host and you need to find the token repo-urls from were zypper stores it

>  I found no sample kiwi-description on kiwi-descriptions for SLES.

because the repo mess is a nightmare

> Wich packages are minimally required is section "bootstrap" for SLES?

for SLES15 you can always compare this with Leap15. Therefore the following should be enough:

* https://github.com/OSInside/kiwi-descriptions/blob/master/suse/x86_64/suse-leap-15.2/config.xml#L95

replace openSUSE-release with sles-release

On a personal note. You can build SLES images in the open buildservice. OBS has access to the SLE repos which is a big plus compared to if you do this on your own system. For example the following kiwi integration test builds against s390/SLE15

* https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_s390:sle15

The repos must be added to the obs prjconfig otherwise they can't be accessed. In the kiwi XML description you then only add

```
<repository type="rpm-md">
    <source path="obsrepositories:/"/>
</repository>
```

Usually this is the better solution to build and maintain images for SLES because the ISO image is pretty static and you don't get updates

Does this makes sense ?

**Comment by t-ru** [comment]
A local OBS doesn't make sense for me. Why? It requires to much RAM. Im building images on my desktop.

I can't use openbuildservice.org. Why? I'm building images for customers. On openbuildservice.org there is no possibility
to set projects to "private".

I use kiwi-ng @ openSUSE 15.2 Leap @ WSL 2. It's working and uses max 4 GB RAM. I don't need updates for the images.
I'm creating a minimal base image. The complete post installation will be excuted after deployment by scripts (register, update, configure). This scripts running pretty well. In former times we shipped images only for VMware. Now HyperV, Azure, AWS, GCE are also required. This is the reason why I'm switching to kiwi... build images for every plattform.

**Comment by t-ru** [comment]
<repository type="rpm-dir" alias="DVD-1-Product-SLES">
		<source path="dir:///kiwi/SLE-15-SP2-Full-x86_64-GM-Media1/Product-SLES"/>
	</repository>
	<repository type="rpm-dir" alias="DVD-1-Module-Basesystem">
		<source path="dir:///kiwi/SLE-15-SP2-Full-x86_64-GM-Media1/Module-Basesystem"/>
	</repository>

... Mounting ISO manually an define the Repos manually is working.

**Comment by schaefi** [comment]
> A local OBS doesn't make sense for me. Why? It requires to much RAM. Im building images on my desktop.

not talking about local obs, just suggestion to build with the obs as a service. If you don't have sensitive information in your image description you can let obs build your image

>I can't use openbuildservice.org. Why? I'm building images for customers. On openbuildservice.org there is no possibility
>to set projects to "private".

ok so nobody is allowed t see the image description... it was just a suggestion

**Comment by schaefi** [comment]
> `<repository type="rpm-dir" alias="DVD-1-Product-SLES"> <source path="dir:///kiwi/SLE-15-SP2-Full-x86_64-GM-Media1/Product-SLES"/> </repository> <repository type="rpm-dir" alias="DVD-1-Module-Basesystem"> <source path="dir:///kiwi/SLE-15-SP2-Full-x86_64-GM-Media1/Module-Basesystem"/> </repository>`
> 
> ... Mounting ISO manually an define the Repos manually is working. Products needs also to be mounted. This contains "sles-release.rpm"

:+1:

**Comment by schaefi** [comment]
Let's see if we can make this more user friendly in the future. We will discuss this in tomorrows planning meeting. Thanks for your feedback

**Comment by t-ru** [comment]
> > Is it possible to access SLES Packages Repos from OBS with a local Installation?
> 
> yes. If you have a registered SLES system which you use as an image build host you can use the token based repo urls also in the kiwi image description as repository. But this requires you to build on that registered host and you need to find the token repo-urls from were zypper stores it
> 

Thank you for this clarification. Now I understand why it is not possible to build SLES Images with a local OBS Appliances.
The downloadable appliance is based on OpenSUSE. To install kiwi-ng on SLES to use the OBS repos is no option. I need
SLES, SLES4SAP and Livepatching... the costs for building are a nightmare for creating one time per year new images. I use the DVDs... costs = 0 + time for a writing simple mount and build script. It's not nice. But it works.

**Comment by schaefi** [comment]
ok, got it.

We discussed this issue and agreed on making the use of product ISO's more user friendly in the future with a new mime type:

```xml
<source path="suseiso://..."/>
```

Also we agreed that the existing iso:// type is probably mostly useless because none of the product ISO's from the distributions can be used with the simple mount and access code that exists in kiwi.

We plan to work on this item in the February sprint

**Comment by schaefi** [comment]
The plan to work on this issue is as follows now:

* We will come up with a documentation explaining how to prepare SUSE product media such that it can be used with kiwi. Parts of this information is already present in this issue. Why don't we implement suseiso:// media type ? The reason for this is related to how SUSE media is being produced. The way this works is done without backward compatibility. This means the suseiso:// type we could come up with now works now and might be broken with the next level of product iso's. Even worse a change will not be compatible with the former format and this would bring us in an unfortunate situation.

* In addition we will deprecate the current iso:// media type. It's broken since some time and it can't be fixed in a generic way. All distribution media comes with a certain layout and basically needs extra handling to become fully usable as repository(ies). The current implementation of the iso type which simply mounts the iso and expects its root to be a know repo is not useful. Therefore the support for it will be deprecated. If it turns out during the deprecation phase that there is a high demand and complains why we do it we will of course rollback

**Comment by schaefi** [comment]
will work on this one
