### ISSUE TITLE
building live images requries qemu-tools

### ISSUE THREAD

**Issue by DimStar77** [OSInside/kiwi#1707]
## Problem description

While building live images (iso), there is an error about 'qemu-img' not being found. the program qemu-img is part of qemu-tools.

## Expected behaviour

Working build of iso / live images

## Steps to reproduce the behaviour

Build a live image

NOTE: in openSUSE:Factory, there is currently a workaround to mitigate this issue:
`Substitute: kiwi-image:iso kiwi-systemdeps-iso-media qemu-tools`

This works around it, but is essentially the wrong point to fix it.

## OS and Software information
+ KIWI version:  9.23.5
+ Operating system:  openSUSE Tumbleweed (20210130+)
+ OBS version: 2.11~alpha.20210128T115202.53f9f9929e

**Comment by Vogtinator** [comment]
It fails because kiwi uses `qemu-img create` for creating the loop backing devices. While for squashfs that appears to be unnecessary (it has to copy everything into a squashfs anyway), it could also be replaced by a `dd if=/dev/zero of=file bs=1M seek=99 count=1` to create a sparse file.

**Comment by schaefi** [comment]
This has been fixed by David in the following merge #1697 

On the next submission of python-kiwi to Factory this will be effectively fixed for obs users too

**Comment by schaefi** [comment]
We had some issues with obs the last week which prevents us from checking the integration test status. Now everything looks good and I plan to submit a new kiwi package today. There is one open PR which would ideally also go into that release but we could also live without it.

**Comment by schaefi** [comment]
I'll keep this one open untill we made the submisson so you will be notified

**Comment by DimStar77** [comment]
> We had some issues with obs the last week which prevents us from checking the integration test status. Now everything looks good and I plan to submit a new kiwi package today. There is one open PR which would ideally also go into that release but we could also live without it.

Good - that explains why the fix was not just used to supersede the old, pending one even though it was known to have this issue

Will see to have some staging space available

**Comment by schaefi** [comment]
You could consider to use https://build.opensuse.org/project/show/Virtualization:Appliances:Staging for the time being

**Comment by qby-wenzel** [comment]
@schaefi I just tried your suggestion in using the [staging](https://build.opensuse.org/project/show/Virtualization:Appliances:Staging) version of kiwi -- which results in OBS using the latest version...
```log
[   15s] [15/300] cumulate kiwi-tools-9.23.11-1.1
[...]
[   15s] [290/300] cumulate qemu-tools-5.2.0-5.1
[   15s] [293/300] cumulate kiwi-systemdeps-core-9.23.11-1.1
[   15s] [296/300] cumulate kiwi-systemdeps-bootloaders-9.23.11-1.1
[   15s] [297/300] cumulate python3-kiwi-9.23.11-1.1
[   15s] [299/300] cumulate kiwi-systemdeps-filesystems-9.23.11-1.1
[   15s] [300/300] cumulate kiwi-systemdeps-disk-images-9.23.11-1.1
[...]
```
For an OEM image, the `kiwi-systemdeps-iso-media` package is also required, as it installs the `xorriso` package, which is mandatory:
```
[  509s] [ INFO    ]: 10:33:41 | Creating ISO filesystem
[  509s] [ DEBUG   ]: 10:33:41 | "xorriso": in paths "/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin" exists: "False" mode match: not checked
[  509s] [ ERROR   ]: 10:33:41 | KiwiIsoToolError: xorriso tool not found
```
As of #1686 is still open, I might miss something out here to adapt. The `kiwi-systemdeps-iso-media` package should be included automatically here, too? Due to kiwis dependencies in the [kiwi rpm spec](https://github.com/OSInside/kiwi/commit/bd77efd7eb4e87f198a12b57024bd8c38e52dfe2)...

**Comment by Vogtinator** [comment]
Yeah, if `installiso="true"`, then it also need some iso stuff.

**Comment by qby-wenzel** [comment]
Forget to mention, that we use both options (`installiso="true"` and `installpxe="true"`), but anyway the first one is the culprit ;)

**Comment by schaefi** [comment]
I've done the Factory submission now: ```osc rq show 868394```

>As of #1686 is still open, I might miss something out here to adapt. The kiwi-systemdeps-iso-media package should be included >automatically here, too?

The docs will follow in the next sprint (P1). Regarding your question, there is no automation in including  kiwi-systemdeps-iso-media because the provides tags concept in the obs build script is only looking at the image type (oem, iso ...) but not at individual attributes that causes further host dependencies like installiso="true"

For this to work we need to make the obs build script look deeper into the image configuration. This can be done but should be an extra issue on the ob side. I hope when we have done the documentation this information can serve for eventual further automation code.

Thanks

**Comment by Vogtinator** [comment]
> Regarding your question, there is no automation in including kiwi-systemdeps-iso-media because the provides tags concept in the obs build script is only looking at the image type (oem, iso ...) but not at individual attributes that causes further host dependencies like installiso="true"

Which means that for now `kiwi-systemdeps-disk-image` has to make sure that everything for `installiso` is also available.
