### ISSUE TITLE
devicepersistency="by-path" not working

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1747]
## Problem description

devicepersistency="by-path" is set.

Result /etc/fstab:

/dev/system/swap swap swap defaults 0 0
UUID=162a6a80-2097-449a-9ec5-71b4199c66b3 / xfs defaults 0 0
UUID=96D1-9B0D /boot/efi vfat defaults 0 0

Im using xfs on lvm for root. Mounting lvm disks with uuid is a bad, bad idea.
If you make a lvm snapshot the snapshot gets exactly the same uuid as the original volume.
If you now booting. The snapshot will be mounted instead the original volume. 

see also https://xan.manning.io/2017/05/29/best-practice-for-mounting-an-lvm-logical-volume-with-etc-fstab.html

## Expected behaviour
/dev/system/swap swap swap defaults 0 0
/dev/system/root / xfs defaults 0 0
UUID=96D1-9B0D /boot/efi vfat defaults 0 0

OR

/dev/system/swap swap swap defaults 0 0
/dev/system/root / xfs defaults 0 0
/dev/sda1 /boot/efi vfat defaults 0 0

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.12
+ Operating system: openSUSE Tumbleweed
+ OBS version: ---

**Comment by schaefi** [comment]
I was looking into this issue and have several questions. First I built an image that uses xfs and LVM to double check on the behavior. My type was as follows:

```xml
<type image="vmx" filesystem="xfs" firmware="efi">
    <systemdisk>
        <volume name="tmp"/>
        <volume name="home"/>
    </systemdisk>
</typer>
```

This results in the following fstab

```
UUID=5f19e4aa-6d99-4956-a419-7b9433e06c52 / xfs defaults 0 0
UUID=c99122e8-e449-4aa6-bcb0-765411d5fb19 /boot xfs defaults 0 0
/dev/systemVG/home /home xfs defaults 0 0
/dev/systemVG/tmp /tmp xfs defaults 0 0
UUID=CBAA-1065 /boot/efi vfat defaults 0 0
```

So for LVM volumes the persistent volume path is used. For devices outside the LVM the default UUID persistend device info is used. For the root(/) device kiwi also uses the UUID and if I understood you correctly you want us to change this to the LVM device. In my example this would be ```/dev/systemVG/LVRoot / xfs defaults 0 0```. And you are suggesting this due to the snapshot example you made. Is this correct ?

If so I'm happy to fix that part, please confirm

**Comment by schaefi** [comment]
Regarding the other suggestion to use unix devices nodes in the fstab e.g ```/dev/sda1 /boot/efi vfat defaults 0 0```.
I have concerns about this one because of two reasons:

* unix nodes are not persistent devices and can change with every boot
* unix nodes used at build time of the image are loop devices and do not represent the later real target system

From that perspective I came to the conclusion that people might be confused about what by-path means in kiwi. Actually the idea was to use the pci location as it gets created by /dev/disk/by-path/... But this is also a bad idea because I realized the pci location at build time also has no relation to the later target system and should not be used.

Thus my suggestion here is to delete ```devicepersistency="by-path"``` from kiwi and fix the root(/) setting in fstab to use the LVM name.

In the end it would result in an fstab from my example like this:

with devicepersistency="by-uuid" (or just default)

```
/dev/systemVG/LVRoot / xfs defaults 0 0
UUID=c99122e8-e449-4aa6-bcb0-765411d5fb19 /boot xfs defaults 0 0
/dev/systemVG/home /home xfs defaults 0 0
/dev/systemVG/tmp /tmp xfs defaults 0 0
UUID=CBAA-1065 /boot/efi vfat defaults 0 0
```

and with devicepersistency="by-label"

```
/dev/systemVG/LVRoot / xfs defaults 0 0
LABEL=BOOT /boot xfs defaults 0 0
/dev/systemVG/home /home xfs defaults 0 0
/dev/systemVG/tmp /tmp xfs defaults 0 0
LABEL=EFI /boot/efi vfat defaults 0 0
```

Would this be an acceptable solution for you ?

Thanks

**Comment by schaefi** [comment]
@t-ru Would this be an acceptable solution for you ?

**Comment by t-ru** [comment]
I'm using this xml for the disk

```
<type 
	image="oem" 
	filesystem="xfs" 
	format="vmdk" 
	firmware="uefi" 
	bootpartition="false" 
	devicepersistency="by-uuid"
	fscreateoptions="-i sparse=0"
	kernelcmdline="plymouth.enable=0 console=ttyS0,115200 console=tty0 mitigations=auto vmw_pvscsi.cmd_per_lun=1024 vmw_pvscsi.ring_pages=32 quiet">
	
	<bootloader name="grub2" timeout="10"/>

	<systemdisk name="system">
		<volume name="@root=root" size="30G"/>
	</systemdisk>

	<oemconfig>
		<oem-resize>false</oem-resize>
		<oem-swap>true</oem-swap>
		<oem-swapsize>20480</oem-swapsize>
		<oem-swapname>swap</oem-swapname>
	</oemconfig>          
</type>
```

This resuls currently in:

```
/dev/system/swap                           swap       swap  defaults  0  0
UUID=0a4dc616-7782-4b73-88a0-c765d367155b  /          xfs   defaults  0  1
UUID=3621-F900                             /boot/efi  vfat  defaults  0  2
```

With your solution the result should be:

```
/dev/system/swap                           swap       swap  defaults  0  0
/dev/system/root                           /          xfs   defaults  0  1
UUID=3621-F900                             /boot/efi  vfat  defaults  0  2
```




> From that perspective I came to the conclusion that people might be confused about what by-path means in kiwi. 

👍 
 
> Thus my suggestion here is to delete `devicepersistency="by-path"` from kiwi and fix the root(/) setting in fstab to use the LVM name.

👍 

> @t-ru Would this be an acceptable solution for you ?

👍

**Comment by schaefi** [comment]
:smile: all right, then let's do this. Thanks for the feedback
