### ISSUE TITLE
debootstrap need target architecture if dpkg isn't installed

### ISSUE THREAD

**Issue by mslacken** [OSInside/kiwi#1778]
## debootsrap fails
  [ INFO    ]: Processing: [                                        ] 0%[ DEBUG   ]: 14:42:40 | bootstrap: E:   Couldn't work out current architecture
  [ INFO    ]: Processing: [########################################] 100%
  [ ERROR   ]: 14:42:40 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed:   

## Reproduce with
kiwi --debug --profile Disk  system build --description kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir /var/tmp/ubuntu_$(date  +%Y%m%d)

## OS and Software information
+ KIWI version:  9.21.23
+ Operating system:  Leap 15.2

**Comment by schaefi** [comment]
You are building Ubuntu on Leap ? Did you install apt, debootstrap and friends on Leap ? I'm not aware of a working toolchain in this context. Therefore can you try:

```
kiwi-ng --profile Disk system boxbuild --box ubuntu -- --description kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir /var/tmp/ubuntu_$(date +%Y%m%d)
```

For details on boxbuild see: https://osinside.github.io/kiwi/self_contained.html

If the build works on ubuntu you can check why it does not work with the tools on Leap

**Comment by mslacken** [comment]
I installed `debbootstrap`, its friends should be pulled by the package itself.
Boxbuild also works fine, with the same config. I think the problem is more in `kiwi` itself, as `debootstrap` has an option to set the arch.

**Comment by schaefi** [comment]
Hmm, I think I don't get that part. So you said running the same debootstrap with the same kiwi call in the box on ubuntu (probably in general on Debian based distros) works but fails when using the debootstrap on a suse host with installed debian tools.

I can't follow you why kiwi should explicitly set the arch in debootstrap when this is usually not required because the host arch is the default setting. This actually also makes sense because we only support cross arch builds with boxbuild inside of VMs on emulated architectures plus the appropriate box.

So the architecture for the build is always the architecture of the running host. This concept has proven to be a stable setting and I have a hard time to wrap my mind around which arch (and why) I should set for debootstrap ?

From my perspective this seems to be a behavior difference in the tooling and could be probably solved best at that stage

Unless I misunderstood the issue

As a general recommendation. apt/apt-get/debootstrap works best on systems for which this tool chain  was developed. So I think building Debian based images should be done within Debian based host environments. That's how obs does it in its workers and that's also what kiwi's boxbuild does.

If we need to create changes in the way kiwi calls debootstrap depending on the state of how the tooling is provided for non-apt based distros we could create regressions in either way.

Thus I'm not so much in favor of adding an arch setting unless this is required in general, which I think it is not

Thoughts ?

**Comment by Conan-Kudo** [comment]
This works fine when I do Debian/Ubuntu builds on Fedora (I do this all the time for work...) and the boxbuild works too. So I think something is probably broken with debootstrap on openSUSE.

I do see that `debootstrap` in Leap 15.1 is ridiculously old (1.0.97), which means that the code hasn't been adapted for Ubuntu 18.04 or 20.04. The version in Leap 15.2 (1.0.123) should work though...

**Comment by davidcassany** [comment]
I think the solution is to install `dpkg` in the host. `debootstrap` does not require it, however without it it can't identify the architecture is working on, `debootstrap` itself is a noarch shell script, so it does not know the architecture is running on by design. It relies on some host tool to get the current runtime arch, this tool is  `dpkg` (probably to ensure the arch names are Debian ones).

From debootstrap manpages
```
--arch=ARCH
              Set the target architecture (use if dpkg isn't installed).  See also --foreign.
```
So probably we should either require `dpkg` or provide the `--arch` flag for `debootstrap` calls on apt based images.

**Comment by Conan-Kudo** [comment]
This is a bug in `debootstrap` packaging in openSUSE. `dpkg` is a dependency of `debootstrap` on Fedora.

**Comment by davidcassany** [comment]
Well, I would not necessarily consider it a bug, since `debootstrap` itself considers the possibility of being called without `dpkg` on the system.

We could discuss if `kiwi-systemdeps-core` should require `dpkg` together with `debootstrap` or try to guess the architecture somehow and make use of debootstrap's `--arch` flag. I am not happy with any of the two...

**Comment by Conan-Kudo** [comment]
> Well, I would not necessarily consider it a bug, since `debootstrap` itself considers the possibility of being called without `dpkg` on the system.
> 

There is otherwise very little point to having `dpkg` in openSUSE. It's pretty much why it exists in Fedora.

> We could discuss if `kiwi-systemdeps-core` should require `dpkg` together with `debootstrap` or try to guess the architecture somehow and make use of debootstrap's `--arch` flag. I am not happy with any of the two...

If we have a `Recommends: debootstrap`, we can also add a `Recommends: dpkg`.

**Comment by schaefi** [comment]
working on this one now
