### ISSUE TITLE
FileSystem.sync_data behaviour depends on presence of trailing / in root_dir property

### ISSUE THREAD

**Issue by Josua-SR** [OSInside/kiwi#1786]
## Problem description

Syncing data from a local folder to a filesystem on a disk image will include a top-level directory on the target FS, if the source directory does not end with a trailing '/'. This is a bad API design considering the invovled parameter is called "root_dir".

## Expected behaviour

One would expect that the contents of this *root_dir* is going to be copied to the target filesystem at the root level, regardless if a slash was skipped.

## Steps to reproduce the behaviour

Minimal example:
```
self._lodev = LoopDevice(filename='example.img', filesize_mbytes=1024, blocksize_bytes=None)
self._lodev.create(overwrite=True)
self._disk = Disk(table_type='msdos', storage_provider=self._lodev, start_sector=None)
self._disk.create_root_partition(mbsize='all_free')
self._disk.map_partitions()
system = FileSystem.new(name='ext4', device_provider=self._disk.get_device()['root'], root_dir='/tmp/example-fs', custom_args=None)
system.create_on_device(label=None)
system.sync_data(exclude=None)
```

## OS and Software information
+ KIWI version: 9.23.22
+ Operating system: Debian 10

**Comment by davidcassany** [comment]
I am not sure there is much to change in KIWI since this is the behavior of rsync, which is a well known and long standing tool. Feature wise this flexible since both behaviors are possible, include or not the top level folder. Probably we could expose or document this behavior in a more explicit way from an API perspective, but I don't see any misbehavior here.

**Comment by Josua-SR** [comment]
@davidcassany you are right - this is very much about API design more than correctness.
If you call it "root_dir" - so both root, and directory at the same time, the behaviour imo should be with a trailing /.
One option is to auto-add that if missing. Alternatively it could be called more generically source_path?

Personally I would love something like:
- source_dir : string
- strip_dirname: bool

I am not trained in API design though, maybe there are smarter names and patterns ...

**Comment by schaefi** [comment]
I agree the different behavior of a trailing slash due to the way rsync handles this is not exposed or manageable in the kiwi api.

I'm afraid I don't want to change the method parameter from root_dir to source_dir because it would be an API change that needs a deprecation policy and would break other peoples code who call the method with the root_dir="..." notation. Even though I agree with you that source_dir might be the better name we can't afford this type of change for this sort of benefit

I like the idea to add control to the sync behavior with and without a trailing slash. So how about adding this opportunity at sync time with a new optional parameter like this:

```python
def sync_data(..., force_trailing_slash: bool = False):
    ....
```

In the doc string of the method there should be a clear explanation what this parameter is good for and why it can make a difference to sync with and without a trailing slash. That information will then automatically be part of the API documentation and so users have a handle for it.

* force_trailing_slash = False: root_dir is used as provided
* force_trailing_slash = True: root_dir is changed to end with a '/'

Thoughts ?

**Comment by Josua-SR** [comment]
@schaefi I think this approach is fine. A difficult question will be the trailing /.
I would guess that most current uses of kiwi call with a /, so true would make sense imo.
