### ISSUE TITLE
Debian has no systemd-firstboot executable, unable to set local/keyboard/timezone

### ISSUE THREAD

**Issue by MartinVerges** [OSInside/kiwi#1787]
## Problem description

Kiwi-ng can't configure the system settings, as Debian has no systemd-firstboot executable. Unfortunately this issue is quite old in Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844528 but this is most likely because Debian again does things different.
```
[ INFO    ]: 00:13:43 | Setting up keytable: us
[ WARNING ]: 00:13:43 | Could not parse systemd-firstboot output
[ WARNING ]: 00:13:43 | keyboard setup skipped no capable systemd-firstboot or etc/sysconfig/keyboard found
[ INFO    ]: 00:13:43 | Setting up locale: en_US
[ WARNING ]: 00:13:43 | Could not parse systemd-firstboot output
[ INFO    ]: 00:13:43 | Setting up timezone: UTC
[ WARNING ]: 00:13:43 | Could not parse systemd-firstboot output
[ WARNING ]: 00:13:43 | chkstat not found in image. File Permissions Check skipped
```

## Expected behaviour

Configure the settings as provided in the xml file.

## Steps to reproduce the behaviour

Build a debian OS with xml:

```
    <preferences>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>UTC</timezone>
``` 

## OS and Software information
+ KIWI version:  9.23.16
+ Operating system: openSUSE Leap 15.2
+ OBS version: none

**Comment by MartinVerges** [comment]
Btw, as a workaround for the locale, I use a script in config.sh

```
echo "LANG=en_US.UTF-8" > /etc/default/locale
sed -i 's/^# \(en_US.UTF-8.*\)$/\1/g' /etc/locale.gen
locale-gen
```

I'm not sure if there exists a better/cleaner/nicer way, but this one works for me since years.

**Comment by t-ru** [comment]
I'm building SLES images and I don't use setting locale, keymap and timezone with the xml.
The reason is that is no more working. 

I ended to set it up manually.

Please ignore the


```
#==============================================================================
# Setup system locale (/etc/locale.conf)
#==============================================================================
echo "---- Setup system locale (/etc/locale.conf) ----"

echo "LANG=en_US.UTF-8" > /etc/locale.conf


#==============================================================================
# Setup keymap (/etc/vconsole.conf)
#==============================================================================
echo "---- Setup keymap (/etc/vconsole.conf) ----"

echo "KEYMAP=de-latin1-nodeadkeys" > /etc/vconsole.conf
echo "FONT=eurlatgr.psfu" >> /etc/vconsole.conf
echo "FONT_MAP=" >> /etc/vconsole.conf
echo "FONT_UNIMAP=" >> /etc/vconsole.conf


#==============================================================================
# Setup date and time 
#   -   timezone
#   -   hardware clock
#   -   ntp sync with systemd-timesyncd
#==============================================================================
echo "---- Setup date and time ----"

[ -f /etc/localtime ] && rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
echo "Time zone .............................: Europe/Berlin" 

echo "0.0 0 0.0" > /etc/adjtime
echo "0" >> /etc/adjtime
echo "UTC" >> /etc/adjtime
echo "Hardware clock use utc/local ..........: UTC"

systemctl disable systemd-timesyncd.service
echo "NTP sync with systemd-timesyncd .......: disabled"
```

**Comment by schaefi** [comment]
Thanks for the details how to do the setup on Debian based distros. We had a conversation in the sprint meeting today about this issue and came up with the following idea.

* We will add the above suggested solution in an example image description hosted on the kiwi-descriptions repository
* We will add a comment in that example explaining why this is done that way on Debian based distros. This should give users an example to start with including an explanation why this is different compared to other distributions

In kiwi we usually avoid to encode system configuration tasks because they are typically not following any standard. The locale, timezone and keyboard setting forms an exception because they are needed for a system to be operational. With systemd as one of the services available to many modern linux systems we implemented the setup utilizing systemd to reach a certain coverage. For the rest of the distros that follows a different design pattern I think we are good with providing example descriptions to support our users but I don't think it's a good idea to provide alternative implementations in code for that purpose.

I hope this makes sense to you too ?

Thanks

**Comment by MartinVerges** [comment]
Maybe a debian/ubuntu generic approach with `debconf` could be something that fit's more needs.

You can use https://manpages.debian.org/jessie/debconf/debconf-set-selections.1.en.html to set settings BEFORE installing them. I'm unsure if that helps

root@ansible ~ $ debconf-get-selections |grep -v ^#|grep -i UTF
console-setup	console-setup/charmap47	select	UTF-8

**Comment by schaefi** [comment]
Will work on this one
