### ISSUE TITLE
keep opensuse 15.1 builder in OBS until dracut-live type=dmsquash works in newer releases

### ISSUE THREAD

**Issue by db-at-work** [OSInside/kiwi#1838]
## Problem description

[ ERROR   ]: 13:28:06 | KiwiUriOpenError: http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_15.1: 404 Client Error: Not Found for url: http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_15.1

## Expected behaviour

config.xml to use available builder for leap 15.1 builds required for work-around of 

https://bugzilla.suse.com/show_bug.cgi?id=1186678

thanks !

**Comment by schaefi** [comment]
There is a policy for the Virt:App:Builder project to keep the latest two versions for each distribution. We also
documented that in the headline of the project description from here:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Builder

The reason is to allow our testing matrix to stay valid and to not let that project explode. With Leap 15.3 now released,
Leap 15.1 got dropped.

Because of that would it be acceptable for you to just branch off:

```
osc branch Virtualization:Appliances:Builder/python-kiwi
```

and add the Leap15.1 repo in your branch. It will just build

Thoughts ?

Thanks

**Comment by schaefi** [comment]
You could also ```osc linkpac``` if changes we do should be made available in your project

**Comment by db-at-work** [comment]
Builder from 15.2 works in the 15.1 config.xml and the resulting Live ISO PXE's and does dmsquash / dracut-live just fine. Sorry for the noise.
