### ISSUE TITLE
Kiwi fails to create image because no space on /tmp

### ISSUE THREAD

**Issue by Mariopaniagua** [OSInside/kiwi#1866]
## Problem description

While creating an image kiwi fails with 

```
ERROR: 14:04:17 | KiwiCommandError: mksquashfs: stderr: 
Write failed because No space left on device
```
## Expected behaviour
Image builds and I get an ISO
## Steps to reproduce the behaviour
On a bare metal machine just try to build ISO with the following command 
```kiwi-ng system build --description ./iso-build --target-dir ./tmpoutput```

## OS and Software information
+ KIWI version: 9.23.34
+ Operating system:  Fedora 33
+ OBS version:  N/A

[kiwi-error.log](https://github.com/OSInside/kiwi/files/6718140/kiwi-error.log)

**Comment by Conan-Kudo** [comment]
This seems like it might be caused by `/tmp` being tmpfs. I can reproduce this issue with [this iso-build description](https://github.com/datto/osvc21-kiwi-demo-descriptions/tree/main/iso-build).

**Comment by Conan-Kudo** [comment]
@schaefi, @davidcassany: is there a reason we use `/tmp` instead of `/var/tmp` here?

**Comment by davidcassany** [comment]
The root cause of it is here https://github.com/OSInside/kiwi/blob/0c786a8a8450b393513341ade78771017fc4a6c3/kiwi/builder/live.py#L269

We just use the output of this command to create some squashfs container. There is no logic in KIWI to place it in `/tmp` neither not to place it in `/tmp`. We just use the NamedTemporaryFile defaults. We could use `dir` optional flag to place the temporary file into a directory of our choice.
