### ISSUE TITLE
Allow signing-keys to be specified in the XML description

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1883]
## Problem description

kiwi allows to specify repo signing keys via the command line but not via the XML description

## Expected behaviour

Extend the XML description with a section to define signing keys to be imported
like it is done by the custom suseImportBuildKey method (#1876)

**Comment by dcermak** [comment]
I am not opposed to this change, but I would very much prefer if the resulting UX would not change, i.e. that one does not need to specify the exact fingerprint of the key or the package name or something along those lines, because that would make maintaining kiwi descriptions across distros rather cumbersome.

**Comment by schaefi** [comment]
I'll look into this
