### ISSUE TITLE
`jeos-firstboot` does not show up on gfx console anymore but on serial instead

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1889]
## Problem description
Since the update from 9.23.31 to 9.23.43 https://build.opensuse.org/request/show/905081 (Could be another update as well), `jeos-firstboot` does not show up on gfx console anymore but on serial instead. See: https://openqa.opensuse.org/tests/1841307#step/firstrun/6
Is there any kiwi update which could explain this?

## Expected behaviour
It should continue to show up on gfx console.

## Steps to reproduce the behaviour
Try to boot an unreleased JeOS image from Factory:ARM project. (Released JeOS image is fine)

## OS and Software information
+ KIWI version: 9.23.43
+ Operating system: openUSSE Tumbleweed aarch64
+ OBS version: build.opensuse.org

**Comment by schaefi** [comment]
The console settings are a configuration option

```xml
<type ... kernelcmdline="console=...">
    <bootloader name="grub2" console="console|gfxterm|serial" .../>
</type>
```

* via the kernel commandline console parameter you control the console behavior after/during the linux kernel loads
* via the console parameter in the bootloader section you control the console behavior of the bootloader (usually grub)
  For grub this can be a setting of ```console```, ```gfxterm``` or ```serial``` or a combination of them. For details in this regard please read: https://www.gnu.org/software/grub/manual/grub/html_node/Simple-configuration.html

By default kiwi uses the standard console settings (no serial terminal)

If you observe changes in the setup I cannot imagine it's because of kiwi changing as I double checked on the default settings to be not serial.

As I'm not responsible for the JeOS images I would kindly ask that you get in contact with the team that manages these descriptions.

Unless you think there is a bug in kiwi which causes a breaking change I'm closing this on behalf of the above information.
In any other case please open a new issue with further details.

Thanks

**Comment by ggardet** [comment]
It seems due to the grub 2.06 update. 
Sorry for the noise on kiwi side.
