### ISSUE TITLE
module_hotfixes handling in kiwi-ng dnf.py code

### ISSUE THREAD

**Issue by felicemastro** [OSInside/kiwi#1896]
## Problem description

The following logic in dnf.py is problematic:
        if Defaults.is_buildservice_worker():
            # when building in the build service, modular metadata is
            # inaccessible. In order to use modular content in the build
            # service, we need to disable modular filtering, which is
            # done with module_hotfixes option
            repo_config.set(
                name, 'module_hotfixes', '1'
            )

According to SUSE documentation:
kiwi.defaults.Defaults.is_buildservice_worker
Checks if build host is an open buildservice machine
The presence of /.buildenv on the build host indicates we are building inside of the open buildservice

This results in all repositories created by kiwi in its cache to include this "module_hotfixes" flag in the repo files. Why is this being handled in a global way for all repos vs logic that would handle this flag per repo much like is being done today with repository_gpgcheck, package_gpgcheck, and priority flags ? We may only want to set this modules_hotfixes flag for some repos and not for other repos, right ? Or am I missing something here ?

## Expected behaviour

Would be awesome to have a new param in repo definition, e.g.
   <repository type="rpm-md" alias="My_repo" repository_gpgcheck="false" package_gpgcheck="false" priority="1" **hotfixes="1"**>
        <source path="dir:///home/user/MY_REPO/"/>
    </repository>

## Steps to reproduce the behaviour

Execute "kiwi-ng system build" command.

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.44
+ Operating system: RHEL 8.3
+ OBS version:

**Comment by schaefi** [comment]
module_hotfixes is enabled for the OBS case because the way Fedora/RHEL repos are imported to the OBS space does not allow to use the modular metadata. That's the reason why it's globally set if inside of OBS. The global scope in this case imho makes sense because all repos requires this setting in the OBS case.

But I see your point. The config option module_hotfixes is a repository setting and we could expose it as a setting like other repo settings as well. My understanding so far was that using module_hotfixes is an exceptional case which you normally don't want to set when dealing with "normal" Fedora/RHEL repos. Am I mistaken on that ?

If the module_hotfixes setting is something that would be very valuable to customers because needed more often than I currently think, I would agree with you let's add it.

Thoughts ?

**Comment by felicemastro** [comment]
Thanks for looking at this, greatly appreciated.

As far as I know yes, it's exceptional.

MariaDB package installation is one example where this flag must be used. More info here:
https://downloads.mariadb.org/mariadb/repositories/#distro=RedHat&distro_release=rhel8-amd64--rhel8&mirror=accretive&version=10.5
https://bugzilla.redhat.com/show_bug.cgi?id=1780363#c1
https://jira.mariadb.org/browse/MDEV-20673

I like your rationale that it's a repository setting and we could expose it like other repo settings ... in my opinion, this alone is justification for going forward with this.

What is the process for adding this new attribute in the schema and modifying the dnf.py code ? As you can clearly see I am new to this. Would you be the one making the changes ?

Thanks,
Felice

**Comment by schaefi** [comment]
I can come up with a pull request to implement this part.

In general we are happy to receive contributions :) Regarding the needed changes they would be
primarily in

* schema/kiwi.rnc (element <repository>)
* system/setup.py
* system/prepare.py

I'll look into it.

**Comment by felicemastro** [comment]
Thank you Marcus.

**Comment by schaefi** [comment]
I started to code in that direction and came across the idea to implement it in a more generic way.

Actually repo files can contain several options which we cannot set by kiwi as of today. Supporting each of them with an extra attribute is not really a good idea because there is no standard for repo files across the different package managers. module_hotfixes in this particular example is specific to dnf and the module concept on Fedora.

Thus I'll come up with an implementation of a broader scope based on a script hook like the following example shows

```xml
<repository ... customize="/path/to/custom_script">
    <source path="..."/>
</repository>
```

In your case this would mean you need to write a script ```/path/to/custom_script``` which is invoked with the package manager dependent repo file as parameter. The script contents should be relatively simple

```bash
repo_file=$1
# update/change repo_file as you desire
```

The implementation in kiwi will make sure the script gets imported into the new root-tree as long as the image build runs such that it will work in and outside of a chroot operation. Meaning the script can be used to update the repo file in the early bootstrap phase as well as later in the image phase(chroot call of the package manager)

I'll also update the documentation how to use the new ```customize``` attribute

From a user perspective it's a little bit more effort to set the option(s) you need compared to just add a attribute to the kiwi description but I hope you agree with me that we want this in a more generic way and can offer the same solution to a user when another special setup of the repo file is needed in the future

Thanks

**Comment by felicemastro** [comment]
Hi Marcus,
Great idea, very clever ... I'm sold :). Totally favor any approach that is flexible like this one is.
Thanks a lot for getting on top of it.
Best regards,
Felice

**Comment by schaefi** [comment]
ok PR open for review

**Comment by felicemastro** [comment]
Hi Marcus,

Thanks for doing this so quickly. I installed your new package manually and tested it. Works like a charm :).

I used this simple script:
repo_file=$1
echo "module_hotfixes=true" >> $repo_file

And added this to the repo in question in my config.xml:
<repository ... customize="custom.sh">
        <source path="..."/>
</repository>

I can see the hotfixes flag added to my repo in /var/cache/kiwi/repos :).

Thanks again for handling this so quickly, greatly appreciated.

Best regards,
/Felice

**Comment by felicemastro** [comment]
Hey Marcus,

One comment maybe I am wrong about this. When I installed your kiwi changes using setup.py, I noticed show --version indicated latest available kiwi version instead of some unofficial patch version. Shouldn't you also modify version info in case someone pulls the zip file and installs the dirty way with setup.py vs pip install ? Am I missing something here ?

How long does it usually take for your modifications to be merged in master ? Is there anything I can do to expedite it ?

Thanks again,
Felice

**Comment by schaefi** [comment]
Hi @felicemastro thanks much for testing and the confirmation that it worked for you :+1: 

You are right we do not expose the patchlevel. The information is however present in kiwi/version.py. The field
```__githash__ = '$Format:%H$'``` should contain the git hash and that will point to the unofficial branch.

> How long does it usually take for your modifications to be merged in master ?

we are fast :) I plan to merge the PR on behalf of your positive response today. This will make an update available on pip as well as on the Virtualization:Appliances:Staging project in OBS. For the update to appear in the SUSE distribution I will wait for the integration tests to pass. I suggest to fetch the update from pip as the update on distribution repositories naturally takes longer

Would that work for you ?

**Comment by felicemastro** [comment]
Great Marcus, thanks again for your awesome support !
