### ISSUE TITLE
Remove "rpm-dir" repository type support

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#1926]
KIWI has a generic "rpm-dir" type repository, which in practice only works with Zypper's special "rpm-dir" repository type. No other RPM package manager has this capability, and OBS does not use it, even with Zypper.

We should _immediately_ deprecate this in KIWI 9 for removal in KIWI 10.

**Comment by Conan-Kudo** [comment]
Now that Zypper has dropped support, this needs to be done ASAP.

**Comment by schaefi** [comment]
From the discussion in the community meeting:

* we are going to drop rpm-dir from the list of allowed repo types
* we are adding an XSLT stylesheet to drop rpm-dir if present. This will keep any image description functional and doesn't change the processing in zypper because add-repo is called without any explicit type to let zypper decide

Users can still pass any directory with arbitrary packages. How and if zypper can consume/will continue to consume this information is outside of kiwi's responsibility.

On a personal note: The zypper team has no dedicated test for rpm-dir repos and we have seen this feature to fail in the past. We recommend to call ```createrepo``` and use the repository as proper rpm-md type
