### ISSUE TITLE
Using Repos of updates.suse.com

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1959]
## Problem description
Hello,

currently I use a RMT to mirror the repos of updates.suse.com. That repos will be used in my kiwi descriptions.
Now I want to move to cloud and I want to use the repos of updates.suse.com directly.

I added:

```
<repository alias="Module-Basesystem" username="SCC_daax...." password="58784a....">
		<source path="https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP3/x86_64/product"/>
</repository>

```
username and password are copied from scccredentials. On build I get the error:

```
[ ERROR   ]: 05:01:34 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: Repository 'Module-Basesystem' is invalid.
[Module-Basesystem|https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP3/x86_64/product?credentials=kiwiRepoCredentials] Valid metadata not found at specified URL
History:
 - [|] Error trying to read from 'https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP3/x86_64/product?credentials=kiwiRepoCredentials'
 - Permission to access 'https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP3/x86_64/product/content?credentials=kiwiRepoCredentials' denied.
Visit the SUSE Customer Center to check whether your registration is valid and has not expired.

Please check if the URIs defined for this repository are pointing to a valid repository.
Some of the repositories have not been refreshed because of an error.
```

What I need to do to use the repos of update.suse.com directly?

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.24.1
+ Operating system: SLES 15.3
+ OBS version: ---

**Comment by schaefi** [comment]
ok, so you have a container that was registered against SLE15 SP3. If you now go to

```
/etc/zypp/repos.d
```

you will see all the ```.repo``` files. If you look into them you will see something like:

```
baseurl=...
```

The baseurl is afaik encoded in a token format. If you want to run kiwi inside of that container your ```<repository>``` sections can make use of the baseurl's as listed in the .repo files

If the baseurl uses a username/password reference you need to provide this information in the ```<repository>``` by the username= and password= attributes. These credentials are available below ```/etc/zypp/credentials.d```

**Comment by schaefi** [comment]
> Second Question: Is possible to use ENV variables in the kiwi description?

nope, the kiwi XML description does not use environment variables from the host. Users who wants that often uses a template engine e.g jinja and add the meta tags into the kiwi description. The process to build is then template first, kiwi second. So some sort of pre processing is needed to get there.

We intentionally don't wanted to allow environment substitution by default because this means the description would be no longer deterministic depending on values from env variables. Also you would be screwed when running the appliance builder outside of a shell environment.

So we left that part to the user side and their use cases as we thought it's relatively simple to apply a preprocessing in "some way" prior calling kiwi 

Hope this makes sense ?

**Comment by schaefi** [comment]
iirc questions of this issue were answered. Closing this one now. Please open a new ticket if the provided answers did not suit you. Thanks
