### ISSUE TITLE
Debian OEM image is not rebootable

### ISSUE THREAD

**Issue by ozboss** [OSInside/kiwi#1991]
## Problem description

Currently a Debian OEM image created with kiwi is not rebootable by default.
There is no entry created in the NVRAM. For the installation to be rebootable it is necessary to do a `grub-install` after installation.

Is this behavior intended?
I'm only testing with EFI in VirtualBox and I think it is not handling the default EFI boot location.
Maybe this will work better on real hardware, but still this is not very convenient and I'm currently handling it with a custom firstboot script.

## Expected behaviour

During installation of the OEM image a NVRAM entry is created.

## Steps to reproduce the behaviour

- Create a Debian OEM image
- Install the image
- Reboot

## OS and Software information
+ KIWI version: 9.24.6
+ Operating system: Debian 10
+ OBS version: -

**Comment by schaefi** [comment]
Hmm, I cannot reproduce this behavior so far. To be fair I tested Ubuntu focal and with KVM and /usr/share/qemu/ovmf-x86_64-ms.bin... will give it another try with Debian 10 later

The update of the NVRAM is usally a task done by the mokutil/efibootmgr tools and integrated into the boot process of the distributions. Since this part is not handled consistently across the distributions I'm a bit reluctant on patching kiwi or seeing this as a responsibility of the appliance builder.

Let's check if we find the root cause and a generic solution which can be placed as part of the appliance build.

**Comment by Conan-Kudo** [comment]
I think it worked with Debian 11, which is more in sync with what Ubuntu 20.04 offered. Try testing that and see if it works there?

**Comment by schaefi** [comment]
Unless provided with more details on this issue I think we can't do much. I was also not able to reproduce this on the Debian integration test from here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:debian/test-image-live-disk

@ozboss could you provide us with more details that allows us to reproduce the issue

Thanks

**Comment by ozboss** [comment]
I spent the better half of the day trying to recreate the scenario I had and so far it does not seem to happen anymore. Not sure what changed, but I guess the issue can be closed. Thanks for the fast response and your effort though.
