### ISSUE TITLE
Support patches for KIWI file system preparation

### ISSUE THREAD

**Issue by elfring** [OSInside/kiwi#2017]
[Overlay files](https://github.com/OSInside/kiwi/blob/caf1b633feb8a3e85047bac4e0085ddbe003530d/doc/source/overview.rst#terminology "Documentation") would completely replace items in a configured directory structure.
:thought_balloon: I imagine that more fine-grained control will occasionally be needed for the adjustment of some contents.
Thus I suggest to support also the application of patches instead of (or in addition to) overlay data. :thinking:

**Comment by schaefi** [comment]
I think you can achieve this without further changes on the kiwi code. Thinking about the following setup

```
root/A.patch
root/B.patch
```

Apply patches as part of the ```config.sh``` script

```bash
set -ex

for patch in A.patch B.patch;do
    patch -p0 < $patch
    rm $patch
done
```

**Comment by schaefi** [comment]
Sorry for the long delay on this topic, it felt off my radar

I'm going to close this one now. If you think this does not match your needs please open a new issue with further details.

Thanks

**Comment by elfring** [comment]
:thought_balloon: I hope still that development interests can grow also for previously mentioned information and subsequent file system preparation approaches.

**Comment by elfring** [comment]
I assume that involved “radars” can be adjusted.
:crystal_ball: How will the chances evolve to clarify remaining open issues?

**Comment by elfring** [comment]
Are you aware of any remaining system configuration challenges also according to [overlay files](https://github.com/OSInside/kiwi/blob/caf1b633feb8a3e85047bac4e0085ddbe003530d/doc/source/overview.rst#terminology)?

**Comment by schaefi** [comment]
I think on Linux there are 1001 ways to setup a system :) This is also the reason why from an appliance building perspective the ```system configuration``` is not a direct responsibility of kiwi. This means kiwi provides techniques to integrate with system configuration tasks but it does not implement any sort of system configuration in its own code. For users of kiwi this means they need to decide how they want to maintain the system configuration task as part of their kiwi image description. From my experience this brings up the following questions:

* Is my configuration static ? if yes I can go with simple overlay files
* Is my configuration static but should be manageable in the later system ? if yes I should package my configuration and install them
* Is my configuration dynamic and requires to be processed on the later target system ? If yes I need to implement a process to run some config utility and integrate this into my image configuration. Thinkable: anaconda profile + systemd unit or another million ways to do this
* Is my configuration pre-populated and needs to be adapted at build time of the image ? If yes your patch concept could be one solution

So in general system configuration is pretty use case specific and kiwi is flexible enough to offer you many ways to integrate with whatever you need. This is because kiwi does not tell users how they need to apply a system configuration. That also means it's a bit of work for users to manage it.

If you can share your needs for the system configuration we are happy to assist and share our thoughts how to do it in a good way. As I said there is always more than one way and a good part of it is often personal preference. However, I suggest you join the kiwi matrix channel on Element for this type of conversation

https://osinside.github.io/kiwi/#contact

Hope this helps a bit, cheers

**Comment by elfring** [comment]
>This is also the reason why from an appliance building perspective the `system configuration` is not a direct responsibility of kiwi.

I wonder about such a view.

I got the impression that this software development tool should be able to help a bit more with the construction of corresponding “images“.


>If yes your patch concept could be one solution

Thanks for another bit of positive feedback.

How much will development interests evolve further for the advanced handling of overlay files?


>This is because kiwi does not tell users how they need to apply a system configuration. That also means it's a bit of work for users to manage it.

:thinking: I hope that such an application area can become easier and safer.

**Comment by schaefi** [comment]
> I got the impression that this software development tool should be able to help a bit more with the construction of corresponding “images“.

Well, I think with the construction of images we do everything we can to support our users in the best way. However I differentiate between the ```construction of an image``` and the ```target functionality``` of that image once it got deployed on the target machine. Let's make an example. You want to build a web-server image. The task to provide the needed apache configuration, the startup of the services, the document root setup, etc etc. This is not considered a responsibility of kiwi.
You will not find any line of code in kiwi that tells a user how to do this. And the reason for this is: Because there is no standard way and people love to have the freedom of choice. In addition there are plenty of other projects and subsystems which supports users with exactly that: "system configuration". Maybe you know; salt, ansible ... and many more. From my perspective kiwi must be flexible enough that users can integrate with all the existing tools. I would consider it a big issue if kiwi would somehow prevent users from writing an image description that cannot make use of e.g an ansible playbook

You should see kiwi as one tool in a process chain. kiwi is the part that creates you the image. The part in the process that sets up the image to function according to your use case is not a responsibility of the image builder, it's the responsibility of your ideas and the tooling you prefer. This is basically the value you add to your image description and you could also share this with other people in a way to demonstrate how you did it. If the world takes it as a standard we could also implement this in kiwi. But as long as system configurations can be done in 1001 ways I think it's better to keep the freedom of choice.

It's maybe not what you wanted to hear but I think it's important to understand that we do not invest into system configurations with the kiwi project because we believe there are other better tools available to handle this part

Thanks
