### ISSUE TITLE
build stops with "useradd: group 'foo' does not exist"

### ISSUE THREAD

**Issue by nexryai** [OSInside/kiwi#2067]
## Problem description
Build aborted with error "KiwiCommandError: chroot: stderr: useradd: group 'hoge' does not exist". Here is the log.

```
INFO: 20:50:13 | Copying user defined files to image tree
DEBUG: 20:50:13 | EXEC: [rsync -r -p -t -D -H -X -A --one-file-system --links /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/tmp/config/root/ /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root]
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root grep -q ^root: /etc/group]
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root grep -q ^live: /etc/group]
DEBUG: 20:50:13 | EXEC: Failed with stderr: (no output on stderr), stdout: (no output on stdout)
INFO: 20:50:13 | Adding group live
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root groupadd live]
INFO: 20:50:13 | Setting up user root
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root grep -q ^root: /etc/passwd]
DEBUG: 20:50:13 | EXEC: [openssl passwd -1 -salt xyz root7]
INFO: 20:50:13 | --> Modifying user: root
INFO: 20:50:13 | --> Primary group for user root: root
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root usermod -p $1$xyz$0QQY0hyW88RFzAkb82Lrz1 -g root root]
INFO: 20:50:13 | Setting up user live
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root grep -q ^live: /etc/passwd]
DEBUG: 20:50:13 | EXEC: Failed with stderr: (no output on stderr), stdout: (no output on stdout)
DEBUG: 20:50:13 | EXEC: [openssl passwd -1 -salt xyz root7]
INFO: 20:50:13 | --> Adding user: live
INFO: 20:50:13 | --> Primary group for user live: live
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root useradd -p $1$xyz$0QQY0hyW88RFzAkb82Lrz1 -g live -m -d /home/live live]
DEBUG: 20:50:13 | EXEC: Failed with stderr: useradd: group 'live' does not exist
, stdout: (no output on stdout)
ERROR: 20:50:13 | KiwiCommandError: chroot: stderr: useradd: group 'live' does not exist
, stdout: (no output on stdout)
INFO: 20:50:13 | Cleaning up SystemPrepare instance

```
## Expected behaviour
The group "live" should be added successfully and the build should continue.

## Steps to reproduce the behaviour
Build this recipe. (I was able to build the exact same recipe until the other day.)

```
<?xml version="1.0" encoding="utf-8"?>
<image schemaversion="7.3" name="alexandrite-os">
    <description type="system">
        <author>nexryai</author>
        <contact>nexryai@gmail.com</contact>
        <specification>AlexandriteOS Workstation</specification>
    </description>
    <profiles>
        <profile name="DracutLive" description="Simple Live image" import="true"/>
        <profile name="Live" description="Live image"/>
        <profile name="Virtual" description="Simple Disk image"/>
        <profile name="Disk" description="Expandable Disk image"/>
    </profiles>
    <preferences>
        <version>3.00</version>
        <packagemanager>zypper</packagemanager>
        <locale>ja_JP</locale>
        <keytable>ja</keytable>
        <timezone>Asia/Tokyo</timezone>
        <rpm-excludedocs>true</rpm-excludedocs>
        <rpm-check-signatures>false</rpm-check-signatures>
        <bootsplash-theme>naiad</bootsplash-theme>
        <bootloader-theme>naiad</bootloader-theme>
        <type image="iso" flags="overlay" firmware="efi" kernelcmdline="quiet splash lsm=apparmor,yama lockdown=confidentiality" hybridpersistent_filesystem="ext4" hybridpersistent="true" mediacheck="true" squashfscompression="zstd">
            <bootloader name="grub2" console="gfxterm" timeout="10"/>
        </type>
    </preferences>
    <users>
        <user password="root7" pwdformat="plain" home="/root" name="root" groups="root"/>
        <user password="root7" pwdformat="plain" home="/home/live" name="live" groups="live"/>
    </users>
    <repository type="rpm-md">
        <source path="https://ftp.riken.jp/Linux/opensuse/tumbleweed/repo/oss/"/>
    </repository>
    <repository type="rpm-md" repository_gpgcheck="false">
        <source path="https://ftp.riken.jp/Linux/opensuse/tumbleweed/repo/non-oss/"/>
    </repository>
    <packages type="image" patternType="plusRecommended">
        <package name="kernel-default"/>
        <package name="bind-utils"/>
        <package name="systemd"/>
        <package name="kernel-firmware-all"/>
        <package name="kernel-firmware-nvidia"/>
        <package name="ucode-amd"/>
        <package name="ucode-intel"/>
        <package name="iputils"/>
        <package name="dracut-kiwi-live"/>
        <package name="nvme-cli"/>
        <package name="biosdevname"/>
        <package name="rpcbind"/>
        <package name="mdadm"/>
        <package name="ntfs-3g"/>
        <package name="cifs-utils"/>
        <package name="gvfs"/>
        <package name="dmraid"/>
        <package name="multipath-tools"/>
        <package name="btrfsprogs"/>
        <package name="open-iscsi"/>
        <package name="keyutils"/>
        <package name="nfs-client"/>
        <package name="samba-client"/>
        <package name="NetworkManager"/>
        <package name="vim"/>
        <package name="grub2"/>
        <package name="grub2-x86_64-efi" arch="x86_64"/>
        <package name="grub2-i386-pc"/>
        <package name="snapper-zypp-plugin"/>
        <package name="kexec-tools"/>
        <package name="mokutil"/>
        <package name="syslinux"/>
        <package name="lvm2"/>
        <package name="plymouth"/>
        <package name="sudo"/>
        <package name="fontconfig"/>
        <package name="fonts-config"/>
        <package name="tar"/>
        <package name="parted"/>
        <package name="openssh"/>
        <package name="iproute2"/>
        <package name="less"/>
        <package name="tree"/>
        <package name="fish"/>
        <package name="bash-completion"/>
        <package name="dhcp-client"/>
        <package name="which"/>
        <package name="shim"/>
        <package name="timezone"/>
        <package name="dracut-kiwi-live"/>
        <package name="nano"/>
        <package name="htop"/>
        <package name="powerline"/>
        <package name="xorg-x11-server-wayland"/>
        <package name="xwayland"/>
        <package name="bluez"/>
        <package name="pipewire"/>
        <package name="gnome-session"/>
        <package name="gnome-session-wayland"/>
        <package name="gnome-desktop"/>
        <package name="gnome-shell"/>
        <package name="gdm"/>
        <package name="MozillaFirefox"/>
        <package name="MozillaFirefox-translations-common"/>
        <package name="MozillaFirefox-branding-upstream"/>
        <package name="calamares"/>
        <package name="firewalld"/>
    </packages>
    <packages type="bootstrap">
        <package name="udev"/>
        <package name="filesystem"/>
        <package name="glibc-locale"/>
        <package name="cracklib-dict-full"/>
        <package name="ca-certificates"/>
        <package name="ca-certificates-mozilla"/>
        <package name="gawk"/>
        <package name="grep"/>
        <package name="gzip"/>
        <package name="xz"/>
    </packages>
</image>
```

## OS and Software information
+ KIWI version:` KIWI (next generation) version 9.24.21`
+ Operating system:  `openSUSE Tumbleweed`
+ OBS version: 0.175.0

**Comment by schaefi** [comment]
I don't see that kiwi is doing it wrong, but I agree with you this should not happen

**Comment by nexryai** [comment]
I have noticed that the message `EXEC: Failed with stderr: (no output on stderr), stdout: (no output on stdout)` is logged in two places and it is being passed through. Is this normal?

```
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root grep -q ^live: /etc/group]
DEBUG: 20:50:13 | EXEC: Failed with stderr: (no output on stderr), stdout: (no output on stdout)
```

```
INFO: 20:50:13 | Setting up user live
DEBUG: 20:50:13 | EXEC: [chroot /run/media/suser/bb3e71a7-9e71-450b-9b72-9056e61d78f4/alexandrite/out/build/image-root grep -q ^live: /etc/passwd]
DEBUG: 20:50:13 | EXEC: Failed with stderr: (no output on stderr), stdout: (no output on stdout)
```

**Comment by schaefi** [comment]
> logged in two places and it is being passed through. Is this normal?

This is a bit of a weird logging behavior. Any command called in kiwi provides a log information if it fails with an exit code != 0.
In this case the command ```grep -q ^live: /etc/group``` is called to check if the ```live``` group exists. It does not exist and this is an exit code != 0. As consequence the group is created with ```groupadd```. As a side effect you get a log information about the failed call. The call did not produce any output on stderr or stdout

So yes it's normal ;)

**Comment by stephanebill** [comment]
Maybe this can help, I have the same problem after I updated my TW build machine last week, the build fails with:
INFO: 14:13:28 | Setting up user root
DEBUG: 14:13:28 | EXEC: [chroot /home/kiwi/minimal/build/build/image-root grep -q ^root: /etc/passwd]
INFO: 14:13:28 | --> Modifying user: root
INFO: 14:13:28 | --> Primary group for user root: root
DEBUG: 14:13:28 | EXEC: [chroot /home/kiwi/minimal/build/build/image-root usermod -p $6$TJY2VDwqhgPYYFQW$s1sJHlaobyt.Cok6jPWYsdN.nYq/KMXDAuciH5czRWp5/8CKBKpZoQSvDqA2qjyUnb8GQ4Vmel30pKN9v0ais. -g root root]
INFO: 14:13:28 | Setting up user user
DEBUG: 14:13:28 | EXEC: [chroot /home/kiwi/minimal/build/build/image-root grep -q ^user: /etc/passwd]
DEBUG: 14:13:28 | EXEC: Failed with stderr: (no output on stderr), stdout: (no output on stdout)
INFO: 14:13:28 | --> Adding user: user
INFO: 14:13:28 | --> Primary group for user user: users
DEBUG: 14:13:28 | EXEC: [chroot /home/kiwi/minimal/build/build/image-root useradd -p !! -g users -m -d /home/user user]
INFO: 14:13:28 | --> Setting permissions for /home/user
DEBUG: 14:13:28 | EXEC: [chroot /home/kiwi/minimal/build/build/image-root chown -R user:users /home/user]
DEBUG: 14:13:28 | EXEC: Failed with stderr: chown: invalid user: ?user:users?
, stdout: (no output on stdout)
ERROR: 14:13:28 | KiwiCommandError: chroot: stderr: chown: invalid user: ?user:users?
, stdout: (no output on stdout)
INFO: 14:13:28 | Cleaning up SystemPrepare instance

I do have user & users in /etc/passwd & /etc/group
If I remove this single line from <users> in config.xml, the build completes:
<user password="!!" home="/home/user" name="user" groups="users"/>

**Comment by schaefi** [comment]
Thanks for providing the details. I still have no clue what should be wrong with the sequence of commands to be honest.
I think you still have the root tree below ```/home/kiwi/minimal/build/build/image-root``` available right ?

So can you do me a favor and call

```
chroot /home/kiwi/minimal/build/build/image-root bash

useradd -p !! -g users -m -d /home/user user
# I expect this to fail because the user should exist...

chown -R user:users /home/user
# I don't see what's wrong with this call
```

Does this expose any more details what is going on ? does /etc/group and /etc/passwd contain the expected group, user ?

This one is so strange

**Comment by stephanebill** [comment]
useradd fails and chown succeeds as expected, files in /etc seem OK.

I can see other user errors in the kiwi logs that should not be there, for example if I try to install redis:
DEBUG: 15:36:50 | system: (598/619) Installing: redis-6.2.6-2.4.x86_64 [.
DEBUG: 15:36:50 | system: warning: /var/cache/kiwi/packages/tumbleweed/x86_64/redis-6.2.6-2.4.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
DEBUG: 15:36:50 | system: .
DEBUG: 15:36:50 | system: /usr/bin/systemd-sysusers -
DEBUG: 15:36:50 | system: Creating group redis with gid 463.
DEBUG: 15:36:50 | system: Creating user redis (User for redis key-value store) with uid 463 and gid 463.
DEBUG: 15:36:50 | system: warning: group redis does not exist - using root
DEBUG: 15:36:50 | system: warning: group redis does not exist - using root
DEBUG: 15:36:50 | system: warning: group redis does not exist - using root
DEBUG: 15:36:50 | system: warning: user redis does not exist - using root
DEBUG: 15:36:50 | system: warning: group redis does not exist - using root
DEBUG: 15:36:50 | system: warning: user redis does not exist - using root
DEBUG: 15:36:50 | system: warning: group redis does not exist - using root
DEBUG: 15:36:50 | system: warning: user redis does not exist - using root
DEBUG: 15:36:50 | system: warning: group redis does not exist - using root
DEBUG: 15:36:50 | system: ..........
DEBUG: 15:36:50 | system: /usr/lib/tmpfiles.d/redis.conf:2: Failed to resolve user 'redis': No such process
DEBUG: 15:36:50 | system: See /usr/share/doc/packages/redis/README.SUSE to continue
DEBUG: 15:36:50 | system: done]

And /var/lib/redis belongs to root:root in the chroot instead of redis:redis
There is no such problem if I run 'zypper in redis' from the host.
I think some systemd change does not play well with the chroot.

**Comment by stephanebill** [comment]
Finally figured out what is going on, kiwi sets up the chroot with a bind mount of /run, which contains /run/nscd/socket accessible making the glibc resolver use nscd outside the chroot. Stopping nscd makes the resolver revert to only files and everything works again.
Maybe a real fix would be to set a nsswitch.conf to ignore nscd or not bind mount the whole /run?

**Comment by schaefi** [comment]
You rock :+1: thanks much for the details. I agree this needs a real fix.

Currently the following bind mount locations are used when building

```python
self.bind_locations = [
            '/proc',
            '/dev',
            '/var/run/dbus',
            '/sys',
            '/run'
        ]
```

Actually I wanted to keep this list as small as possible but over time it grew. /run was needed for several reasons. I think one was /run/systemd.

The issue I see is that I don't exactly know the after effects if we bind mount only specific locations. As there can be more /run locations which we then implicitly use in an image build I also vote for a dedicated list of /run locations and not all

@Conan-Kudo @davidcassany Can you share your thoughts on this one, would be great.

From my perspective we only need the following from /run

* /run/systemd
* /run/udev
* /run/runc
 
* /run/mount ?
* /run/lvm ?

* /run/dbus
 
* /run/cryptsetup ?
* /run/containers ?

Thanks

**Comment by davidcassany** [comment]
ouch this is an ugly one. Yes constraining the bind mounts looks like a reasonable approach, even this is making the list longer.

What makes me feel insecure of this change is that those paths such as `/run/dbus`, `/run/runc`, etc. might change across distros. Googling I have seen many references to `/var/run/nscd/socket`, so I guess that's why we did not face it until now, because probably the nscd socket used to be placed under `/var`. So adding bind mounts that are not directly the FHS paths such as `/var/run` or `/run` are likely to be distro dependent.

Also the logic from: https://github.com/OSInside/kiwi/blob/a0cc1989c6d0b87a3f4f452fa75c51eaf8844664/kiwi/system/root_bind.py#L96-L107

could eventually suffer from that, since it requests to exist both paths and runtime paths on the image chroot are definitely not likely to be there and we don't want to create them either, or, if we create them, we need to make sure we are not copying runtime structures to the image...

I agree we need to better target the bind mounts, but I feel that simply adding more fine grained paths to the list is a naive approach.

**Comment by schaefi** [comment]
> but I feel that simply adding more fine grained paths to the list is a naive approach.

yes it's naive and it assumes the paths are compatible between host and image. However, I think a smart and intelligent solution (and I have no one in my mind to be honest) could cause hard to debug side effects either

The interesting part is that I just tried to build an image (with lvm and a bit more complexity) without /run bind mounted and that succeeded

So another question is if we really need it ?

**Comment by schaefi** [comment]
maybe making it a configurable list would help, but on the other side issues caused by this are not at all obvious and so from the error I think nobody can guess, ah yes it's this missing bind mount

**Comment by schaefi** [comment]
```diff
diff --git a/kiwi/system/root_bind.py b/kiwi/system/root_bind.py
index 6c7d56dfe..3008b0ad3 100644
--- a/kiwi/system/root_bind.py
+++ b/kiwi/system/root_bind.py
@@ -69,8 +69,7 @@ class RootBind:
             '/proc',
             '/dev',
             '/var/run/dbus',
-            '/sys',
-            '/run'
+            '/sys'
         ]
         # share the following directory with the host
         self.shared_location = '/' + Defaults.get_shared_cache_location()

```

still keeps it functional

**Comment by davidcassany** [comment]
Yes, so that brings us to the point that probably what we need to double think about is are the changes from 951231867bef6f9b17696699b85e1be98ba17e70 , since this is what introduced the issue. Could it be that this is somehow related to #2020. So all in all this all related to running containers in a chroot. What if instead of calling `podman` into the chroot you use buildah? Then you could eventually do something like `buildah run --isolation chroot`, it prevents using kernel namespaces so no `runc` or `crun` involved. I know this is not as nice and simple as directly using podman, but I guess it is reasonable to accept that podman/docker are tools that require much from the host, hence in a chroot enviornment they are not really well suited.

**Comment by Conan-Kudo** [comment]
Yeah, I think this is sort of the reason for `buildah`, splitting the container build process out and having Podman/Docker-like behavior without all the baggage for the full runtime.

Ideally, we should rework our OCI support so both dockerfile and non-dockerfile based OCI container builds go through buildah instead of supporting podman/docker for dockerfile and buildah/umoci for non-dockerfile.

**Comment by davidcassany** [comment]
> Yeah, I think this is sort of the reason for `buildah`, splitting the container build process out and having Podman/Docker-like behavior without all the baggage for the full runtime.

Yes, that's why I think buildah, if possible, is the right tool to use in `config.sh`.
 
> Ideally, we should rework our OCI support so both dockerfile and non-dockerfile based OCI container builds go through buildah instead of supporting podman/docker for dockerfile and buildah/umoci for non-dockerfile.

I am not sure I understand it, we are not making use of docker/podman in KIWI in any way. Neither supporting Dockerfiles in any way. IIRC commit 951231867bef6f9b17696699b85e1be98ba17e70 (it adds `/run` as a bind mount) was added to enable the use of podman inside `config.sh` (@schaefi can correct me if I miss something).

Regarding `umoci` support I know that buildah is supported over many distros and `umoci` doesn't, however beyond the obvious SUSE related reasons to support `umoci` there are technical ones. `umoci` the is reference implementation of the OCI standard and part of the opencontainers initiative, so it is not a SUSE only project. Moreover and the most important `umoci` is way lighter than buildah and suits KIWI workflow way better, umoci can be used to operate over OCI images with plain filesystem operations (no mounts, no container storage from the host, etc.), just set a root-tree and all its associated metadata.

**Comment by schaefi** [comment]
> I am not sure I understand it, we are not making use of docker/podman in KIWI in any way. Neither supporting Dockerfiles in any way. IIRC commit 9512318 (it adds /run as a bind mount) was added to enable the use of podman inside config.sh (@schaefi can correct me if I miss something).

yes you are completely right, and yes it seems this was all my fault :(

**Comment by Conan-Kudo** [comment]
@davidcassany I think I was confused on what the scope of this problem actually was. Thanks for clarifying what's going on.

**Comment by nexryai** [comment]
Today I updated kiwi-ng via pip and the build was working correctly again. Thanks!

**Comment by schaefi** [comment]
Thanks much for the feedback :+1: I'm going to prepare a release on the suse side
