### ISSUE TITLE
Need Error Checking/Handling in kiwi-dump-image.sh for dump_X_image() scenarios

### ISSUE THREAD

**Issue by TheMisanthropicHumanist** [OSInside/kiwi#2070]
## Problem description
We need more error checking/handling around the kiwi-dump-image.sh area of the KIWI Dracut Modules. I think it was expected that most people would use Checksum Verification to determine when Image transfers (Like in a PXE scenario with an image download | dd load.) failed for whatever reason, so no error checking/handling was ever added during the non-silent dump_X_image() or dump_image() code. But at the moment, I'm entering a situation where Checksum Verification fails incorrectly somehow (Could have to do with NVMe disks specifically, but will have to confirm later.), and disabling it in the config.xml leaves me with no troubleshooting options since the machine immediately reboots after the image_dump/verification process. I'm seeing the Image Download process fail, but I'm unable to drop to a console in debug mode to figure out why because it never:

1. Checks for an error from the image load process
2. Or subsequently performs a report_and_quit() to give me the opportunity to get to an Interactive Console

I intend to implement the fix myself - just using this as a placeholder. Will hopefully get a chance to implement this tomorrow and submit the Pull Request.

## OS and Software information
+ KIWI version: 9.24
+ Operating system: SLES15 SP3/SLES12 SP5
+ OBS version: NA

**Comment by schaefi** [comment]
I think you can get dropped into a debug environment the following way.

```xml
<oemconfig>
    <oem-reboot-interactive>true</oem-reboot-interactive>
    ...
</oemconfig>
```

Rebuild your image and make sure you use the kiwi dracut modules with version >= 9.24.22. The reason for the version
constraint is because of a fix we have made for the reboot options (#2055)

Now boot your image and use the kernel boot option:

```
rd.debug rd.shell
```

If you now repeat your deployment you will get a dialog after deployment and before reboot. As you requested
rd.debug and rd.shell it will drop you into a shell after you stated "No" to reboot

For reference this is the code for the dialog 

```
function ask_and_reboot {
    local text_message="$1"
    if ! run_dialog --yesno "\"${text_message}\"" 7 80; then
        die "${text_message}"
    else
        reboot -f
    fi
}
```

Le me know if this procedure works for you

Thanks

**Comment by schaefi** [comment]
The ```die``` method comes from dracut and drops into a shell if rd.debug is switched on

**Comment by TheMisanthropicHumanist** [comment]
Hi!

Ah, yes, it was ask_and_reboot() that I was thinking of, not report_and_quit(). Thank you! All of that information is very helpful!

(Bolded the main question to make up for my lack of concision :) )

I do have the rd.debug and rd.kiwi.debug options on, and I believe I'm using the newest version of those Dracut/KIWI Modules as I know I've been able to drop to a Console during previous failures at different stages in the deployment (Like if/when network fails, etc.). _**The rd.shell option is new to me though. Does that give me the ability to drop to a shell at any time? Or only under the condition that oem-reboot-interactive is also true?**_

If rd.shell allows me to drop to a Console at any time, then I have an easy workaround for now. If not, I'm wondering if it might also be worth it to allow one to override those OEM flags from the config.xml using the APPEND flags in PXE Menu or via Kernel Args.

And sorry, should have clarified that in this case, the intention was to have a generally non-interactive deployment that our customers could ultimately walk away from, but that I would be able to troubleshoot as-is without a flag change and rebuild. And to be fair, that is kind of asking for a lot because the concept of "non-interactive" and "unattended" implies that a Console for debugging isn't guaranteed. That being said, even with those settings on, the deployment does prompt to drop to a console after failing in other operations (Assuming proper APPEND/Kernel Args for Dracut debugging), so I see an opportunity for improvement of the debug capabilities here.

Also, it appears that my issue was during the decompression of the image in `xz` due to compression corruption during the build (Still narrowing that cause down.), not the download, so I'm thinking that obtaining stderr info from the `xz` and `curl` operations might be valuable for display on failure if we start checking the error status.

**Comment by schaefi** [comment]
sorry for the late response

>I do have the rd.debug and rd.kiwi.debug options on, and I believe I'm using the newest version of those Dracut/KIWI Modules as I know I've been able to drop to a Console during previous failures at different stages in the deployment (Like if/when network fails, etc.). The rd.shell option is new to me though. Does that give me the ability to drop to a shell at any time? Or only under the condition that oem-reboot-interactive is also true?

rd.shell is evaluated in the context of an emergency. There is the dracut-emergency.service which calls 98dracut-systemd/dracut-emergency.sh. So only in case of an emergency you will then be dropped into a shell. What an emergency is, is in the hand of the dracut module author

**Comment by schaefi** [comment]
> If rd.shell allows me to drop to a Console at any time

I think this should be doable via ```rd.emergency``` but I never tried that

**Comment by schaefi** [comment]
> so I see an opportunity for improvement of the debug capabilities here.

I'm not sure if I can follow here. Do you mean the debugging capabilities of dracut as a whole or a special debugging opportunity in one or more of the kiwi dracut modules ? I think in general debugging of the initrd can only be done if some sort of console is available, be it a ttySX, some special UART, or some other sort of console. If none is present I would think the system will be in a locked up state as soon as an open to /dev/console fails.

Could you be more specific what type of debugging capabilities you had in mind ? Thanks

**Comment by schaefi** [comment]
> Also, it appears that my issue was during the decompression of the image in xz due to compression corruption during the build (Still narrowing that cause down.), not the download, so I'm thinking that obtaining stderr info from the xz and curl operations might be valuable for display on failure if we start checking the error status.

yes and I thought we do that. There is this generic fetch() method which should write a ```/tmp/fetch.info```

**Comment by schaefi** [comment]
I mark this one as a to be discussed at the community meeting, let's see if the debugging can be improved

**Comment by schaefi** [comment]
Your feedback would be valuable, thanks

**Comment by schaefi** [comment]
Hi, we discussed the debugging issue during the community meeting and the overall result is that we don't like to add extra flags for the purpose of easier debug sessions in kiwi dracut modules. The reasoning was as follows:

1. Adding a debug flag that is kiwi specific increases the dependency of kiwi to its dracut modules. As we aim for the kiwi dracut modules to be optional and not required it would be a weird flag setting that only works under certain conditions
2. Adding a debug flag that makes debugging easier will interfere with the behavior of existing rd. debug flags which is considered unwanted
3. Last but not least the message was raised that the existing debug opportunities provided by dracut itself should be good enough. From my perspective I would agree and since we did not have further information if the provided information here helped you we assume it applies to your case as well

Please re-open if you have a specific case when you could not debug the dracut code, so we can revise the conversation.

Thanks
