### ISSUE TITLE
Installing Quick Start ISO from VMware not working

### ISSUE THREAD

**Issue by juliagomezi** [OSInside/kiwi#2109]
## Problem description
I followed the [quick start](https://documentation.suse.com/kiwi/9/single-html/kiwi/index.html#quick-start) section of the kiwi documentation and the ISO it outputed does not work. It shows the grub menu but when choosing the install option it gets stuck in loading initrd.

## Expected behaviour
ISO is installed.

## Steps to reproduce the behaviour
1. Follow step [Build your first image](https://documentation.suse.com/kiwi/9/single-html/kiwi/index.html#build-your-first-image).
2. Create VM in VMware Workstation Pro 16.
3. Boot from the created ISO.
4. Choose install option in the grub menu.

## OS and Software information
+ KIWI version: 9.24.29
+ Operating system: openSUSE Leap 15.3

**Comment by schaefi** [comment]
I think the issue is that the output is targeted to the serial console. You think it's stuck because VMware by default does not show the serial console.

If you see the grub menu, hit the "e" key which opens an editor. Look for ```console=ttyS0``` and remove this parameter. Hit "Ctrl-x" to boot with your changes. You should see more now ?

If you look at the docs again here:

https://documentation.suse.com/kiwi/9/single-html/kiwi/index.html#run-your-image

you see that the how to run describes the serial console, but for qemu-kvm and not for VMware

Let me know if this helps

Thanks

**Comment by juliagomezi** [comment]
It worked, thanks!
