### ISSUE TITLE
RFE: add an option to set the size of the system partition

### ISSUE THREAD

**Issue by davide125** [OSInside/kiwi#2203]
I'd like to be able to set the exact size of the root partition (via a parameter under `<type>` I guess). I've tried using `<oem-systemsize>` to achieve the same result, but it doesn't seem to have any effect (likely because I have `<oem-resize>` to false as we're using systemd native filesystem growth instead).

**Comment by schaefi** [comment]
You are right, if oem-resize is switched off the size constraint for oem-systemsize is not taken into account. The process for the partition table setup in this creates the partitions according to the requested/or-needed size and the root partition is always last (to allow for resize). The size for this last partition is always the rest space available and as of now an eventual given oem-systemsize is not used in this case.

You can specify

```xml
<type>
    size unit="G">2</size>
</type>
```

to force creation of a 2G disk file which impacts the size of the last partition created. I assume the problem is that you would like to specify an exact size for the root partition in the image which is currently not possible because I don't wanted to create and image which allows to leave a gap in the partition table entries and the disk geometry

* As you perform resize via systemd can you explain why the exact size of the root partition is a requirement ?
* Maybe specifying the size of the disk and influence the root part size that way is an acceptable setting for your use case too ?

Thanks

**Comment by davide125** [comment]
So, the specific issue is that on Apple Silicon we need the volume size to be an exact multiple of 4096 (i.e. size % 4096 == 0). Right now I'm working around that by eyeballing `<size>` and then adding some padding afterwards in a post processing script, but it'd be useful to not have to do that. The resizing done by systemd is unrelated and orthogonal to this.

**Comment by davide125** [comment]
In case it helps, https://pagure.io/fedora-asahi/kiwi-descriptions/blob/rawhide/f/make-asahi-installer-package.sh#_57 is the postprocessing script we're using (and the same repo has the kiwi config).

**Comment by schaefi** [comment]
> So, the specific issue is that on Apple Silicon we need the volume size to be an exact multiple of 4096 (i.e. size % 4096 == 0). Right now I'm working around that by eyeballing `<size>` and then adding some padding afterwards in a post processing script, but it'd be useful to not have to do that. The resizing done by systemd is unrelated and orthogonal to this.

ok understood, thanks for the details. I'll come up with a PR that takes oem-systemsize into account and we can discuss if this will solve your issue. I hope I get to it during the week or on the weekend

**Comment by schaefi** [comment]
@davide125 sorry I'm late on this. Going to work on it now

**Comment by schaefi** [comment]
@davide125 pull request is open for review now
