### ISSUE TITLE
image/preferences/type:image=filesystem unusable in OBS

### ISSUE THREAD

**Issue by olafhering** [OSInside/kiwi#2209]
The documentation claims `<image/preferences/type image="ext4"/>` is supported.
Adding such element leads to `unresolvable: nothing provides kiwi-image:ext4`, most likely because there is no `Provides: kiwi-image:ext4` in `python-kiwi.spec`.

**Comment by schaefi** [comment]
Hi Olaf. Well I had a conversation with the build team, I think it's more than 2 years ago where we announced that the provides tags for imaging features are going to change. The new concept creates a collection of ```kiwi-systemdeps-IMAGE-SCOPE``` packages which pulls in the needed software to create an image matching IMAGE-SCOPE. These systemdeps packages also contains the Provides information which could be consumed by the buildservice. All of this is also documented here:
 
* https://osinside.github.io/kiwi/concept_and_workflow/systemdeps.html#host-requirements-to-build-images

With regards to your specific case the package ```kiwi-systemdeps-filesystems``` would be the correct one.
Its provides list looks the following

```
Provides:       kiwi-image:pxe
Provides:       kiwi-image:kis
%if ! (0%{?rhel} >= 8)
Provides:       kiwi-filesystem:btrfs
%endif
Provides:       kiwi-filesystem:ext2
Provides:       kiwi-filesystem:ext3
Provides:       kiwi-filesystem:ext4
Provides:       kiwi-filesystem:squashfs
Provides:       kiwi-filesystem:xfs
```

As you can see the correct provides for obs to work with would be ```kiwi-filesystem:ext4```

So the magic in the ```build``` script that reads the kiwi image description and constructs a provides tag
out of the ```image="ext4"``` into ```kiwi-image:ext4``` is old and broken because even though I told people and also documented the change it was not applied in obs unfortunately

I myself did not find the time to adapt the code in the obs build. I guess it's this one:

* https://github.com/openSUSE/obs-build/blob/master/Build/Kiwi.pm#L339

I hope this information helps and I rather see the issue to be in obs than in kiwi

Let me know what you think

Thanks

**Comment by schaefi** [comment]
@olafhering any comments on this one ?

**Comment by olafhering** [comment]
If the change needs to be done in obs itself, I will open an issue there.

**Comment by schaefi** [comment]
ok thanks. If there is anything that we can do from the kiwi side to help with this, let us know
