### ISSUE TITLE
archlinux kiwi-test-image-live-disk-kis install iso fails to boot in UEFI mode

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#2232]
## Problem description

The Archlinux [test-image-live-disk-kis](https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:archlinux/test-image-live-disk-kis) install iso fails to boot in UEFI mode with the following error:
![image](https://user-images.githubusercontent.com/45594031/212084374-e54ba960-eb63-4e5d-a4cb-a2a9c4849b9a.png)

## Expected behavior

It should boot just like it does with BIOS

## Steps to reproduce the behavior

- Download https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/archlinux/images/iso/kiwi-test-image-live-disk-kis.x86_64-1.0.0-Disk-Build54.11.install.iso
- boot it in UEFI mode
- wait for it to fail to boot

**Comment by schaefi** [comment]
@davidcassany can you have a look please ?

**Comment by davidcassany** [comment]
Sure I am on it

**Comment by davidcassany** [comment]
Of course related to the `grub.cfg` and the patches we apply on top. The point is that Arch Linux does not require the `BootLoaderConfigGrub2._fix_grub_to_support_dynamic_efi_and_bios_boot` method, so that there is a hack in the ArchLinux test image to revert such a patch see this [editboot script](https://build.opensuse.org/package/view_file/Virtualization:Appliances:Images:Testing_x86:archlinux/test-image-live-disk-kis/_service:obs_scm:editbootinstall_arch.sh?expand=1) within the test. At a time I created this script to workaround the issue for disk images and to prevent having to touch all this grub stuff just for Arch when it was already functional for openSUSE, Fedora and Ubuntu. The editboot script works to fix the disk, but not the installation ISO. @schaefi do you know if there is any way to also run an editbootinstall script for the installation media? I think not.

Long story short, Arch Linux does not have `linuxefi` and `initrdefi` grub2 modules, instead, the `linux` and `initrd` commands are capable to boot in efi and legacy firmwares. IIRC this is what upstream grub2 is doing but this is/was not there yet for openSUSE and other major distros.

So this is, again, an issue related to `linux` vs `linuxefi` and `initrd` vs `initrdefi` commands in grub config. I guess this will also happen in other distros at some point.

I a bit resistant to actually try to fix this at KIWI code, I'd be more in favor of trying to find workarounds at image description level, as long as the bootloader setup is good for the other major distros (Fedora, Debian, Ubuntu and openSUSE) I would try to keep it as is. The glitches around the bootloader setup (aka grub2 everywhere) across different distros is just astonishing...

**Comment by dcermak** [comment]
David Cassany Viladomat ***@***.***> writes:

> Of course related to the `grub.cfg` and the patches we apply on top. The point is that Arch Linux does not require the `BootLoaderConfigGrub2._fix_grub_to_support_dynamic_efi_and_bios_boot` method, so that there is a hack in the ArchLinux test image to revert such a patch see this [editboot script](https://build.opensuse.org/package/view_file/Virtualization:Appliances:Images:Testing_x86:archlinux/test-image-live-disk-kis/_service:obs_scm:editbootinstall_arch.sh?expand=1) within the test. At a time I created this script to workaround the issue for disk images and to prevent having to touch all this grub stuff just for Arch when it was already functional for openSUSE, Fedora and Ubuntu. The editboot script works to fix the disk, but not the installation ISO. @schaefi do you know if there is any way to also run an editbootinstall script for the installation media? I think not.
>
> Long story short, Arch Linux does not have `linuxefi` and `initrdefi` grub2 modules, instead, the `linux` and `initrd` commands are capable to boot in efi and legacy firmwares. IIRC this is what upstream grub2 is doing but this is/was not there yet for openSUSE and other major distros.
>
> So this is, again, an issue related to `linux` vs `linuxefi` and `initrd` vs `initrdefi` commands in grub config. I guess this will also happen in other distros at some point.
>
> I a bit resistant to actually try to fix this at KIWI code, I'd be more in favor of trying to find workarounds at image description level, as long as the bootloader setup is good for the other major distros (Fedora, Debian, Ubuntu and openSUSE) I would try to keep it as is. The glitches around the bootloader setup (aka grub2 everywhere) across different distros is just astonishing...

With openQA in place we could actually give this a try and have decent
test coverage across all the distros. But I can see the arguments for
not bothering at this point as well ;-)
