### ISSUE TITLE
delta containers against system

### ISSUE THREAD

**Issue by rjschwei** [OSInside/kiwi#2309]
## Problem description

At present `delta_root` requires the use of `derived_from` where the value for `derived_from` is some location where a container can be found. However, it would be great if one could build a delta container against bits that are on the build system. Yes that creates a tight coupling between the system and the container and is not in line with he idea of "containers can easily be moved around". However in combination with flake-pilot and from an isolation point of vie as part of a Linux distribution this is a powerful concept in that one can avoid including shared dependencies in many containers and one can consume those from the system.

## Expected behaviour

Add keyword recognition to `derived_from` such that one can use `delta_root="true" derived_from="system"` and then kiwi can sort out the dependencies in the created layer and drop everything that can be found on the system.

**Comment by schaefi** [comment]
Hmm, I think it will be very hard to create that coupling. The "build system" is actually the host you run the kiwi process on. There is not necessarily any connection to the result image you are about to build. Also when kiwi starts to build an image it does that based on an empty ```root/``` directory. In case of a delta we overlay mount that ```root/``` with something pre-existing. The build system in open build service terminology does not even exist because the build worker creates a new environment prior calling kiwi on it. So I don't see a technical way to do this

But I think I have a solution to your problem. iirc you would like to create a coupling of host data for example shared libs should be taken from the host and not provided in the image. This dependency can be created as shown in the following example build:

* https://build.opensuse.org/package/show/home:marcus.schaefer:delta_containers/base_leap_python_system

This image provides a python stack for use in delta_images that needs a python stack. The image itself however does not provide any data from: ```/lib``` ```/usr/lib64/lib*``` ```/usr/bin/*``` ```/bin/*``` If you use this image in combination with the flake-pilot provision code it knows that these data is missing and takes it from the running host.

As you said it creates a tight coupling between the host and the image but it is wanted and you can control what data that should be as part of the image description. For details how this is done take a look at the ```config.sh``` script of the above example.

Let me know what you think

**Comment by schaefi** [comment]
So in short if you build an image that has data provided as ```/removed``` the flake-pilot provisioning takes it from the host. All this data you can delete from your image. And so you are creating a tight coupling between the host OS and the flake. Usually I would avoid that for libraries and binaries because it also makes it hard to update the host OS and guarantee the flake to still work, but for e.g keys, user data, configurations, etc etc it would be ok. In any case we do not prevent any kind of nasty dependency workflow in the flake-pilot provisioning :)

**Comment by schaefi** [comment]
That's also why I created all the different examples and for having conversations about it

**Comment by schaefi** [comment]
As there is no further conversation on this topic and a proposal for a solution is provided, I'm going to close this issue now. @rjschwei if your use case is not covered or further conversation is needed please feel free to open a new issue or reach out for re-opening this one. Latest version of flake-pilot can be found in IBS at Devel:Automotive:ALPA or in OBS at home:marcus.schaefer:EOS
