### ISSUE TITLE
disable header_hybrid on aarch64

### ISSUE THREAD

**Issue by leifliddy** [OSInside/kiwi#2343]
## Problem description

I'm building an aarch64 image on a Fedora aarch64 system, and I'm seeing this in the top of 
`/boot/grub2/grub.cfg` in the final image

```
set linux=linux
set initrd=initrd
if [ "${grub_cpu}" = "x86_64" -o "${grub_cpu}" = "i386" ]; then
    if [ "${grub_platform}" = "efi" ]; then
        set linux=linuxefi
        set initrd=initrdefi
    fi
fi
export linux initrd
#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub2-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub

....
```

I see where that's being set in `./kiwi/bootloader/template/grub2.py`
```
        self.header_hybrid = dedent('''
            set linux=linux
            set initrd=initrd
            if [ "$${grub_cpu}" = "x86_64" -o "$${grub_cpu}" = "i386" ]; then
                if [ "$${grub_platform}" = "efi" ]; then
                    set linux=linuxefi
                    set initrd=initrdefi
                fi
            fi
            export linux initrd
```

But it really should be there at all. I mean it literally has this warning in the file 
```
#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub2-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub
#
```
And the next time you update grub, those `header_hybrid` lines will be removed. 
So my question is -- what purpose does adding these lines actually serve? 
And can we just remove this `header_hybrid` functionality altogether?

Also on a slightly unrelated note, is there a way that can prevent the creation of these files?
``` 
/boot/mbrid
/root/config.bootoptions
/root/config.partids
```
Perhaps those files are used by Suse, but they're not used by Fedora.

**Comment by schaefi** [comment]
Hi,

> is there a way that can prevent the creation of these files?

kiwi creates this file as sort of metadata information that is used under certain circumstances in the dracut modules provided with kiwi. If you build an image that doesn't make use of that boot code you actually don't need this information. However, there is no way to prevent the creation of it. You can simply delete them if you place a ```pre_disk_sync.sh``` script as part of your image description and just delete them, knowing the consequences though :)

**Comment by schaefi** [comment]
> what purpose does adding these lines actually serve?

Regarding the grub issue. So this extra lines exists because of the following code in ```bootloader/config/grub2.py```

```python
def _fix_grub_to_support_dynamic_efi_and_bios_boot(self, config_file):
        if self.firmware.efi_mode():
            # On systems that are configured to use EFI with grub2
            # there is no support for dynamic EFI environment checking.
            # In this condition we change the grub config to add this
            # support as follows:
            #
            # * Apply on grub with EFI
            #    1. Modify grub.cfg to set linux/initrd as variables
            #    2. Prepend hybrid setup to select linux vs. linuxefi on demand
            #
            # Please note this is a one time modification done by kiwi
            # Any subsequent call of the grub config tool will overwrite
            # the setup and disables dynamic EFI environment checking
            # at boot time
            with open(config_file) as grub_config_file:
                grub_config = grub_config_file.read()
                grub_config = re.sub(
                    r'([ \t]+)linux(efi|16)*([ \t]+)', r'\1$linux\3',
                    grub_config 
                )
                grub_config = re.sub(
                    r'([ \t]+)initrd(efi|16)*([ \t]+)', r'\1$initrd\3',
                    grub_config
                )
            with open(config_file, 'w') as grub_config_file:
                grub_config_file.write(
                    Template(self.grub2.header_hybrid).substitute()
                )
                grub_config_file.write(grub_config)
```

We have several of this ```_fix...``` methods and I hate them all together :) but we needed them in order to fix boot issues.

In this particular case the comment of the method actually describes it as I think. If you create an image that can boot in EFI and in BIOS mode which is the default layout of any kiwi disk image that is EFI enabled, there was a difference in loading the kernel and the initrd from grub. We had to differentiate between the commands ```linuxefi | linux``` and ```initrdefi | initrd``` depending how the image was booted. That's why this extra header was placed.

You are right that with the first invocation of grub2-mkconfig all of it will be gone, but at call time in this case you are already in a booted system in either EFI mode or CSM(BIOS) mode and grub2-mkconfig (and the grub tooling around it) has now a chance to identify how the system was booted. We expect the grub tooling to do the right thing and create a sufficient setup for this system. Of course if you now change the way the system boots in the firmware of the machine it could end up with a problem because that initial check is gone.

> And can we just remove this header_hybrid functionality altogether?

At the moment only by adding

```xml
<type ... editbootconfig="my_boot_config.sh"
```

Then write ```my_boot_config.sh``` and patch it out. 

NOTE !!! be careful with ```my_boot_config.sh```, it does NOT run chrooted. So don't reference names with ```/``` because that's your host in this case.

Hope this helps

**Comment by schaefi** [comment]
I was thinking on arm this _fix method doesn't make any sense. So we could also consider to not run this _fix method if building for arm

**Comment by leifliddy** [comment]
> I was thinking on arm this _fix method doesn't make any sense. So we could also consider to not run this _fix method if building for arm. Thoughts ?

That was my thought exactly. If the arch doesn't match `x86_64`  or `i386` , then skip it.

**Comment by schaefi** [comment]
yeah let's do that

**Comment by schaefi** [comment]
PR is out, please double check. Thanks

**Comment by leifliddy** [comment]
LGTM, thanks!
