### ISSUE TITLE
RFC: Enhance KIS image type for embedded use cases

### ISSUE THREAD

**Issue by MofX** [OSInside/kiwi#2355]
Hi,

for embedded use cases, it is often required, to not create a complete image, but separate files for each partition, kernel, initramfs, ....
This is basically what the KIS image type provides, with several caveats:

1. It does not package device trees
2. It does not execute a script like (pre_disk_sync.sh), that allows removing unwanted files and packages AFTER dracut ran
3. It supports only a single partition
4. It does not support adding the verity/integrity metadata
5. It does not allow to remove the kernel from the root filesystem

I have some suggestions, to fix the issues:

1. I did play around with packaging all device trees, that are installed by the kernel package (`/usr/lib/firmware/$(uname -r)/device-tree`). But for a generic kernel these are a lot of files. Maybe narrowing it down using the image description, to explicitly select device trees to include would be a good option?
2. I think @isbm already talked to @schaefi about a patch, that executes the pre_disk_sync script for KIS images was well, but @schaefi  didn't really like it, because it may change behavior. Maybe a solution to avoid this forever in the future while still allowing to add hooks everywhere would be to make them explicit in the image description instead of "magically" executing some files at certain stages of the build. Something like: `<hooks><hook type="pre_disk_sync" name="cleanup.sh" /></hooks>`
3. Adding support for multiple partitions, like the oem config does should be feasible with some refactoring.
4. Same as 3
5. Since one of the last steps in KIS image creation is extracting the kernel from the root filesystem, it is not possible to remove it (or the kernel modules), because there is no hook anymore AFTER extraction and executing dracut. This would be easily fixable with, when 2 is implemented.

Maybe it would be better to create new image type, that is highly customizable and not an enhanced KIS version.

This is not asking to do all the work, this is an rfc and maybe we can come up with a solution, that works for all our needs and help implementing it.

Jörg

**Comment by schaefi** [comment]
Hi Jörg, sorry long time no response on this one. Now I finally get to it.

I agree it might be needed to have a new image type for this sort of archive. Just some feedback on the bullet list

> It supports only a single partition

kis, actually does not partition at all, it only includes a filesystem image of the rootfs

> It does not allow to remove the kernel from the root filesystem

kis, should be possible to do that with a ```<packages type="remove"> ``` section

All other parts you mentioned are not a part of the kis archive and I agree with you the current kiwi image types does not satisfy this needs.

Before we look closer to this and because I know for which use case you need it, I'd like to clarify if you still need it ? I got the information that all of EB Corbos Linux will be build using Canonical's toolchain including the packaging to be done on elbe which is Debians Embedded Linux Build Environment. From that perspective I assume you will also switch the image builder to what elbe provides and in that case any action from here would be without a user.

So if you can give a short update if it's still relevant that would be nice.

Thanks

**Comment by schaefi** [comment]
closing due to no further response
