### ISSUE TITLE
Inconsistent handling of repository types

### ISSUE THREAD

**Issue by isbm** [OSInside/kiwi#2395]
## Problem description

As per [documentation](http://osinside.github.io/kiwi/working_with_images/build_in_buildservice.html?highlight=obsrepositories#repository-configuration), when building on OBS, `<repository>` takes a type. Default is `rpm-md`. If it is set up for `apt-deb`, Kiwi sets up a spaghetti, based on `rpm-md` type:

```xml
<repository type="tomato-potato">
  <source path="obsrepositories:/"/>
</repository>
```

## Expected behaviour

A crash, a failure, a message that only `container` and `rpm-md` are supported at the moment.

**Comment by isbm** [comment]
@schaefi and this leads to a discussion: how do we fix that? Your code _sometimes_ gets repotype, and sometimes skips it, defaulting always to `rpm-md` type. I think this is quite wrong.

Would it be OK if you get a PR, where:
- `kiwi/system/uri.py::Uri` class loses default value of `repo_type` to `rpm-md` but makes it mandatory to be defined explicitly
- `kiwi/system/uri.py::Uri._buildservice_path` does not do `else` (i.e. "default"), but actually does `elif rpm-md`, but `else` leads to crash "Unsupported repo type, valid are: X, Y, Z"
- `Url()` is not initialised in half-baked way sometimes default, sometimes with repo-type, but is always with the repo type
- unit tests are updated to that matter

@wintron04 @osab270844 JFYI

**Comment by schaefi** [comment]
Hmm, I can't follow you on your observations.

1. The allowed values for type in ```<repository>``` are validated by the schema. Using your example gave me the following error 
    ```
    [ INFO    ]: 21:44:18 | RelaxNG validation failed. See jing report:
    [ INFO    ]: 21:44:18 | --> jing: stderr: (no output on stderr), stdout: /var/tmp/kiwi_xslt-7guebt9k:32:38: error: value of attribute "type" is invalid; must be equal to "apt-deb", "apt-rpm", "deb-dir", "mirrors", "rpm-dir" or "rpm-md"
    ```
2. There is no repository default type. The type attribute is optional. If not provided the selected package manager setup the repository according to its capabilities. For zypper,dnf it's rpm-md, for pacman it's pacman, for apt it's a flat or a dist repo and so on. In fact for apt the type argument is a no-op because apt only knows about one basic repotype. I have  a problem if you delete the default setting for repo_type: in the Uri class. It is there to allow a class instance of Uri without an explicit setting for the repo type. In the beginning the type was mandatory but this changed later. In order to stay compatible with the API the default for the parameter has not changed. Also the doc string of the method states it relatively clearly:

    ```
    :param str repo_type: 
            repository type name, defaults to 'rpm-md' and is only
            effectively used when building inside of the open
            build service which maps local repositories to a
            specific environment
    ``` 
I'm not willing to change that in any way as I only see regressions for no good reason

4. The bridge you are creating to obs is probably heading into the code from ```_buildservice_path```. What you see here is super buildservice specific and sort of magic that only makes sense if you know how the obs backend works. I don't like this code either but there is no way to change it because that's how obs works.

The changes you propose will impact the public API and can cause issues when we setup that obs specific buildservice path. The Uri class basically suffered from the requirements of how repos works in obs but changing that to fix an inconsistency can create quite some trouble which I think is not a way we have to go. Also you said it's inconsistent, that part I do not understand. An instance of Uri always has a repo_type, it's default is 'rpm-md' and it's been used only for the obs handling. I would say it's consistent but it's not a good implementation. It would have been better to have a general Uri class that doesn't know about obs and an inherited class from Uri that adds the obs magic. But also this would introduce an API change and I don't see it as so troublesome to be honest.

There are more pressing issues that needs a fix imho

**Comment by schaefi** [comment]
It would also help to understand the real problem (other than a code smell) such that I can reproduce something. You are in this debian world, so we have integration tests for Ubuntu in OBS here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:ubuntu/test-image-live-disk

The image description for this test is here

* https://github.com/OSInside/kiwi/blob/master/build-tests/x86/ubuntu/test-image-live-disk/appliance.kiwi

What needs to be changed such that I can reproduce the problem ?

**Comment by schaefi** [comment]
And maybe I understand the problem. If I delete the repo_type from the test image description then the default repo_type when building in OBS is rpm-md and there is no message about it or warning. Is that the issue you ran into ?

**Comment by schaefi** [comment]
You should always have in mind that the obs backend sets up the repositories. In the obs case the ```_buildservice_path``` is only different for ```container``` everything else is just a path to a repo and there is no way to influence that. Thus the if/else code is the only thing you can do. After obs has setup the repo paths kiwi is called and gets those repo-paths assigned as commandline parameters. The selected package manager now works on these paths. Therefore it shouldn't make any difference if you specify a repo_type or not. But I will wait for your response to understand the real issue and get a reproducer

**Comment by isbm** [comment]
@schaefi well OK, so if it is set like so:

```xml
<repository type="rpm-md">
  <source path="obsrepositories:/"/>
</repository>
```

...what does it mean? From your last comment I understood that there is either "container" or anything else (well, the Python code says so as well). In that case `type="rpm-md"` doesn't have to exist, basically — as long as one doesn't write `type="container"`. Is that correct?

To my understanding, if there are "repository types" and there is `rpm-md` and `apt-deb` then logically, if there is no any notice in the documentation, then one would expect that if the repos are Debian, then it should be as following:

```xml
<repository type="apt-deb">
  <source path="obsrepositories:/"/>
</repository>
```

If I setup it that way, I get the following log (and then image fails):

```
[   82s] [ INFO    ]: 10:01:30 | Setting up repository dir:///./repos/xxxxxxx:/xxx:/release/xUbuntu_22.04
[   82s] [ INFO    ]: 10:01:30 | --> Type: rpm-md
[   82s] [ INFO    ]: 10:01:30 | --> Priority: 10
[   82s] [ INFO    ]: 10:01:30 | --> Translated: /repos/xxxxxxx:/xxx:/release/xUbuntu_22.04
[   82s] [ INFO    ]: 10:01:30 | --> Alias: 9947f82499ba8d993d5c7f38c913d1be
[   82s] [ DEBUG   ]: 10:01:30 | EXEC: [mkdir -p /usr/src/packages/KIWI-oem/build/image-root/repos/xxxxxxx:/xxx:/release/xUbuntu_22.04]
```

So first, shouldn't it say `--> Type: apt-deb` or at least `--> Type: generic` instead? And second this happens then:

```
[   82s] E: The repository 'file:/repos/ubuntu:/22.04/universe-update ./ Release' is not signed.
[   82s] E: The repository 'file:/repos/ubuntu:/22.04/update ./ Release' is not signed.
[   82s] E: The repository 'file:/repos/ubuntu:/22.04/standard ./ Release' is not signed.
[   82s] E: The repository 'file:/repos/ubuntu:/22.04/universe ./ Release' is not signed.
...
(some more not signed paths)
```

And then this:
```
[   82s] Ign:1 file:/repos/nautilos:/2.0:/devel/xUbuntu_22.04 ./ InRelease
[   82s] Get:2 file:/repos/ubuntu:/22.04/universe-update ./ InRelease
[   82s] Ign:2 file:/repos/ubuntu:/22.04/universe-update ./ InRelease
[   82s] Get:3 file:/repos/ubuntu:/22.04/update ./ InRelease
[   82s] Ign:3 file:/repos/ubuntu:/22.04/update ./ InRelease
[   82s] Get:4 file:/repos/ubuntu:/22.04/standard ./ InRelease
[   82s] Ign:4 file:/repos/ubuntu:/22.04/standard ./ InRelease
[   82s] Get:5 file:/repos/ubuntu:/22.04/universe ./ InRelease
[   82s] Ign:5 file:/repos/ubuntu:/22.04/universe ./ InRelease
```

...and then game over. So probably it should be not `rpm-md` but `generic`, if you say it makes no sense to do anything special (on the other hand, setup seems still wrong). Or there is something I am missing, but that's not documented (or I am blind, as always).

_NOTE: I've mangled some paths, but you know them_. 😉

**Comment by isbm** [comment]
One little nitpick that touches my nerve: shouldn't it be `obsrepositories://` (doubleslash)? 😉

**Comment by schaefi** [comment]
The thing is, if you setup

```xml
<source path="obsrepositories:/"/>
```

then kiwi is out of the repository game *completely* The setting above is a placeholder for the OBS use case. This means all repositories are passed by OBS to the kiwi call via ```--set-repo``` and ```--add-repo``` on the commandline when OBS calls kiwi. The value of these settings is created by OBS code from the prj setup of the OBS project. There is not a single kiwi line of code involved anymore which is the reason why I cannot fix this. It is furthermore completely irrelevant if you pass a ```type="..."``` to the ```<repository>``` in this case because there is no code evaluating it when you run in OBS.

I think we had this conversation while I was still part of EB. Debian distribution repos cannot be handled in the OBS prj config. This is the reason why I did not use the obsrepositories:/ magic for the images I created for EB but maintained a list of repos in real kiwi speak e.g

```
<repository type="apt-deb" alias="Nautilos-Devel" repository_gpgcheck="false">
    <source path="obs://nautilos:2.0:devel/xUbuntu_22.04"/>
</repository>
```

A repo definition of this type is really handled by kiwi code and the ```obs://``` mime type is a real URI type that gets translated into a URL if you build locally or a path if you build inside of OBS. Also read:

* https://osinside.github.io/kiwi/concept_and_workflow/repository_setup.html

which should explain this.

But again, as soon as you switch to ```obsrepositories``` you are basically telling kiwi to shut up on repos and let OBS take over control.

If you see repo issues in this case you need to discuss them with the OBS folks as there is no code which we could fix here. I hope this helps a bit

**Comment by isbm** [comment]
@schaefi then I don't understand what was the reason to have these types like `type=rpm-md` instead of just `generic` or `external` or even `obs-managed` which would be crystal clear and intuitive?
