### ISSUE TITLE
Recent changes in systemd-boot and removal of kernel-install break expandable images after use

### ISSUE THREAD

**Issue by ignatenkobrain** [OSInside/kiwi#2417]
872678ea14d57d95dc91dad703eb82b7021de464 does not break expandable image per se, it is able to boot from PXE and expand however any further upgrades of kernel using standard tools like dnf, or even simply regenerating initrd which is exactly thing we need to do after the first boot (because we need to remove keyfile for luks and update crypttab to use TPM2).

Current workaround to this situation for us is:

```bash
sed -i -e '/main.conf/d' /boot/efi/loader/loader.conf
rm -f /boot/efi/loader/entries/main.conf
rm -rf /boot/efi/os/
```

Otherwise new kernels or our changes in initrd are never propagated to reality.

---

I don't know proper solution to this, but it would be great to get loader configs generated exactly same way as the target OS would generate them (that was achieved by using kernel-install in past) so that simple dnf update and such would be able to install new kernels and so on.

**Comment by Conan-Kudo** [comment]
The only place we need to not be generating initramfs twice is ISO images, I don't think we do it multiple times for any other image type. So maybe the fix is to not set the variable to disable kernel-install for non-iso images.

**Comment by schaefi** [comment]
To be honest I don't see a good solution at the moment. In the first implementation I used ```kernel-install``` because it is the way to do it the proper systemd-boot way. The issue here is, kernel-install does not produce correct results if you don't run it on the target OS and host. When building an image you have this situation; Your host is not the target and your build host OS can even be a different OS than the target. kernel-install does very weird things under this condition. In addition and in contrast to the name it does a lot more than just kernel-install. From my perspective the only good solution is that kernel-install becomes image-builder-aware and does not assume it only runs on the target host.

As we probably can't have that shortly what are the options:

1. run kernel-install and add _fix code to fixup its results ? no, we have that for grub already and it sucks to no end
2. don't run kernel-install and create the files for systemd-boot as part of the image builder. That's what we do right now and to be honest I haven't expected that this make kernel-install non functional. I thought if you call kernel-install on the target host it will just overwrite
3. change the code in kiwi that creates the systemd-boot setup files to be kernel-install compatible ? If that would be possible I think it would be a solution, but don't know what compatible means
4. add code to the image description that deletes the entries.conf as written by kiwi and run kernel-install to refresh the state. That's always possible as the workaround showed

None of this solutions are ideal. 

> So maybe the fix is to not set the variable to disable kernel-install for non-iso images.

@Conan-Kudo I did not understand that part to be honest, which variable ? and how would it influence the behavior of kernel-install ?

**Comment by ignatenkobrain** [comment]
@schaefi kernel-install works fine but new entry will never boot because loader.conf has `default main.conf` so the original entry created by kiwi always is default

**Comment by ignatenkobrain** [comment]
May be to make it more clear, I am not having problem that main.conf exists and is used on the first boot. I have problem that standard tasks like kernel upgrade or whatever is supposed to generate new loader configs are never being used due to having main.conf as a default.

**Comment by ignatenkobrain** [comment]
Hit send too soon…

Even in the cloud images, you don't "expand" them (i.e. OEM) but you have RAW/QCOW2 image that has such setup so those are basically affected as well as they can't do `dnf update` to get a new kernel booted on the next boot.

**Comment by schaefi** [comment]
> @schaefi kernel-install works fine but new entry will never boot because loader.conf has `default main.conf` so the original entry created by kiwi always is default

yes I got it, so the kernel-install produced XXX.conf on your host, how does this look like ? Do you think it would be possible for us (from the kiwi side) to create a default .conf file that is compatible with subsequent calls of kernel-install in the later system ?

**Comment by schaefi** [comment]
I did some tests on the systemd-integration test image that we build. This is a TW based system. So the initial layout built by kiwi looks like this

```
localhost:~ # find /boot/efi/
/boot/efi/
/boot/efi/EFI
/boot/efi/EFI/BOOT
/boot/efi/EFI/BOOT/BOOTX64.EFI
/boot/efi/EFI/systemd
/boot/efi/EFI/systemd/systemd-bootx64.efi
/boot/efi/EFI/Linux
/boot/efi/loader
/boot/efi/loader/entries
/boot/efi/loader/entries/main.conf
/boot/efi/loader/loader.conf
/boot/efi/loader/random-seed
/boot/efi/loader/entries.srel
/boot/efi/os
/boot/efi/os/vmlinuz-6.6.7-1-default
/boot/efi/os/initrd-6.6.7-1-default
/boot/efi/NvVars
```

ok, the ```main.conf``` and such

next I call

```
kernel-install add 6.6.7-1-default /boot/vmlinuz-6.6.7-1-default
```

and now there is 

```
localhost:/boot/efi # find /boot/
/boot/
/boot/.vmlinuz-6.6.7-1-default.hmac
/boot/System.map-6.6.7-1-default
/boot/config-6.6.7-1-default
/boot/initrd
/boot/sysctl.conf-6.6.7-1-default
/boot/vmlinuz
/boot/vmlinuz-6.6.7-1-default
/boot/efi
/boot/efi/EFI
/boot/efi/EFI/BOOT
/boot/efi/EFI/BOOT/BOOTX64.EFI
/boot/efi/EFI/systemd
/boot/efi/EFI/systemd/systemd-bootx64.efi
/boot/efi/EFI/Linux
/boot/efi/loader
/boot/efi/loader/entries
/boot/efi/loader/entries/main.conf
/boot/efi/loader/entries/opensuse-tumbleweed-6.6.7-1-default.conf
/boot/efi/loader/loader.conf
/boot/efi/loader/random-seed
/boot/efi/loader/entries.srel
/boot/efi/os
/boot/efi/os/vmlinuz-6.6.7-1-default
/boot/efi/os/initrd-6.6.7-1-default
/boot/efi/NvVars
/boot/efi/opensuse-tumbleweed
/boot/efi/opensuse-tumbleweed/6.6.7-1
/boot/efi/opensuse-tumbleweed/6.6.7-1-defalt
/boot/efi/opensuse-tumbleweed/6.6.7-1-default
/boot/efi/opensuse-tumbleweed/6.6.7-1-default/linux
/boot/efi/opensuse-tumbleweed/6.6.7-1-default/initrd
/boot/initrd-6.6.7-1-default
/boot/mbrid
```

So it creates

```
/boot/efi/loader/entries/opensuse-tumbleweed-6.6.7-1-default.conf
```

which looks like a naming convention from the kernel dir name in /lib/modules/... and the os name probably taken from /etc/os-release (ID)

We can replicate that in kiwi and create these filenames

Would that be correct ?
