### ISSUE TITLE
Drop SYSLINUX/ISOLINUX support

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2433]
## Problem description

SYSLINUX has been abandoned for several years now, and it does not even work with modern versions of the filesystems supported in SYSLINUX. Thus, we should drop our support for ISOLINUX (we already dropped support for SYSLINUX in 2016 in 8217431c7eb0172b37c15f6e0b3772cb4af8ae1a).

**Comment by schaefi** [comment]
yeah we have a fallback to syslinux if you build for x86_64 and explicitly specify ```firmware="bios"```. Meaning we support that users can build an image without EFI for x86_64 intentionally and that uses ```isolinux.bin```. In EFI mode we always support both, the EFI boot as well as an embedded MBR and eltorito.img from grub.

I'd say 99% of all users setup the hybrid EFI boot because it works in all conditions.

That fallback method only exists if there is no grub around. So I'd say we can get rid of all that, but be aware that we will be loosing any ISO boot fallback in case there is no grub

**Comment by schaefi** [comment]
@Conan-Kudo I'm not sure if it's a P1... does it hurt somewhere ?

**Comment by schaefi** [comment]
you misunderstood, I mean for the purpose of booting an ISO, isolinux.bin not syslinux.bin

**Comment by Conan-Kudo** [comment]
Hmm, I'm not sure. I guess it's not "P1" _per se_, but we should drop it before we make our kiwi 10 initial release.

**Comment by schaefi** [comment]
ok I'll prepare a pull request to entirely drop syslinux/isolinux support
