### ISSUE TITLE
Create live images with direct squashfs

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#2447]
Currently kiwi puts the LiveOS inside an ext4 filesystem image which is then put inside a squashfs and then inside ISO9660/UDF.
I don't know the rationale for the current design, but the only reasons I can think of do not apply (anymore):

- Overlay on squashfs should work just fine
- squashfs supports all necessary FS features (hardlinks, sparse files, xattrs). ACLs aren't supported but I don't see any in the current live images.

Avoiding the indirection results in a smaller image (Leap 15.6 went from 588M to 575M), and should also noticably improve performance. It should also make .iso builds quicker.

Currently it looks like there's no existing option that could be reused to switch it off, the FS is hardcoded to ext4 in defaults.py.

**Comment by Vogtinator** [comment]
> The reason for the layout was the compatibility with the upstream dmsquash dracut module. With kiwi-10 (current main branch) we have an opportunity to break compatibility, so maybe a good idea to rethink the live layout

FTR, I started experimenting with that, will try a PR if it works.

**Comment by schaefi** [comment]
Thanks for the update :+1: I was about to also look into it, but if you do it I will stop for the moment. As a hint we have the ```flags="overlay|dmsquash"``` attribute in kiwi. In the ```builder/live.py``` code this is available in the ```self.live_type``` variable. So in your experiments you can say

```
if self.live_type == 'dmsquash':
    # keep the layout compatible with dracut modules upstream
else:
    # introduce a new layout together with the kiwi-live provided dracut module
```

The kiwi-live dracut module exists for some time and we had planned to drop it because meanwhile all features of our own module are available in upstream dmsquash too. However I agree with you we could provide a smaller/better/faster layout as an alternative in the kiwi-live dracut module when upstream cannot afford breaking the compat layer. Adding another layout to the upstream dracut dmsquash is not so easy because the code already has quite some niche cases for former overlay with device-mapper and it was less intrusive to have a small and clean live module. So long story short I think we can have an alternative live module in combination with upstream and customers could decide what they prefer. I think this wouldn't be a bad move for the existing kiwi live dracut and builder code

**Comment by Vogtinator** [comment]
PR created: https://github.com/OSInside/kiwi/pull/2460

It doesn't quite follow what you had in mind, but it's rather simple and small (if you hide whitespace changes).

**Comment by Vogtinator** [comment]
BTW, for testing I ported the live images to schema 7.4 and was able to build them with kiwi from the main branch. So far I didn't notice any issues, just the already known https://bugzilla.opensuse.org/show_bug.cgi?id=1219074.
