### ISSUE TITLE
dracut-kiwi-oem-repart not found because its  kiwi-dracut-oem-repart

### ISSUE THREAD

**Issue by udf2457** [OSInside/kiwi#2524]
kiwi shows the following error:

```
Required dracut module package missing in package list

The package 'dracut-kiwi-oem-repart' is required for the selected
oem image type. Please add the following in your
<packages type="image"> section to your system XML
description:

<package name="dracut-kiwi-oem-repart"/>
```

The problem is, when building a Debian image `dracut-kiwi-oem-repart` does not exist becuase it is actually `kiwi-dracut-oem-repart` (https://packages.debian.org/bookworm/kiwi-dracut-oem-repart)

Therefore the underlying logic should be updated to check `dracut-kiwi-oem-repart || kiwi-dracut-oem-repart`

Your Debian build-test does not pick this up because you have `<oem-resize>false</oem-resize>` set in your `appliance.kiwi` for the Debian build test. 

I am not a Python coder, so I cannot offer a PR.  However a quick scan of your source code suggest this is the offending section: https://github.com/OSInside/kiwi/blob/2bd0ebf6a54db397a875d8ef807cb6aa3783a92d/kiwi/runtime_checker.py#L757C9-L757C32

**Comment by schaefi** [comment]
Uhh, yes good catch. I will update the runtime check. Thanks

**Comment by schaefi** [comment]
> Your Debian build-test does not pick this up because you have <oem-resize>false</oem-resize> set in your appliance.kiwi for the Debian build test.

There is a build test in the ```Disk``` profile which makes use of the resize dracut module. But the problem is that for building the build tests the kiwi packages from upstream are used (Virtualization:Appliances:Staging) and the upstream packaging uses the  ```dracut-kiwi-...``` naming policy. Thus the integration test builds and works for us but when users build against the Debian packages built by the Debian maintainer the names are different. This is unfortunate but can happen for other distributions too. I will come up with a pull request that allows us to match against multiple options.

**Comment by udf2457** [comment]
Thanks for both the clarification and the fix @schaefi
