### ISSUE TITLE
Support custom /etc/crypttab configuration

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#874]
## Problem description

Currently it is not possible to configure an encrypted disk (`luks="password"`) image that can be booted automatically having the key location configured in `/etc/crypttab`. A common use case for that would be having an encrypted disk that boots without user interaction having the key accessible in a removable device (e.g. a USB stick).

## Expected behaviour

It is possible to configure `/etc/crypttab`.

**Comment by sveldhuisen** [comment]
That woud be quite useful. If I may suggest https://github.com/dracut-crypt-ssh/dracut-crypt-ssh also. It would be pretty neat if we could control this in combination with dropbear and Kiwi.

**Comment by Conan-Kudo** [comment]
I'd rather we only leverage functionality present in the baseline dracut package. It gets tricky otherwise.

**Comment by davidcassany** [comment]
> I'd rather we only leverage functionality present in the baseline dracut package. It gets tricky otherwise.

Fully agree, however I could not manage to get `rd.luks.key` and related luks dracut parameters working. So I still believe that some strategy to add some customizations for `/etc/crypttab` makes sense. Probably it changed meanwhile I last tried, but at the time I was having a look a it I really got the impression there was no other way than ignoring `rd.luks*` family for the time being.

**Comment by davidcassany** [comment]
All right, I did some more debugging to this feature. I am still uncertain how we should proceed. First relevant thing I discovered is that dracut (upstream) luks support is not executed if systemd is present in initrd. The `rd.luks.*` parameters documented on dracut docs are just not handled by dracut if systemd dracut module is there (which is the case for KIWI images), instead systemd itself manages the luks device using this [generator](https://www.freedesktop.org/software/systemd/man/systemd-cryptsetup-generator.html). Also this generator is updated to support key files in external devices since last August, see the commit [here](https://github.com/systemd/systemd/commit/70f5f48eb89) (late August 2018). Note that the parameters syntax is not 100% equivalent to what is documented with the dracut crypt module.

Had look to Fedora 29 (that includes close to upstream dracut and systemd versions) but F29 still does not include a systemd version supporting external devices (systemd >= 240). Regarding Tumbleweed I noticed the systemd is up to date, but this not the case for dracut, resulting in dracut-crypt module adding some hooks that I have the feeling that they should not be there.... Gonna continue debugging a bit more, but to my eyes it starts to look like more than few changes in Tumbleweed's dracut might be required to get it working using kernel parameters.

Gonna debug a bit further but trying to generate `/etc/crypttab` including the required data for decrypting the luks device is gaining force after these findings.

**Comment by Conan-Kudo** [comment]
Fedora 30 should have the necessary dependencies.

I've also submitted [dracut-049](https://build.opensuse.org/request/show/705447) for Tumbleweed. Hopefully, that will show up soon...

**Comment by davidcassany** [comment]
Then I'll wait to further dig in this issue until we get dracut 049. @Conan-Kudo thanks a ton for your contributions here!

**Comment by Conan-Kudo** [comment]
dracut-049 has landed in Tumbleweed, and should be present in the next snapshot.

**Comment by schaefi** [comment]
We've dropped the priority for this card since we are uncertain about the direction of a good implementation. Since #1168 was added we support full disk encryption including /boot encrypted.
This moves the stage to enter the luks passphrase into the bootloader. Currently grub's cryptomount does not support entering the master passphrase from a different source than the terminal. There are some patches available here:

* http://grub.johnlane.ie/

But those doesn't seem to have made it into grub upstream so far

If we consider /boot open and on a separate partition we could consider an implementation that reads the passphrase from a boot commandline variable and updates /etc/crypttab in  a way that the systemd service can open the luks container without further user interaction. However we expected this type of support to be present in the luks dracut support upstream. Given the different patchlevels between upstream and the distributions it will be not trivial to sort this out

So in the end there is currently no clear direction for a stable solution :/

@davidcassany: Please correct me or add further information if I missed something

Thanks

**Comment by schaefi** [comment]
From a discussion with David on this we came to the conclusion that there is currently no way for us to improve the situation with a change in kiwi. Whenever there are changes upstream on dracut and or grub that allows us to contribute a good change we will come back to this one and expect new issues that describes potential changes in more detail.
